//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDAirDropHandlerGenericLinks.h"

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerAppStoreLinks : SDAirDropHandlerGenericLinks
{
}

- (id)suitableContentsDescription;	// IMP=0x00000001001075f4
- (long long)transferTypes;	// IMP=0x00000001001075bc
- (id)singleItemActionTitle;	// IMP=0x00000001001075b0
- (_Bool)canHandleTransfer;	// IMP=0x0000000100107590
- (id)candidateIdentifiers;	// IMP=0x00000001001074b8
- (id)initWithTransfer:(id)arg1;	// IMP=0x000000010010747c

@end

