//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SDAutoUnlockIconTransferStore : NSObject
{
    NSMutableDictionary *_transferStore;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000ccf08
- (void)_loadTransferStore;	// IMP=0x00000001000cce40
- (_Bool)imageCachedForHash:(id)arg1 device:(id)arg2;	// IMP=0x00000001000ccc34
- (void)storeCachedImageForHash:(id)arg1 device:(id)arg2 appName:(id)arg3;	// IMP=0x00000001000cc8ac
- (id)init;	// IMP=0x00000001000cc844

@end

