//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "UNUserNotificationCenterDelegate-Protocol.h"

@class NSMutableDictionary, NSSet, NSString, UNUserNotificationCenter;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SDNotificationManager : NSObject <UNUserNotificationCenterDelegate>
{
    _Bool _activated;	// 8 = 0x8
    NSMutableDictionary *_autoFillRequests;	// 16 = 0x10
    UNUserNotificationCenter *_homePodNotifCenter;	// 24 = 0x18
    UNUserNotificationCenter *_homePodMiniNotificationCenter;	// 32 = 0x20
    _Bool _homePodNotifGranted;	// 40 = 0x28
    NSMutableDictionary *_homePodRequests;	// 48 = 0x30
    _Bool _invalidated;	// 56 = 0x38
    NSMutableDictionary *_tvKeyboardRequests;	// 64 = 0x40
    UNUserNotificationCenter *_tvNotifCenter;	// 72 = 0x48
    _Bool _tvNotifGranted;	// 80 = 0x50
    NSMutableDictionary *_watchKeyboardRequests;	// 88 = 0x58
    UNUserNotificationCenter *_watchNotifCenter;	// 96 = 0x60
    _Bool _watchNotifGranted;	// 104 = 0x68
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 112 = 0x70
}

+ (id)sharedManager;	// IMP=0x000000010012e374
- (void).cxx_destruct;	// IMP=0x0000000100136878
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (void)testWatchKeyboardAutoFill;	// IMP=0x0000000100136774
- (void)testWatchKeyboard;	// IMP=0x0000000100136698
- (void)testKeyboardUpdate;	// IMP=0x00000001001365c4
- (void)testKeyboardRemove;	// IMP=0x00000001001364e8
- (void)testKeyboardPostAutoFill;	// IMP=0x00000001001363f4
- (void)testKeyboardPost;	// IMP=0x0000000100136314
- (void)testHandoffPost;	// IMP=0x0000000100136144
- (void)testAutoFillRemove;	// IMP=0x0000000100136068
- (void)testAutofillPost;	// IMP=0x0000000100135f8c
- (void)testPostBasic;	// IMP=0x0000000100135e40
- (void)testPost:(id)arg1;	// IMP=0x0000000100135c44
- (void)userNotificationCenter:(id)arg1 didReceiveNotificationResponse:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001001356c4
- (void)_homePodHandleResponse:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001001351a0
- (void)_homePodHandoffUpdateIfNeeded:(id)arg1 info:(id)arg2;	// IMP=0x0000000100134cd4
- (void)homePodHandoffUpdateIfNeeded:(id)arg1 info:(id)arg2;	// IMP=0x0000000100134bf8
- (void)_homePodHandoffRemoveAll;	// IMP=0x0000000100134b44
- (void)homePodHandoffRemoveAll;	// IMP=0x0000000100134adc
- (void)_homePodHandoffRemove:(id)arg1 reason:(long long)arg2;	// IMP=0x000000010013480c
- (void)homePodHandoffRemove:(id)arg1 reason:(long long)arg2;	// IMP=0x0000000100134760
- (void)_homePodHandoffPostIfNeeded:(id)arg1 info:(id)arg2;	// IMP=0x0000000100134584
- (void)homePodHandoffPostIfNeeded:(id)arg1 info:(id)arg2;	// IMP=0x00000001001344a8
- (id)homePodHandoffContentForDevice:(id)arg1 info:(id)arg2;	// IMP=0x0000000100133f58
- (void)_watchHandleResponse:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100133ea8
- (void)_watchKeyboardUpdate:(id)arg1 rtiData:(id)arg2;	// IMP=0x0000000100133810
- (void)watchKeyboardUpdate:(id)arg1 rtiData:(id)arg2;	// IMP=0x0000000100133734
- (void)_watchKeyboardUpdate:(id)arg1 info:(id)arg2;	// IMP=0x00000001001332c0
- (void)watchKeyboardUpdate:(id)arg1 info:(id)arg2;	// IMP=0x00000001001331e4
- (void)_watchKeyboardRemoveAll;	// IMP=0x0000000100133154
- (void)watchKeyboardRemoveAll;	// IMP=0x00000001001330ec
- (void)_watchKeyboardRemove:(id)arg1;	// IMP=0x0000000100132f58
- (void)watchKeyboardRemove:(id)arg1;	// IMP=0x0000000100132ec0
- (void)_watchKeyboardPostIfNeeded:(id)arg1;	// IMP=0x0000000100132d2c
- (void)watchKeyboardPostIfNeeded:(id)arg1;	// IMP=0x0000000100132c94
- (id)watchKeyboardContentForDevice:(id)arg1;	// IMP=0x00000001001329b0
- (void)_tvAutoFillRemoveAll;	// IMP=0x000000010013290c
- (void)tvAutoFillRemoveAll;	// IMP=0x00000001001328a4
- (void)_tvAutoFillRemove:(id)arg1;	// IMP=0x0000000100132710
- (void)tvAutoFillRemove:(id)arg1;	// IMP=0x0000000100132678
- (void)_tvAutoFillPostIfNeeded:(id)arg1;	// IMP=0x0000000100132304
- (void)tvAutoFillPostIfNeeded:(id)arg1;	// IMP=0x000000010013226c
@property(readonly, copy, nonatomic) NSSet *activeTVAutoFillPrompts;
- (void)_tvKeyboardUpdate:(id)arg1 rtiData:(id)arg2;	// IMP=0x0000000100131b5c
- (void)tvKeyboardUpdate:(id)arg1 rtiData:(id)arg2;	// IMP=0x0000000100131a80
- (void)_tvKeyboardUpdate:(id)arg1 info:(id)arg2;	// IMP=0x000000010013160c
- (void)tvKeyboardUpdate:(id)arg1 info:(id)arg2;	// IMP=0x0000000100131530
- (void)_tvKeyboardRemoveAll;	// IMP=0x00000001001314a0
- (void)tvKeyboardRemoveAll;	// IMP=0x0000000100131438
- (void)_tvKeyboardRemove:(id)arg1;	// IMP=0x00000001001312a4
- (void)tvKeyboardRemove:(id)arg1;	// IMP=0x000000010013120c
- (void)_tvKeyboardPostIfNeeded:(id)arg1 backgroundAction:(_Bool)arg2;	// IMP=0x0000000100131048
- (void)tvKeyboardPostIfNeeded:(id)arg1 backgroundAction:(_Bool)arg2;	// IMP=0x0000000100130f9c
- (id)tvKeyboardContentForDevice:(id)arg1 backgroundAction:(_Bool)arg2;	// IMP=0x0000000100130c98
- (void)_tvHandleResponse:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100130630
- (id)attachmentFromURL:(id)arg1;	// IMP=0x0000000100130418
- (void)_addRequestWithID:(id)arg1 content:(id)arg2 type:(unsigned int)arg3 isHomePodMini:(_Bool)arg4;	// IMP=0x000000010012fbb8
- (void)_addRequestWithID:(id)arg1 content:(id)arg2 type:(unsigned int)arg3;	// IMP=0x000000010012fb5c
- (void)_homePodEnsureStarted:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010012f38c
- (void)_watchEnsureStarted:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010012ef88
- (void)_tvEnsureStarted:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010012eb78
- (void)_update;	// IMP=0x000000010012eafc
- (void)prefsChanged;	// IMP=0x000000010012eaf0
- (void)_invalidate;	// IMP=0x000000010012ea90
- (void)invalidate;	// IMP=0x000000010012ea28
- (void)_activate;	// IMP=0x000000010012e98c
- (void)activate;	// IMP=0x000000010012e924
@property(readonly, copy) NSString *description;
- (id)init;	// IMP=0x000000010012e3e0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

