//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@interface SDUnlockLockStateUpdated : PBCodable <NSCopying>
{
    unsigned int _version;	// 8 = 0x8
    _Bool _unlocked;	// 12 = 0xc
    struct {
        unsigned int version:1;
        unsigned int unlocked:1;
    } _has;	// 16 = 0x10
}

@property(nonatomic) _Bool unlocked; // @synthesize unlocked=_unlocked;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x00000001000c26d4
- (unsigned long long)hash;	// IMP=0x00000001000c2680
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000c25ac
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000c251c
- (void)copyTo:(id)arg1;	// IMP=0x00000001000c24a8
- (void)writeTo:(id)arg1;	// IMP=0x00000001000c242c
- (_Bool)readFrom:(id)arg1;	// IMP=0x00000001000c2424
- (id)dictionaryRepresentation;	// IMP=0x00000001000c203c
- (id)description;	// IMP=0x00000001000c1f88
@property(nonatomic) _Bool hasUnlocked;
@property(nonatomic) _Bool hasVersion;

@end

