//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDUnlockSessionManager.h"

#import "SDUnlockIDSControllerDelegate-Protocol.h"

@class NSDate, NSObject, NSString, NSTimer, SDUnlockSessionRecord;
@protocol OS_dispatch_source;

__attribute__((visibility("hidden")))
@interface SDUnlockKeyManager : SDUnlockSessionManager <SDUnlockIDSControllerDelegate>
{
    _Bool _useEscrowRecord;	// 8 = 0x8
    _Bool _remoteDeviceLocked;	// 9 = 0x9
    _Bool _ltkWaitingForUnlock;	// 10 = 0xa
    _Bool _outstandingStartLTK;	// 11 = 0xb
    _Bool _unlockingForKeybagUnlock;	// 12 = 0xc
    long long _unlockingState;	// 16 = 0x10
    NSTimer *_stashTimer;	// 24 = 0x18
    NSDate *_deviceSwitchUnlockRetryDate;	// 32 = 0x20
    NSObject<OS_dispatch_source> *_stateTimer;	// 40 = 0x28
    NSObject<OS_dispatch_source> *_longTermKeyTimer;	// 48 = 0x30
    SDUnlockSessionRecord *_sessionRecord;	// 56 = 0x38
    CDUnknownBlockType _stashHandler;	// 64 = 0x40
    CDUnknownBlockType _stateHandler;	// 72 = 0x48
    id _keybagAssertion;	// 80 = 0x50
}

+ (id)sharedKeyManager;	// IMP=0x0000000100194e84
- (void).cxx_destruct;	// IMP=0x000000010019c094
@property(retain) id keybagAssertion; // @synthesize keybagAssertion=_keybagAssertion;
@property(copy) CDUnknownBlockType stateHandler; // @synthesize stateHandler=_stateHandler;
@property(copy) CDUnknownBlockType stashHandler; // @synthesize stashHandler=_stashHandler;
@property(retain) SDUnlockSessionRecord *sessionRecord; // @synthesize sessionRecord=_sessionRecord;
@property(retain) NSObject<OS_dispatch_source> *longTermKeyTimer; // @synthesize longTermKeyTimer=_longTermKeyTimer;
@property(retain) NSObject<OS_dispatch_source> *stateTimer; // @synthesize stateTimer=_stateTimer;
@property(retain) NSDate *deviceSwitchUnlockRetryDate; // @synthesize deviceSwitchUnlockRetryDate=_deviceSwitchUnlockRetryDate;
@property _Bool unlockingForKeybagUnlock; // @synthesize unlockingForKeybagUnlock=_unlockingForKeybagUnlock;
@property _Bool outstandingStartLTK; // @synthesize outstandingStartLTK=_outstandingStartLTK;
@property _Bool ltkWaitingForUnlock; // @synthesize ltkWaitingForUnlock=_ltkWaitingForUnlock;
@property _Bool remoteDeviceLocked; // @synthesize remoteDeviceLocked=_remoteDeviceLocked;
@property(retain) NSTimer *stashTimer; // @synthesize stashTimer=_stashTimer;
@property _Bool useEscrowRecord; // @synthesize useEscrowRecord=_useEscrowRecord;
- (_Bool)initiateStashBagCreationWithManifest:(id)arg1;	// IMP=0x000000010019bd1c
- (void)initiateRemoteUnlock;	// IMP=0x000000010019b554
- (void)sendStateRequest;	// IMP=0x000000010019b2b0
- (void)sendStashToken:(id)arg1 sessionID:(unsigned int)arg2;	// IMP=0x000000010019b020
- (void)sendStashKeyRequest:(id)arg1 sessionID:(unsigned int)arg2;	// IMP=0x000000010019ad90
- (void)sendSessionAuthenticationToken:(id)arg1 sessionID:(unsigned int)arg2;	// IMP=0x000000010019abc0
- (void)sendSessionKeyExchangeRequest:(id)arg1 usedEscrow:(_Bool)arg2 sessionID:(unsigned int)arg3;	// IMP=0x000000010019aa00
- (void)sendSetupCreateEscrowRecordWithSessionID:(unsigned int)arg1 stepData:(id)arg2 errorCode:(long long)arg3;	// IMP=0x000000010019a850
- (void)sendSetupSessionCreatedWithLocalKey:(id)arg1 stepData:(id)arg2 sessionID:(unsigned int)arg3 errorCode:(long long)arg4;	// IMP=0x000000010019a668
- (void)sendClassALongTermKeyResponse:(id)arg1 sessionID:(unsigned int)arg2 errorCode:(unsigned int)arg3;	// IMP=0x000000010019a4ac
- (void)sendLongTermKeyResponse:(id)arg1 requestID:(id)arg2;	// IMP=0x000000010019a290
- (void)sendStartLTKTransfer;	// IMP=0x000000010019a068
- (void)handleUnlockStateResponse:(id)arg1;	// IMP=0x0000000100199dbc
- (void)handleStashConfirmation:(id)arg1;	// IMP=0x0000000100199c24
- (void)handleStashKeyExchangeResponse:(id)arg1;	// IMP=0x00000001001998cc
- (void)handleResetState:(id)arg1;	// IMP=0x0000000100199810
- (void)handleUnlockConfirmation:(id)arg1;	// IMP=0x000000010019951c
- (void)handleSessionKeyExchangeResponse:(id)arg1;	// IMP=0x0000000100199090
- (void)handleCreateEscrowSecret:(id)arg1;	// IMP=0x0000000100198c3c
- (void)handleEscrowSessionRequest:(unsigned int)arg1 withUpdatedLongTermKey:(_Bool)arg2;	// IMP=0x0000000100198928
- (void)handleSetupRequest:(id)arg1;	// IMP=0x00000001001986c4
- (_Bool)updateLongTermKey:(id)arg1;	// IMP=0x0000000100198588
- (void)handleClassALongTermKeyRequest:(id)arg1;	// IMP=0x000000010019830c
- (void)handleLongTermKeyRequest:(id)arg1;	// IMP=0x000000010019807c
- (void)handleRemoteLockStateChanged:(id)arg1;	// IMP=0x0000000100197d8c
- (void)idsControllerNearbyStateChanged:(id)arg1;	// IMP=0x0000000100197d14
- (void)idsController:(id)arg1 didReceiveProtoData:(id)arg2 forType:(unsigned short)arg3;	// IMP=0x0000000100197b58
- (id)stringForState:(long long)arg1;	// IMP=0x0000000100197b1c
@property long long unlockingState; // @synthesize unlockingState=_unlockingState;
- (void)resetState;	// IMP=0x0000000100197948
- (void)resetAndClearState;	// IMP=0x0000000100197904
- (void)resetSetupState;	// IMP=0x00000001001978c0
- (void)notifyStashStateWithError:(id)arg1;	// IMP=0x00000001001977ac
- (void)establishStashBagWithManifest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001001974b4
- (void)establishStashBagWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100197228
- (void)invalidateStashTimer;	// IMP=0x00000001001971dc
- (void)stashTimerFired:(id)arg1;	// IMP=0x00000001001970cc
- (void)restartStashTimer;	// IMP=0x0000000100197054
- (void)invalidateStateTimer;	// IMP=0x0000000100196fc4
- (void)restartStateTimer;	// IMP=0x0000000100196d5c
- (void)notifyUnlockStateWithState:(id)arg1 error:(id)arg2;	// IMP=0x0000000100196ce8
- (void)unlockStateForDevice:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100196b84
- (void)syncUnlockEnabled:(_Bool)arg1;	// IMP=0x0000000100196a90
- (_Bool)unlockEnabled;	// IMP=0x0000000100196a0c
- (void)disableUnlockPairingForSecurityManager:(id)arg1;	// IMP=0x0000000100196948
- (void)disableUnlockPairing;	// IMP=0x0000000100196938
- (void)checkDevicePairingState;	// IMP=0x0000000100196800
- (void)handleActiveDeviceUpdated;	// IMP=0x00000001001966c8
- (void)releaseKeyBagAssertion;	// IMP=0x0000000100196644
- (void)takeMobileKeybagAssertion;	// IMP=0x00000001001964e0
- (void)invalidateLongTermKeyTimer;	// IMP=0x0000000100196450
- (void)restartLongTermKeyTimer:(unsigned long long)arg1;	// IMP=0x00000001001962ac
- (void)newDeviceBecameActive:(id)arg1;	// IMP=0x00000001001961c8
- (void)devicesDidFailToPair:(id)arg1;	// IMP=0x0000000100195f0c
- (void)devicesDidUnpair:(id)arg1;	// IMP=0x0000000100195c50
- (_Bool)startUnlockIfNeeded;	// IMP=0x0000000100195b68
- (void)handleUILockStateChange;	// IMP=0x00000001001959c4
- (void)keyBagLockStateChange:(id)arg1;	// IMP=0x0000000100195818
- (void)startLTKExchange;	// IMP=0x00000001001957d4
- (void)handleConfigState;	// IMP=0x00000001001956fc
- (void)deviceDidEnterConfigurationState:(id)arg1;	// IMP=0x000000010019561c
- (id)generateDebugInfo;	// IMP=0x0000000100195390
- (void)debugInfoRequested:(id)arg1;	// IMP=0x000000010019532c
- (void)addObservers;	// IMP=0x0000000100195174
- (id)init;	// IMP=0x0000000100194ef0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

