//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKPlayerProfileCacheReader.h"

@interface GKPlayerProfileNoneCacheReader : GKPlayerProfileCacheReader
{
}

- (id)processAvailableResource:(id)arg1 retrievedWithStatement:(struct sqlite3_stmt *)arg2 fromDatabase:(struct sqlite3 *)arg3 statementStore:(id)arg4;	// IMP=0x000000010012ca9c
- (double)relationshipDetailsTTLProfileStatementResult:(struct sqlite3_stmt *)arg1;	// IMP=0x000000010012ca54
- (double)TTLForProfileStatementResult:(struct sqlite3_stmt *)arg1;	// IMP=0x000000010012ca48
- (int)availablePiecesForProfileStatementResult:(struct sqlite3_stmt *)arg1;	// IMP=0x000000010012ca3c
- (id)playerForProfileStatementResult:(struct sqlite3_stmt *)arg1;	// IMP=0x000000010012c718
- (void)bindParametersForProfileStatement:(struct sqlite3_stmt *)arg1 playerGCID:(id)arg2;	// IMP=0x000000010012c6c8
- (id)playerProfileSQLString;	// IMP=0x000000010012c584

@end

