//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TCCDPolicyOverrideProtected-Protocol.h"

@class NSDictionary, NSMutableDictionary, NSString;
@protocol OS_dispatch_source;

@interface TCCDPolicyOverride : NSObject <TCCDPolicyOverrideProtected>
{
    NSString *plistFilePath;	// 8 = 0x8
    NSDictionary *plistDictionary;	// 16 = 0x10
    NSMutableDictionary *policyAccessByIdentifier;	// 24 = 0x18
    NSObject<OS_dispatch_source> *watchedFileVnodeSource;	// 32 = 0x20
}

+ (unsigned long long)evaluateOverridePolicyForAccessByIdentity:(id)arg1 toService:(id)arg2 withIndirectObjectIdentityIdentity:(id)arg3 authorizationReason:(unsigned long long *)arg4;	// IMP=0x000000010002ace8
+ (void)loadPolicyData;	// IMP=0x000000010002abcc
+ (id)orderedOverridePolicies;	// IMP=0x000000010002ab98
+ (id)useString:(id)arg1 orReadFromDefaults:(struct __CFString *)arg2;	// IMP=0x000000010002ab80
+ (id)queue;	// IMP=0x000000010002ab0c
+ (id)logHandle;	// IMP=0x000000010002aacc
- (void).cxx_destruct;	// IMP=0x000000010002c91c
@property(retain) NSObject<OS_dispatch_source> *watchedFileVnodeSource; // @synthesize watchedFileVnodeSource;
@property(retain) NSMutableDictionary *policyAccessByIdentifier; // @synthesize policyAccessByIdentifier;
@property(retain) NSDictionary *plistDictionary; // @synthesize plistDictionary;
@property(retain) NSString *plistFilePath; // @synthesize plistFilePath;
- (void)watchPlistChanges;	// IMP=0x000000010002c4a4
- (id)watchedPath;	// IMP=0x000000010002c49c
- (unsigned long long)_locked_evaluateAccessByIdentity:(id)arg1 toService:(id)arg2 withIndirectObjectIdentityIdentity:(id)arg3 authorizationReason:(unsigned long long *)arg4;	// IMP=0x000000010002c494
- (void)parsePlist;	// IMP=0x000000010002b8cc
- (_Bool)validateEntry:(id)arg1 identifierType:(id)arg2 codeRequirementString:(id)arg3 serviceName:(id)arg4 allowed:(id)arg5 comment:(id)arg6;	// IMP=0x000000010002b71c
- (id)allowedParser:(id)arg1;	// IMP=0x000000010002b704
- (struct __CFData *)parseCodeRequirements:(id)arg1;	// IMP=0x000000010002b6fc
- (void)loadAndParse;	// IMP=0x000000010002b5e8
- (void)loadPlist;	// IMP=0x000000010002b244
- (id)init;	// IMP=0x000000010002b1c0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

