//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TCCDPolicyOverride.h"

@interface TCCDBinCompatPolicyOverride : TCCDPolicyOverride
{
}

- (id)watchedPath;	// IMP=0x000000010001a234
- (void)loadAndParse;	// IMP=0x000000010001a190
- (id)allowedParser:(id)arg1;	// IMP=0x000000010001a17c
- (id)init;	// IMP=0x000000010001a084

@end

