//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CSEventMonitor.h"

@interface CSSpeechDetectionDevicePresentMonitor : CSEventMonitor
{
}

+ (id)sharedInstance;	// IMP=0x00000001000504a4
- (void)_startObservingSystemControllerLifecycle;	// IMP=0x000000010005093c
- (void)_systemControllerDied:(id)arg1;	// IMP=0x0000000100050838
- (void)_startObservingSpeechDetectionVADPresence;	// IMP=0x0000000100050750
- (_Bool)isPresent;	// IMP=0x00000001000506c8
- (void)handleSpeechDetectionVADPresentChange:(id)arg1;	// IMP=0x00000001000505c8
- (void)_stopMonitoring;	// IMP=0x0000000100050578
- (void)_startMonitoringWithQueue:(id)arg1;	// IMP=0x0000000100050544
- (id)init;	// IMP=0x0000000100050510

@end

