//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IDSPairedDeviceKeychainSchema : NSObject
{
}

- (id)_migrateFromSinglePairedDeviceToMultipleWithKeychainDictionary:(id)arg1;	// IMP=0x000000010017e588
- (id)migrateKeychainDictionary:(id)arg1;	// IMP=0x000000010017e3d8
- (unsigned long long)_migrationTypeForKeychainDictionary:(id)arg1;	// IMP=0x000000010017e200
- (_Bool)isMigrationRequiredForKeychainDictionary:(id)arg1;	// IMP=0x000000010017e170
- (id)_propertyDictionariesFromPairedDevices:(id)arg1;	// IMP=0x000000010017dee8
- (id)keychainDictionaryWithPairedDevices:(id)arg1;	// IMP=0x000000010017dda8

@end

