//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IDSUser-Protocol.h"
#import "NSCopying-Protocol.h"

@class IDSPhoneUser, NSDate, NSString;

@interface IDSTemporaryPhoneUser : NSObject <NSCopying, IDSUser>
{
    _Bool _hasBeenProvisioned;	// 8 = 0x8
    _Bool _finishedRegistration;	// 9 = 0x9
    _Bool _hasNotifiedSuccess;	// 10 = 0xa
    NSDate *_expirationDate;	// 16 = 0x10
    IDSPhoneUser *_phoneUser;	// 24 = 0x18
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00000001001c6cc4
- (void).cxx_destruct;	// IMP=0x00000001001c7670
@property(retain, nonatomic) IDSPhoneUser *phoneUser; // @synthesize phoneUser=_phoneUser;
@property(nonatomic) _Bool hasNotifiedSuccess; // @synthesize hasNotifiedSuccess=_hasNotifiedSuccess;
@property(nonatomic) _Bool finishedRegistration; // @synthesize finishedRegistration=_finishedRegistration;
@property(nonatomic) _Bool hasBeenProvisioned; // @synthesize hasBeenProvisioned=_hasBeenProvisioned;
@property(retain, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
@property(readonly, copy) NSString *description;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001001c71e0
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001001c6fbc
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001001c6ce4
- (_Bool)isIdenticalToUser:(id)arg1;	// IMP=0x00000001001c6ab4
- (_Bool)isEqualToUser:(id)arg1;	// IMP=0x00000001001c6a3c
- (_Bool)isEqualToTemporaryPhoneUser:(id)arg1;	// IMP=0x00000001001c6868
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001001c67ac
@property(readonly) unsigned long long hash;
- (_Bool)shouldReplace:(id)arg1;	// IMP=0x00000001001c66f0
@property(readonly, nonatomic) NSString *networkCode;
@property(readonly, nonatomic) NSString *countryCode;
@property(readonly, nonatomic) NSString *phoneNumber;
- (id)storageIdentifier;	// IMP=0x00000001001c644c
- (id)unprefixedIdentifier;	// IMP=0x00000001001c63e0
- (id)realmPrefixedIdentifier;	// IMP=0x00000001001c6374
- (long long)realm;	// IMP=0x00000001001c635c
- (id)uniqueIdentifier;	// IMP=0x00000001001c6220
- (id)temporaryPhoneUserWithNotifiedSuccess;	// IMP=0x00000001001c6194
- (id)temporaryPhoneUserWithFinishedRegistration;	// IMP=0x00000001001c6108
- (id)temporaryPhoneUserWithUpdatedExpirationDate:(id)arg1;	// IMP=0x00000001001c6034
- (id)initWithPhoneUser:(id)arg1 expirationDate:(id)arg2 finishedRegistration:(_Bool)arg3;	// IMP=0x00000001001c5ef8
- (id)initWithPhoneUser:(id)arg1;	// IMP=0x00000001001c5dfc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

