//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SQLiteEntity.h"

@interface CloudStoreContainerDatabase : SQLiteEntity
{
}

+ (id)_predicateForPID:(long long)arg1;	// IMP=0x000000010028f104
+ (id)_predicateForScope:(long long)arg1;	// IMP=0x000000010028f090
+ (id)_predicateForContainerName:(id)arg1;	// IMP=0x000000010028f070
+ (id)_predicateForContainerName:(id)arg1 scope:(long long)arg2;	// IMP=0x000000010028ef60
+ (id)anyInDatabase:(id)arg1 withPID:(long long)arg2;	// IMP=0x000000010028eed0
+ (id)anyInDatabase:(id)arg1 withContainerName:(id)arg2 scope:(long long)arg3;	// IMP=0x000000010028ee3c
+ (void)removeCloudStoreDatabaseWithContainerName:(id)arg1 scope:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x000000010028ed34
+ (id)_cloudStoreDatabaseWithContainerName:(id)arg1 scope:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x000000010028ecc8
+ (id)insertOrUpdateCloudStoreDatabaseWithContainerName:(id)arg1 scope:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x000000010028ea80
+ (id)databaseTable;	// IMP=0x000000010028ea74
- (id)_commonDictionaryFoDatabaseWithScope:(long long)arg1 containerName:(id)arg2;	// IMP=0x000000010028f25c
- (id)databaseSubscription;	// IMP=0x000000010028f1ec
- (id)cloudStoreZones;	// IMP=0x000000010028f178
- (_Bool)deleteFromDatabase;	// IMP=0x000000010028edb4
- (void)updateWithDatabaseSubscription:(id)arg1;	// IMP=0x000000010028ec70
- (void)updateWithContainerName:(id)arg1 scope:(long long)arg2;	// IMP=0x000000010028ec18
- (id)initWithCloudStoreDatabaseWithContainerName:(id)arg1 scope:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x000000010028eb58

@end

