//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SQLiteEntity.h"

@interface CreditAccountFeatureDescriptor : SQLiteEntity
{
}

+ (id)_propertySettersForCreditAccountFeatureDescriptor;	// IMP=0x000000010024a39c
+ (id)_creditAccountFeatureDescriptorsWithQuery:(id)arg1;	// IMP=0x000000010024a1c8
+ (id)_predicateForFeatureIdentifier:(id)arg1;	// IMP=0x000000010024a038
+ (id)_predicateForAccountPID:(long long)arg1;	// IMP=0x0000000100249fc4
+ (void)updateCreditAccountFeatureDescriptors:(id)arg1 forAccountPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x0000000100249688
+ (id)creditAccountFeatureDescriptorsForAccountPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x00000001002490ec
+ (void)deleteCreditAccountFeatureDescriptorsForAccountPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x000000010024904c
+ (id)associationPropertyForEntityClass:(Class)arg1;	// IMP=0x0000000100249014
+ (id)databaseTable;	// IMP=0x0000000100249008
- (id)creditAccountFeatureDescriptor;	// IMP=0x000000010024a058
- (void)updateWithCreditFeatureDescriptor:(id)arg1;	// IMP=0x0000000100249b4c
- (id)initWithCreditAccountFeatureDescriptor:(id)arg1 forAccountPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x00000001002491a4

@end

