//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PDCloudStoreContainer.h"

#import "PDAccountManagerObserver-Protocol.h"
#import "PDCloudStoreContainerDatabaseDataSource-Protocol.h"

@class NSMutableSet, NSSet, NSString, PDAccountManager, PDFamilyCircleManager, PDPaymentWebServiceCoordinator, PDSpotlightIndexer, PKPaymentTransactionProcessor, PKPeerPaymentAccount;

@interface PDApplePayCloudStoreContainer : PDCloudStoreContainer <PDAccountManagerObserver, PDCloudStoreContainerDatabaseDataSource>
{
    struct os_unfair_lock_s _fetchLock;	// 8 = 0x8
    _Bool _proactiveFetchInProgress;	// 12 = 0xc
    _Bool _ensuringZoneShareIntegrityInProgress;	// 13 = 0xd
    NSMutableSet *_fetchingTransactionsForTransactionSourceIdentifiers;	// 16 = 0x10
    PKPaymentTransactionProcessor *_transactionProcessor;	// 24 = 0x18
    PDPaymentWebServiceCoordinator *_paymentWebServiceCoordinator;	// 32 = 0x20
    PDFamilyCircleManager *_familyCircleManager;	// 40 = 0x28
    PDAccountManager *_accountManager;	// 48 = 0x30
    PDSpotlightIndexer *_spotlightIndexer;	// 56 = 0x38
    PKPeerPaymentAccount *_peerPaymentAccount;	// 64 = 0x40
    NSSet *_accounts;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x000000010006ebdc
- (void)_parseAccountEventsFromRecordParser:(id)arg1 databaseIdentifier:(id)arg2 shouldUpdateLocalDatabase:(_Bool)arg3 shouldReturn:(_Bool)arg4 updateReasons:(unsigned long long)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x000000010006e694
- (id)_recordsByFromAccountEvent:(id)arg1 zone:(id)arg2;	// IMP=0x000000010006e4a8
- (void)_fetchMissingAccountEventsWithRecordParser:(id)arg1 request:(id)arg2 databaseIdentifier:(id)arg3 carriedOverRecordsByDatabaseIdentifier:(id)arg4 updateReasons:(unsigned long long)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x000000010006c5f0
- (id)_recordTypeForAccountEventRecord:(id)arg1;	// IMP=0x000000010006c5a4
- (_Bool)_isAccountEventAssociatedObjectFromRecordType:(id)arg1;	// IMP=0x000000010006c450
- (_Bool)_isAccountEventFromRecordType:(id)arg1;	// IMP=0x000000010006c43c
- (void)_saveTransactionFetchRetries:(id)arg1;	// IMP=0x000000010006c400
- (id)_transactionFetchRetries;	// IMP=0x000000010006c24c
- (void)_fetchTransactionsAttemptForTransactionSourceIdentifier:(id)arg1;	// IMP=0x000000010006c138
- (void)_resetFetchTransactionsForTransactionSourceIdentifier:(id)arg1;	// IMP=0x000000010006c0b0
- (_Bool)_shouldFetchTransactionsForTransactionSourceIdentifier:(id)arg1;	// IMP=0x000000010006bff8
- (id)_originDeviceIDForCloudStoreRecord:(id)arg1;	// IMP=0x000000010006bf64
- (id)_transactionSourceIdentifierForTransactionCloudStoreRecord:(id)arg1 databaseIdentifier:(id)arg2;	// IMP=0x000000010006b8a0
- (id)_transactionSourceIdentifierForTransactionRecordID:(id)arg1 recordType:(id)arg2 databaseIdentifier:(id)arg3;	// IMP=0x000000010006af8c
- (void)_fetchMissingTransactionRecordsWithRecordParser:(id)arg1 request:(id)arg2 databaseIdentifier:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010006a218
- (void)_processShareWithRecordParser:(id)arg1 request:(id)arg2 databaseIdentifier:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100068478
- (_Bool)_canFormTransactionFromCloudStoreRecord:(id)arg1;	// IMP=0x0000000100068224
- (_Bool)_canFormShareFromCloudStoreRecord:(id)arg1;	// IMP=0x00000001000681b0
- (id)_parseTransactionRecords:(id)arg1 request:(id)arg2 databaseIdentifier:(id)arg3 updateReasons:(unsigned long long)arg4;	// IMP=0x0000000100067054
- (void)containerResetCompletedWithSuccess:(_Bool)arg1 error:(id)arg2;	// IMP=0x0000000100066a80
- (_Bool)_isTransactionItemFromRecordType:(id)arg1;	// IMP=0x0000000100066a0c
- (id)_originDeviceID;	// IMP=0x00000001000669f8
- (id)_cloudStoreSpecificKeysForItem:(id)arg1 paymentPass:(id)arg2;	// IMP=0x0000000100066648
- (id)_paymentApplicationForPassUniqueIdentifier:(id)arg1;	// IMP=0x0000000100066580
- (long long)_numberOfActiveTransactionSources;	// IMP=0x0000000100066160
- (_Bool)_queue_isRelevantTransactionSourceIdentifier:(id)arg1;	// IMP=0x0000000100065de0
- (void)_queue_familyMembersByAppleIDWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100065ac8
- (void)_handleFamilyUpdateNotification:(id)arg1;	// IMP=0x00000001000659e0
- (id)_cloudStoreZonesForTransactionSourceIdentifier:(id)arg1;	// IMP=0x00000001000653e4
- (void)_createOrRemoveZoneSharesIfNecessaryWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000640a0
- (void)_queue_ensureZoneShareIntegrity;	// IMP=0x0000000100063f34
- (id)_accountZoneNamesForAccount:(id)arg1 containerDatabase:(id)arg2;	// IMP=0x0000000100063e28
- (id)_accountZoneNamesForAccountSet:(id)arg1 containerDatabase:(id)arg2;	// IMP=0x0000000100063c7c
- (id)_peerPaymentZoneNamesForAccount:(id)arg1 containerDatabase:(id)arg2;	// IMP=0x0000000100063b6c
- (void)_queue_updateWithPossibleNewZonesToAdd:(id)arg1 orphanedZones:(id)arg2 containerDatabase:(id)arg3;	// IMP=0x00000001000634cc
- (void)_queue_processAccountChangeWithOldAccounts:(id)arg1 newAccounts:(id)arg2;	// IMP=0x0000000100063340
- (void)_queue_processPeerPaymentAccountChangeWithOldAccount:(id)arg1 newPeerPaymentAccount:(id)arg2;	// IMP=0x00000001000631b4
- (id)cloudStoreZonesForItemType:(unsigned long long)arg1 configuration:(id)arg2 action:(unsigned long long)arg3 inContainerDatabase:(id)arg4;	// IMP=0x00000001000626fc
- (id)cloudStoreZonesForItem:(id)arg1 action:(unsigned long long)arg2 inContainerDatabase:(id)arg3;	// IMP=0x0000000100061a68
- (id)zoneIDForSubscription:(id)arg1 inContainerDatabase:(id)arg2;	// IMP=0x0000000100061904
- (id)subscriptionForZone:(id)arg1 inContainerDatabase:(id)arg2;	// IMP=0x000000010006178c
- (id)possibleDatabaseSubscriptionForContainerDatabase:(id)arg1;	// IMP=0x000000010006164c
- (id)allPossibleZoneSubscriptionsForContainerDatabase:(id)arg1;	// IMP=0x0000000100061460
- (id)allPossibleZoneNamesForContainerDatabase:(id)arg1;	// IMP=0x0000000100061224
- (void)accountManager:(id)arg1 didUpdateAccount:(id)arg2 oldAccount:(id)arg3;	// IMP=0x0000000100060fe4
- (void)accountManager:(id)arg1 didRemoveAccount:(id)arg2;	// IMP=0x0000000100060de0
- (void)accountManager:(id)arg1 didAddAccount:(id)arg2;	// IMP=0x0000000100060a8c
- (void)_handlePeerPaymentAccountChanged:(id)arg1;	// IMP=0x00000001000608fc
- (void)populateEvents:(id)arg1 forAccountIdentifier:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010005fea4
- (void)uploadTransaction:(id)arg1 forTransactionSourceIdentifier:(id)arg2 includeServerData:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010005f134
- (void)generateRandomTransactionForTransactionSourceIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010005ef88
- (void)syncTransactionsToCloudStoreOriginatedOnDevice:(unsigned long long)arg1;	// IMP=0x000000010005ef40
- (void)passDidDisappear:(id)arg1;	// IMP=0x000000010005eddc
- (_Bool)_queue_canSyncTransactionToCloudKit:(id)arg1 forTransactionSourceIdentifier:(id)arg2;	// IMP=0x000000010005ed00
- (void)canSyncTransactionToCloudKit:(id)arg1 forTransactionSourceIdentifier:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010005ebb0
- (void)canSyncTransactionFromCloudKitForTransactionSourceIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010005ea94
- (void)_fetchAndStoreRecordsForTransactionSourceIdentifier:(id)arg1 groupName:(id)arg2 groupNameSuffix:(id)arg3 returnRecords:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x000000010005d98c
- (void)fetchAndStoreRecordsForTransactionSourceIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010005d870
- (void)requestUpdatesForTransactionSourceIdentifier:(id)arg1;	// IMP=0x000000010005cfd4
- (void)_queue_cloudStoreZoneInvitationDataForInvitation:(id)arg1 toRecipient:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010005c4f8
- (id)_stripToFirstDash:(id)arg1;	// IMP=0x000000010005c470
- (id)identifierFromRecord:(id)arg1;	// IMP=0x000000010005c098
- (id)recordTypesForCloudStoreItemType:(unsigned long long)arg1;	// IMP=0x000000010005beec
- (void)_queue_processResultWithError:(id)arg1 nextExpectedState:(unsigned long long)arg2 operationGroupNameSuffix:(id)arg3 retryCount:(unsigned long long)arg4 shouldRetry:(_Bool)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x000000010005bd3c
- (void)processFetchedCloudStoreDataWithModifiedRecordsByDatabaseIdentifier:(id)arg1 deletedRecordsByDatabaseIdentifier:(id)arg2 carriedOverRecordsByDatabaseIdentifier:(id)arg3 request:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x000000010005abd4
- (void)_deleteLocalDataFromDeletedRecordsByDatabaseIdentifier:(id)arg1;	// IMP=0x000000010005a504
- (_Bool)shouldContinueWithRequest:(id)arg1;	// IMP=0x000000010005a2f4
- (void)coalesceRequest:(id)arg1 withNewRequest:(id)arg2;	// IMP=0x000000010005a01c
- (_Bool)canCoalesceRequest:(id)arg1 withNewRequest:(id)arg2;	// IMP=0x0000000100059db8
- (void)_queue_setContainerState:(unsigned long long)arg1 operationGroupNameSuffix:(id)arg2 retryCount:(unsigned long long)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100059370
- (void)_queue_cloudStoreAccountChanged:(id)arg1;	// IMP=0x0000000100058c4c
- (id)cloudStoreSpecificKeysForItem:(id)arg1;	// IMP=0x00000001000589f4
- (_Bool)_queue_canInvalidateContainer;	// IMP=0x00000001000587c8
- (_Bool)_queue_canInitializeContainer;	// IMP=0x00000001000583bc
- (_Bool)_queue_shouldFetchAndStoreCloudDataAtStartup;	// IMP=0x000000010005825c
- (void)canOverrideChangeTokenForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000581a0
- (void)invalidateCloudStoreIfPossibleWithOperationGroupNameSuffix:(id)arg1 clearCache:(_Bool)arg2;	// IMP=0x000000010005803c
- (void)dealloc;	// IMP=0x0000000100057fe0
- (id)initWithDataSource:(id)arg1 transactionProcessor:(id)arg2 accountManager:(id)arg3 paymentWebServiceCoordinator:(id)arg4 familyCircleManager:(id)arg5 spotlightIndexer:(id)arg6;	// IMP=0x0000000100057a5c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

