//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class UIView, _UIFloatingContentView;

@interface TVNPFloatingContentControl : UIControl
{
    _UIFloatingContentView *_floatingContentView;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010001cf58
@property(readonly, nonatomic) _UIFloatingContentView *floatingContentView; // @synthesize floatingContentView=_floatingContentView;
- (unsigned long long)_currentControlState;	// IMP=0x000000010001cf00
- (_Bool)_canHandlePresses:(id)arg1;	// IMP=0x000000010001ce6c
- (void)_setupConstraints;	// IMP=0x000000010001c9dc
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010001c91c
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010001c870
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010001c7c4
- (_Bool)canBecomeFocused;	// IMP=0x000000010001c7bc
- (void)setHighlighted:(_Bool)arg1;	// IMP=0x000000010001c748
- (void)setControlState:(unsigned long long)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x000000010001c730
- (void)setControlState:(unsigned long long)arg1 animated:(_Bool)arg2;	// IMP=0x000000010001c718
@property(readonly, nonatomic) UIView *contentView;
- (id)init;	// IMP=0x000000010001c5e8

@end

