//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class PRXPCActivityManager, PRXPCServicesManager;
@protocol OS_dispatch_queue;

@interface PRDaemon : NSObject
{
    NSObject<OS_dispatch_queue> *_eventQueue;	// 8 = 0x8
    PRXPCActivityManager *_xpcActivityManager;	// 16 = 0x10
    PRXPCServicesManager *_xpcManager;	// 24 = 0x18
}

+ (void)migrateDirectories;	// IMP=0x00000001000224f8
- (void).cxx_destruct;	// IMP=0x00000001000230d0
- (void)startServices;	// IMP=0x0000000100023010
- (void)run;	// IMP=0x0000000100022d20
- (id)init;	// IMP=0x0000000100022bec

@end

