//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class AVSystemController, NSHashTable, NSMutableArray;
@protocol OS_dispatch_queue;

@interface ADAVSystemControllerLifecycleManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_accessQueue;	// 16 = 0x10
    AVSystemController *_avSystemController;	// 24 = 0x18
    NSMutableArray *_pendingCompletions;	// 32 = 0x20
    NSHashTable *_observers;	// 40 = 0x28
}

+ (id)sharedManager;	// IMP=0x00000001000ffb90
- (void).cxx_destruct;	// IMP=0x000000010010061c
- (void)_flushPendingCompletions;	// IMP=0x00000001001004ec
- (void)_setAVSystemController:(id)arg1;	// IMP=0x0000000100100300
- (void)avSystemControllerDied:(id)arg1;	// IMP=0x00000001001001d0
- (void)fetchAVSystemControllerInBackground;	// IMP=0x00000001001000a0
- (void)removeObserver:(id)arg1;	// IMP=0x0000000100100008
- (void)addObserver:(id)arg1;	// IMP=0x00000001000fff70
- (void)getAVSystemControllerWithTimeout:(double)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000ffd2c
- (id)init;	// IMP=0x00000001000ffbfc

@end

