//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface ADDictationOfflineStatusObserver : NSObject
{
    NSDictionary *_offlineDictationStatus;	// 8 = 0x8
}

+ (id)_offlineDictationStatusStringToDictionary:(id)arg1;	// IMP=0x000000010006a6e4
+ (id)sharedDictationOfflineStatusObserver;	// IMP=0x000000010006a658
- (void).cxx_destruct;	// IMP=0x000000010006b020
@property(retain, nonatomic) NSDictionary *offlineDictationStatus; // @synthesize offlineDictationStatus=_offlineDictationStatus;
- (void)fetchOfflineDictationStatusIgnoringCache:(_Bool)arg1 asynchronously:(_Bool)arg2;	// IMP=0x000000010006ab80
- (void)_updateOfflineDictationStatus:(id)arg1 error:(id)arg2;	// IMP=0x000000010006a944

@end

