//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol AFAnalyticsService, OS_dispatch_group, OS_dispatch_queue;

@interface AFAnalytics : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSObject<OS_dispatch_group> *_group;	// 16 = 0x10
    id <AFAnalyticsService> _service;	// 24 = 0x18
}

+ (id)sharedAnalytics;	// IMP=0x00000001001abaf8
- (void).cxx_destruct;	// IMP=0x00000001001ad5c8
- (id)_service:(_Bool)arg1;	// IMP=0x00000001001ad57c
- (void)_stageEvents:(id)arg1;	// IMP=0x00000001001ad504
- (void)_stageEvent:(id)arg1;	// IMP=0x00000001001ad41c
- (void)barrier:(CDUnknownBlockType)arg1;	// IMP=0x00000001001ad378
- (void)logEvents:(id)arg1;	// IMP=0x00000001001ad2e0
- (void)logEvent:(id)arg1;	// IMP=0x00000001001ad248
- (void)logEventWithType:(long long)arg1 machAbsoluteTime:(unsigned long long)arg2 contextResolver:(CDUnknownBlockType)arg3;	// IMP=0x00000001001ad070
- (void)logEventWithType:(long long)arg1 machAbsoluteTime:(unsigned long long)arg2 contextProvider:(CDUnknownBlockType)arg3 contextProvidingQueue:(id)arg4;	// IMP=0x00000001001acc88
- (void)logEventWithType:(long long)arg1 machAbsoluteTime:(unsigned long long)arg2 context:(id)arg3 contextNoCopy:(_Bool)arg4;	// IMP=0x00000001001ac97c
- (void)setService:(id)arg1;	// IMP=0x00000001001ac8ec
- (void)boostQueuedEvents:(CDUnknownBlockType)arg1;	// IMP=0x00000001001ac6ec
- (void)logInstrumentationOfType:(Class)arg1 machAbsoluteTime:(unsigned long long)arg2 turnIdentifier:(id)arg3;	// IMP=0x00000001001ac5d8
- (void)logInstrumentationOfType:(Class)arg1 turnIdentifier:(id)arg2;	// IMP=0x00000001001ac580
- (void)endEventsGrouping;	// IMP=0x00000001001ac4e0
- (void)beginEventsGrouping;	// IMP=0x00000001001ac440
- (void)logInstrumentation:(id)arg1 machAbsoluteTime:(unsigned long long)arg2 turnContext:(id)arg3;	// IMP=0x00000001001ac0ac
- (void)logInstrumentation:(id)arg1 machAbsoluteTime:(unsigned long long)arg2 turnIdentifier:(id)arg3;	// IMP=0x00000001001abfec
- (void)logInstrumentation:(id)arg1 turnContext:(id)arg2;	// IMP=0x00000001001abf80
- (void)logEventWithType:(long long)arg1 contextResolver:(CDUnknownBlockType)arg2;	// IMP=0x00000001001abefc
- (void)logEventWithType:(long long)arg1 contextProvider:(CDUnknownBlockType)arg2 contextProvidingQueue:(id)arg3;	// IMP=0x00000001001abe54
- (void)logEventWithType:(long long)arg1 contextProvider:(CDUnknownBlockType)arg2;	// IMP=0x00000001001abdcc
- (void)logEventWithType:(long long)arg1 context:(id)arg2 contextNoCopy:(_Bool)arg3;	// IMP=0x00000001001abd38
- (void)logEventWithType:(long long)arg1 context:(id)arg2;	// IMP=0x00000001001abcb0
- (void)logEventWithType:(long long)arg1 machAbsoluteTime:(unsigned long long)arg2 context:(id)arg3;	// IMP=0x00000001001abc18
- (id)_init;	// IMP=0x00000001001abb70
- (id)init;	// IMP=0x00000001001aba60
- (void)configureForDaemon;	// IMP=0x000000010003e8e0
- (CDUnknownBlockType)_ad_contextLoggerWithEventType:(long long)arg1 context:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000c086c

@end

