//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/SABaseCommand.h>

#import "ADClientFlowServiceCommand-Protocol.h"

@class NSString;

@interface SABaseCommand (DeviceRouting) <ADClientFlowServiceCommand>
+ (_Bool)ad_shouldClassLogToMetrics;	// IMP=0x00000001002a002c
- (id)ad_executionDeviceForDeviceContexts:(id)arg1 proximityMap:(id)arg2 localDeviceIsFollower:(_Bool)arg3 logNearbyDeviceMetrics:(_Bool)arg4;	// IMP=0x00000001000609f4
- (_Bool)ad_requiresProximityInformation;	// IMP=0x00000001000609ec
- (void)_ad_performWithTargetQueue:(id)arg1 executionContext:(id)arg2 replyHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010008c954
- (long long)resultCallbackCode;	// IMP=0x00000001001a54e8
- (_Bool)ad_shouldBeHandledByClientAsResponseToCommand:(id)arg1 fromPeer:(id)arg2;	// IMP=0x00000001001a5b64
- (_Bool)ad_shouldIgnoreCallbacksOnReply;	// IMP=0x00000001001a5b5c
- (_Bool)ad_sendReplyEvenIfCallbacksExist;	// IMP=0x00000001001a5b54
- (_Bool)ad_hasCallbacks;	// IMP=0x00000001001a5b4c
- (id)ad_callbacks;	// IMP=0x00000001001a5b6c
- (void)handleWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001001e3834
- (_Bool)shouldBeHandledByAssistantd;	// IMP=0x00000001001e382c
- (long long)ad_getNetworkActivityTracingLabel;	// IMP=0x00000001002a00f8
- (_Bool)ad_requiresResponse;	// IMP=0x00000001002a00f0
- (id)ad_deferredMetricsContext;	// IMP=0x00000001002a0034
- (_Bool)ad_shouldLogToMetrics;	// IMP=0x00000001002a0010
- (_Bool)ad_willHaveReply;	// IMP=0x00000001002a0008
@property(retain, nonatomic, setter=ad_setParentRequest:) SABaseCommand *ad_parentRequest;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

