//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SQLiteEntity.h"

@interface CreditAccountBalanceSummary : SQLiteEntity
{
}

+ (id)_propertySettersForCreditAccountBalanceSummary;	// IMP=0x0000000100238044
+ (id)_predicateForCreditAccountSummaryPID:(long long)arg1;	// IMP=0x0000000100237fd0
+ (void)updateCreditAccountBalanceSummary:(id)arg1 forCreditAccountSummaryPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x000000010023797c
+ (id)creditAccountBalanceSummaryForCreditAccountSummaryPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x00000001002378c8
+ (void)deleteCreditAccountBalanceSummaryForCreditAccountSummaryPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x0000000100237828
+ (id)insertAccountBalanceSummary:(id)arg1 forCreditAccountSummaryPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x00000001002377ac
+ (id)associationPropertyForEntityClass:(Class)arg1;	// IMP=0x00000001002371a8
+ (id)databaseTable;	// IMP=0x000000010023719c
- (id)creditAccountBalanceSummary;	// IMP=0x0000000100238760
- (void)updateWithCreditAccountBalanceSummary:(id)arg1;	// IMP=0x0000000100237a78
- (id)initWithCreditAccountBalanceSummary:(id)arg1 forCreditAccountSummaryPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x00000001002371e0

@end

