//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PDUserNotification.h"

#import "NSSecureCoding-Protocol.h"

@class PKPaymentTransaction;

@interface PDPassPaymentTransactionAuthenticationUserNotification : PDUserNotification <NSSecureCoding>
{
    PKPaymentTransaction *_paymentTransaction;	// 96 = 0x60
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100153c4c
+ (id)notificationIdentifierForTransactionIdentifier:(id)arg1;	// IMP=0x00000001001539e4
- (void).cxx_destruct;	// IMP=0x000000010015445c
@property(readonly, nonatomic) PKPaymentTransaction *paymentTransaction; // @synthesize paymentTransaction=_paymentTransaction;
- (id)notificationContentWithDataSource:(id)arg1;	// IMP=0x0000000100153e90
- (_Bool)isValid;	// IMP=0x0000000100153d90
- (unsigned long long)notificationType;	// IMP=0x0000000100153d88
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100153d00
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100153c54
- (id)initWithPaymentTransaction:(id)arg1 forPassUniqueIdentifier:(id)arg2;	// IMP=0x0000000100153a1c

@end

