//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;
@protocol OS_xpc_object;

@interface CSAudioRecordContext : NSObject <NSCopying>
{
    _Bool _alwaysUseRemoteBuiltInMic;	// 8 = 0x8
    long long _type;	// 16 = 0x10
    NSString *_deviceId;	// 24 = 0x18
}

+ (id)recordTypeString:(long long)arg1;	// IMP=0x000000010001a89c
+ (id)defaultContext;	// IMP=0x0000000100019fe0
+ (id)contextForHomeButton;	// IMP=0x0000000100019fb0
+ (id)contextForServerInvoke;	// IMP=0x0000000100019f80
+ (id)contextForVoiceTriggerTraining;	// IMP=0x0000000100019f24
+ (id)contextForBTLEWithDeviceId:(id)arg1;	// IMP=0x0000000100019ecc
+ (id)contextForJarvisWithDeviceId:(id)arg1;	// IMP=0x0000000100019e74
+ (id)contextForBuiltInVoiceTrigger;	// IMP=0x0000000100019e44
+ (id)contextForOpportuneSpeakerListener;	// IMP=0x0000000100019e14
+ (id)contextForRemoraVoiceTriggerWithDeviceId:(id)arg1;	// IMP=0x0000000100019db0
+ (id)contextForHearstVoiceTriggerWithDeviceId:(id)arg1;	// IMP=0x0000000100019d4c
- (void).cxx_destruct;	// IMP=0x000000010001ab54
@property(nonatomic) _Bool alwaysUseRemoteBuiltInMic; // @synthesize alwaysUseRemoteBuiltInMic=_alwaysUseRemoteBuiltInMic;
@property(retain, nonatomic) NSString *deviceId; // @synthesize deviceId=_deviceId;
@property(nonatomic) long long type; // @synthesize type=_type;
- (id)description;	// IMP=0x000000010001aa7c
@property(readonly, nonatomic) NSObject<OS_xpc_object> *xpcObject;
- (long long)avvcActivationMode:(long long)arg1;	// IMP=0x000000010001a874
- (long long)recordTypeFromAVVCActivationMode:(long long)arg1;	// IMP=0x000000010001a6e4
- (_Bool)isDictation;	// IMP=0x000000010001a6d4
- (_Bool)isStarkTriggered;	// IMP=0x000000010001a6c4
- (_Bool)isServerInvoked;	// IMP=0x000000010001a6b4
- (_Bool)isHomePressed;	// IMP=0x000000010001a6a4
- (_Bool)isJarvisVoiceTriggered;	// IMP=0x000000010001a694
- (_Bool)isRTSTriggered;	// IMP=0x000000010001a684
- (_Bool)isHearstDoubleTapTriggered;	// IMP=0x000000010001a674
- (_Bool)isHearstVoiceTriggered;	// IMP=0x000000010001a664
- (_Bool)isTriggeredFromHearst;	// IMP=0x000000010001a61c
- (_Bool)isBuiltInVoiceTriggered;	// IMP=0x000000010001a60c
- (_Bool)isVoiceTriggered;	// IMP=0x000000010001a5b0
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010001a504
- (id)_createAVVCContextWithType:(long long)arg1 deviceId:(id)arg2;	// IMP=0x000000010001a41c
- (id)avvcContext;	// IMP=0x000000010001a40c
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010001a378
- (id)initWithRecordType:(long long)arg1 deviceId:(id)arg2;	// IMP=0x000000010001a2e8
- (id)initWithAVVCContext:(id)arg1;	// IMP=0x000000010001a180
- (id)initWithXPCObject:(id)arg1;	// IMP=0x000000010001a0b4
- (_Bool)isPluginContext;	// IMP=0x000000010006deb4
- (id)avvcContextSettings;	// IMP=0x0000000100084f64

@end

