//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MAAsset, NSDictionary, NSString;

@interface MSUUpdateBrainLocator : NSObject
{
    NSDictionary *_updateAssetAttributes;	// 8 = 0x8
    MAAsset *_brainAsset;	// 16 = 0x10
}

+ (id)newBrainAssetName:(id)arg1;	// IMP=0x0000000100009e54
+ (id)stateSummary:(id)arg1;	// IMP=0x0000000100009df0
+ (id)locatorsDictionary;	// IMP=0x00000001000054b4
+ (id)locatorsStateQueue;	// IMP=0x000000010000544c
+ (id)brainLocatorWithUpdateAttributes:(id)arg1;	// IMP=0x0000000100005204
@property(readonly, nonatomic) MAAsset *brainAsset; // @synthesize brainAsset=_brainAsset;
@property(retain, nonatomic) NSDictionary *updateAssetAttributes; // @synthesize updateAssetAttributes=_updateAssetAttributes;
- (void)_clientRequestComplete:(id)arg1 nameForNumber:(id)arg2 valueForNumber:(long long)arg3 withError:(id)arg4 handler:(CDUnknownBlockType)arg5;	// IMP=0x0000000100009c18
- (void)_clientRequestComplete:(id)arg1 reportingState:(id)arg2 withError:(id)arg3 moreToCome:(_Bool)arg4 handler:(CDUnknownBlockType)arg5;	// IMP=0x0000000100009a14
- (void)_clientRequestComplete:(id)arg1 withError:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000098b0
- (void)_clientRequestComplete:(id)arg1 withError:(id)arg2 wasSuccessful:(_Bool)arg3;	// IMP=0x0000000100009780
- (void)_clientRequestComplete:(id)arg1 withError:(id)arg2;	// IMP=0x000000010000969c
- (void)_clientRequestBegin:(id)arg1;	// IMP=0x00000001000095e8
- (_Bool)cancelAllDownloadsExcept:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100009104
- (void)requiredDiskSpace:(CDUnknownBlockType)arg1;	// IMP=0x0000000100008e84
- (_Bool)_purgeInstalledUpdateBrains:(id *)arg1;	// IMP=0x00000001000089e8
- (_Bool)purgeInstalledUpdateBrains:(id *)arg1;	// IMP=0x0000000100008954
- (id)newBrainQuery;	// IMP=0x0000000100008928
- (id)newBrainAsset:(id *)arg1;	// IMP=0x00000001000082dc
- (void)downloadBrainAsset:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100007ee4
- (void)appendCatalogDownloadOptionsToExistingOptions:(id)arg1;	// IMP=0x0000000100007cd8
- (void)createBestAsset:(CDUnknownBlockType)arg1;	// IMP=0x0000000100007a98
- (_Bool)cancelInstall:(id *)arg1;	// IMP=0x0000000100007770
- (void)adjustDownloadOptions:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100007690
- (void)adjustMADownloadOptions:(id)arg1 callback:(CDUnknownBlockType)arg2;	// IMP=0x00000001000071f8
- (void)installMAUpdateBrain:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100006574
- (void)installUpdateBrain:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100006564
- (id)newBestAssetFromResults:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100005bf8
- (id)newFilteredBrainQuery;	// IMP=0x00000001000059bc
- (char *)copyUpdateBrainPath:(id *)arg1;	// IMP=0x00000001000055e0
@property(readonly, nonatomic) NSString *deviceType;
- (void)dealloc;	// IMP=0x0000000100005570
- (id)initWithUpdateAssetAttributes:(id)arg1;	// IMP=0x0000000100005518

@end

