/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, April 14, 2021 at 2:27:21 PM Mountain Standard Time
                       * Operating System: Version 14.4 (Build 18K802)
                       * Image Source: /usr/lib/swift/libswiftCore.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@protocol Swift._NSSetCore <Swift._NSCopying,Swift._NSFastEnumeration>
@property (readonly,nonatomic) long long count; 
@required
-(id)copyWithZone:(void*)arg1;
-(long long)count;
-(id)objectEnumerator;
-(long long)countByEnumeratingWithState:(SCD_Struct_Sw0*)arg1 objects:(id*)arg2 count:(long long)arg3;
-(id)member:(id)arg1;
-(id)initWithObjects:(const id*)arg1 count:(long long)arg2;

@end

