//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "INDaemon.h"

#import "FAFamilyNotificationDelegate-Protocol.h"

@class INAccountEventPushHandler, NSDictionary, NSString;

@interface INDaemon_iOS : INDaemon <FAFamilyNotificationDelegate>
{
    NSDictionary *_familyPushNotificationHandlersByEventType;	// 8 = 0x8
    NSDictionary *_accountPushNotificationHandlersByEventType;	// 16 = 0x10
    INAccountEventPushHandler *_accountDefaultEventPushNotificationHandler;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010000dc14
- (void)renewCredentialsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010000dba4
- (void)commonHeadersForRequest:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x000000010000db38
- (void)remoteFreshmintFlowCompletedWithSuccess:(_Bool)arg1 error:(id)arg2;	// IMP=0x000000010000db34
- (void)presentHiddenFreshmintWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010000d9fc
- (void)notifyDeviceStorageLevel:(long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010000d998
- (void)iCloudServerOfferForAccountWithID:(id)arg1 options:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010000d890
- (void)updateOfferForAccountWithID:(id)arg1 offerId:(id)arg2 buttonId:(id)arg3 info:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x000000010000d804
- (void)didDismissFamilyNotification:(id)arg1;	// IMP=0x000000010000d7a4
- (void)didClearFamilyNotification:(id)arg1;	// IMP=0x000000010000d744
- (void)didActivateFamilyNotification:(id)arg1;	// IMP=0x000000010000d464
- (void)handleICloudQuotaPush:(id)arg1;	// IMP=0x000000010000d41c
- (id)pushTopics;	// IMP=0x000000010000d370
- (id)familyPushNotificationHandlerForEventType:(id)arg1;	// IMP=0x000000010000d358
- (id)accountPushNotificationHandlerForEventType:(id)arg1;	// IMP=0x000000010000d2bc
- (void)_loadPushNotificationHandlers;	// IMP=0x000000010000cec0
- (void)handlePushUnregistrationWithAccount:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010000ce20
- (void)handlePushRegistrationWithAccount:(id)arg1;	// IMP=0x000000010000ce1c
- (void)_handleDeviceDidPairEvent;	// IMP=0x000000010000ca88
- (void)_handleDeviceNameChangeEvent;	// IMP=0x000000010000c6f4
- (void)_configureXPCEventStreamHandler;	// IMP=0x000000010000c488
- (void)dealloc;	// IMP=0x000000010000c454
- (void)start;	// IMP=0x000000010000c3c4
- (id)init;	// IMP=0x000000010000c338

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

