//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCATPointPicker.h"

@interface SCATGridPointPicker : SCATPointPicker
{
}

- (_Bool)handleInputAction:(long long)arg1 withElement:(id)arg2;	// IMP=0x00000001000ad980
- (void)scannerWillMakeManagerInactive:(id)arg1;	// IMP=0x00000001000ad8ec
- (void)scannerWillMakeManagerActive:(id)arg1;	// IMP=0x00000001000ad858
- (void)driver:(id)arg1 didFocusOnContext:(id)arg2 oldContext:(id)arg3;	// IMP=0x00000001000ad77c
- (id)elementBefore:(id)arg1 didWrap:(_Bool *)arg2 options:(int *)arg3;	// IMP=0x00000001000ad6e4
- (id)elementAfter:(id)arg1 didWrap:(_Bool *)arg2 options:(int *)arg3;	// IMP=0x00000001000ad64c
- (id)lastElementWithOptions:(int *)arg1;	// IMP=0x00000001000ad5f0
- (id)firstElementWithOptions:(int *)arg1;	// IMP=0x00000001000ad594
- (id)_gridViewController;	// IMP=0x00000001000ad588
- (long long)pickerType;	// IMP=0x00000001000ad580
- (id)_initWithMenu:(id)arg1;	// IMP=0x00000001000ad4d4

@end

