//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <VoiceOverServices/VOSCommandManager.h>

@interface VOSCommandManager (VOSCommandSupport)
- (id)eventForKeyChord:(id)arg1;	// IMP=0x0000000100016efc
- (id)eventForKeyChord:(id)arg1 resolver:(id)arg2;	// IMP=0x0000000100016e94
- (id)eventForKeyChord:(id)arg1 resolver:(id)arg2 info:(id)arg3;	// IMP=0x0000000100016cb0
- (id)eventForTouchGesture:(id)arg1 resolver:(id)arg2;	// IMP=0x0000000100016c48
- (id)eventForTouchGesture:(id)arg1 resolver:(id)arg2 info:(id)arg3;	// IMP=0x0000000100016a2c
@end

