//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SQLiteMemoryEntity.h"

@interface AppPackage : SQLiteMemoryEntity
{
}

+ (id)_valueDictionaryWithSystemAppLookupItem:(id)arg1;	// IMP=0x00000001001fd468
+ (id)_valueDictionaryWithStoreAsset:(id)arg1;	// IMP=0x00000001001fd028
+ (id)_legacy_valueDictionaryWithAsset:(id)arg1;	// IMP=0x00000001002683a4
+ (id)legacy_packageForAsset:(id)arg1;	// IMP=0x0000000100268314
- (id)initWithSystemAppLookupItem:(id)arg1;	// IMP=0x00000001001fcf80
- (id)initWithStoreAsset:(id)arg1;	// IMP=0x00000001001fced8

@end

