//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "CacheDeletePurgeableProvider-Protocol.h"

@class AKAuthorizationController, NSArray, NSString;
@protocol OS_dispatch_queue;

@interface AppPurgeCoordinator : NSObject <CacheDeletePurgeableProvider>
{
    AKAuthorizationController *_authorizationController;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 16 = 0x10
    NSArray *_fullBlackList;	// 24 = 0x18
    NSArray *_fullPluginBlacklist;	// 32 = 0x20
    double _gracePeriodSeconds;	// 40 = 0x28
    double _lastDuetSync;	// 48 = 0x30
    NSArray *_watchAppList;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00000001000b5e68
- (id)_watchAppBundlesWithLogKey:(id)arg1;	// IMP=0x00000001000b5e4c
- (void)_syncDuetEventsWithLogKey:(id)arg1;	// IMP=0x00000001000b587c
- (void)_syncDuetEventsIfNeededWithLogKey:(id)arg1;	// IMP=0x00000001000b560c
- (id)_sortDescriptors;	// IMP=0x00000001000b5528
- (id)_purgebaleForUrgency:(long long)arg1 logKey:(id)arg2 outError:(id *)arg3;	// IMP=0x00000001000b52bc
- (id)_purgeApps:(id)arg1 desiredPurgeSize:(long long)arg2 purgedSize:(unsigned long long *)arg3 offloadOnly:(_Bool)arg4 logKey:(id)arg5;	// IMP=0x00000001000b49fc
- (id)_processApp:(id)arg1 context:(id)arg2;	// IMP=0x00000001000b3ca8
- (id)_launchEventsFromDate:(id)arg1 toDate:(id)arg2 prediate:(id)arg3;	// IMP=0x00000001000b38f8
- (id)_lastModifiedForRecord:(id)arg1 logKey:(id)arg2;	// IMP=0x00000001000b3684
- (id)_lastModifiedForBundle:(id)arg1;	// IMP=0x00000001000b332c
- (id)_launchEventsFromDuetFromDate:(id)arg1 endDate:(id)arg2 logKey:(id)arg3;	// IMP=0x00000001000b2bd4
- (_Bool)_isOffloadCandiate:(id)arg1;	// IMP=0x00000001000b2a44
- (_Bool)_isBeyondGracePeriodWithLogKey:(id)arg1;	// IMP=0x00000001000b2a3c
- (id)_filterPurgeableApps:(id)arg1 performAvailabilityCheck:(_Bool)arg2 additionalApps:(id)arg3 desiredPurgeSize:(long long)arg4 client:(id)arg5 logKey:(id)arg6;	// IMP=0x00000001000b1684
- (id)_demoteableAppsWithInterval:(long long)arg1 context:(id)arg2 outError:(id *)arg3;	// IMP=0x00000001000b11e4
- (id)_cutoffDateForUrgency:(long long)arg1;	// IMP=0x00000001000b11ac
- (id)_bundleIDsForEntitlements:(id)arg1 logKey:(id)arg2;	// IMP=0x00000001000b0d20
- (void)_appsUsedBasedOnLastModifiedForWindow:(long long)arg1 apps:(id)arg2 cutoffDate:(id)arg3;	// IMP=0x00000001000b06e0
- (_Bool)_appsBasedOnWindow:(long long)arg1 apps:(id)arg2 cutoffDate:(id)arg3 logKey:(id)arg4 ourError:(id *)arg5;	// IMP=0x00000001000b06d8
- (id)_appsUsedWindow:(long long)arg1 logKey:(id)arg2 ourError:(id *)arg3;	// IMP=0x00000001000b063c
- (id)_availableInStore:(id)arg1 logKey:(id)arg2 error:(id *)arg3;	// IMP=0x00000001000b0304
- (_Bool)_authorizedBySignInWithApple:(id)arg1 logKey:(id)arg2;	// IMP=0x00000001000affa0
- (id)_appPluginBlacklist;	// IMP=0x00000001000afe38
- (id)_appBlacklist:(id)arg1;	// IMP=0x00000001000af960
- (long long)purgeForVolume:(id)arg1 urgency:(long long)arg2 desiredPurge:(id)arg3;	// IMP=0x00000001000af638
- (long long)purgeableForVolume:(id)arg1 urgency:(long long)arg2 override:(_Bool)arg3;	// IMP=0x00000001000af1fc
- (long long)purgeableForVolume:(id)arg1 urgency:(long long)arg2;	// IMP=0x00000001000af1ec
- (void)cacheInvalidated;	// IMP=0x00000001000aef64
- (id)allPurgeablesForVolume:(id)arg1;	// IMP=0x00000001000aec34
- (void)syncDuetEvents;	// IMP=0x00000001000aebe0
- (id)purgeAppsForVolume:(id)arg1 urgency:(long long)arg2 desiredPurge:(id)arg3 performAvailabilityCheck:(_Bool)arg4 additionalApps:(id)arg5 offloadOnly:(_Bool)arg6 logKey:(id)arg7 client:(id)arg8;	// IMP=0x00000001000ae964
- (id)purgeableAppsForVolume:(id)arg1 urgency:(long long)arg2 performAvailabilityCheck:(_Bool)arg3 logKey:(id)arg4;	// IMP=0x00000001000ae53c
- (id)purgeableAppsForVolume:(id)arg1 urgency:(long long)arg2 performAvailabilityCheck:(_Bool)arg3;	// IMP=0x00000001000ae494
- (id)launchEventsFromDate:(id)arg1 toDate:(id)arg2;	// IMP=0x00000001000ae42c
- (id)installedApps;	// IMP=0x00000001000ae30c
- (id)diagnosticDescription:(_Bool)arg1;	// IMP=0x00000001000adf68
- (void)clearLaunchHistoryForBundleIDs:(id)arg1;	// IMP=0x00000001000adbd4
- (void)_registerBagKeys;	// IMP=0x00000001000adaf0
- (id)init;	// IMP=0x00000001000ad98c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

