//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SQLiteEntity.h"

@interface InAppPurchaseIntentEntity : SQLiteEntity
{
}

+ (Class)memoryEntityClass;	// IMP=0x00000001002914d4
+ (id)defaultProperties;	// IMP=0x0000000100291438
+ (id)databaseTable;	// IMP=0x000000010029142c

@end

