//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "Promise.h"

@protocol TaskScheduler;

@interface LazyPromise : Promise
{
    CDUnknownBlockType _executor;	// 40 = 0x28
    id <TaskScheduler> _scheduler;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0000000100009008
- (id)joinWithPromise:(id)arg1;	// IMP=0x0000000100008bd0
- (void)thenPerform:(CDUnknownBlockType)arg1 orCatchError:(CDUnknownBlockType)arg2 onScheduler:(id)arg3;	// IMP=0x0000000100008a90
- (id)initOnScheduler:(id)arg1 withExecutor:(CDUnknownBlockType)arg2;	// IMP=0x00000001000089d0

@end

