//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MigratorTask.h"

@interface MigratorValidateAppleIDsTask : MigratorTask
{
}

- (void)main;	// IMP=0x000000010014af54
- (id)migratorType;	// IMP=0x000000010014af44
- (id)copyConfiguration;	// IMP=0x000000010014af14
- (id)initWithConfiguration:(id)arg1;	// IMP=0x000000010014aee0

@end

