//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PushMessageConsumer-Protocol.h"

@class NSMutableArray, NSString, PurchaseHistoryDatabaseStore;
@protocol OS_dispatch_queue, PurchaseHistoryBagContract;

@interface PurchaseHistoryManager : NSObject <PushMessageConsumer>
{
    id <PurchaseHistoryBagContract> _bagContract;	// 8 = 0x8
    _Bool _commandRunning;	// 16 = 0x10
    NSMutableArray *_commandStack;	// 24 = 0x18
    PurchaseHistoryDatabaseStore *_databaseStore;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 40 = 0x28
}

+ (id)sharedInstance;	// IMP=0x00000001001bddd0
- (void).cxx_destruct;	// IMP=0x00000001001c09e4
- (void)_performNextQualifyingUpdateRequest;	// IMP=0x00000001001c0414
- (void)_queueCommand:(id)arg1;	// IMP=0x00000001001c0398
- (void)_updateForAccountID:(id)arg1 withContext:(unsigned long long)arg2 token:(id)arg3 replyHandler:(CDUnknownBlockType)arg4;	// IMP=0x00000001001c022c
- (void)_handleAccountChangedNotification;	// IMP=0x00000001001bfe34
- (id)_getHideShowRequestContextToShowAllForAccount:(id)arg1 withError:(id *)arg2;	// IMP=0x00000001001bfa74
- (id)_getHideShowRequestContextToHideItem:(long long)arg1 forAccount:(id)arg2 withError:(id *)arg3;	// IMP=0x00000001001bf644
- (void)_beginObservingAccountChangeNotification;	// IMP=0x00000001001bf45c
- (void)pushService:(id)arg1 didReceiveMessage:(id)arg2;	// IMP=0x00000001001beee0
- (void)updateWithContext:(unsigned long long)arg1 withToken:(id)arg2 withReplyHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001001bec7c
- (void)updateForAccountID:(long long)arg1 withContext:(unsigned long long)arg2 withToken:(id)arg3 withReplyHandler:(CDUnknownBlockType)arg4;	// IMP=0x00000001001beb38
- (void)updateForAccountID:(id)arg1 expectedItemID:(id)arg2 withReplyHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001001be860
- (void)showAllWithToken:(id)arg1 withReplyHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001001be658
- (void)setHidden:(_Bool)arg1 forStoreItemID:(long long)arg2 withToken:(id)arg3 withReplyHandler:(CDUnknownBlockType)arg4;	// IMP=0x00000001001be448
- (void)executeQuery:(id)arg1 withReplyHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001001be018
- (id)init;	// IMP=0x00000001001bde6c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

