//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface XDCPingMessage : PBCodable <NSCopying>
{
    NSString *_uuid;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100209fac
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void)mergeFrom:(id)arg1;	// IMP=0x0000000100209f68
- (unsigned long long)hash;	// IMP=0x0000000100209f50
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100209eb0
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100209e34
- (void)writeTo:(id)arg1;	// IMP=0x0000000100209e14
- (_Bool)readFrom:(id)arg1;	// IMP=0x0000000100209e0c
- (id)dictionaryRepresentation;	// IMP=0x0000000100209c10
- (id)description;	// IMP=0x0000000100209b5c
@property(readonly, nonatomic) _Bool hasUuid;

@end

