//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class BLOperationQueue, NSMutableArray;
@protocol OS_dispatch_queue, OS_dispatch_source;

__attribute__((visibility("hidden")))
@interface BLMLImporter : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 8 = 0x8
    BLOperationQueue *_operationQueue;	// 16 = 0x10
    NSMutableArray *_scheduledItems;	// 24 = 0x18
    NSObject<OS_dispatch_source> *_scheduledItemTimer;	// 32 = 0x20
}

+ (id)deviceMLImporter;	// IMP=0x0000000100009c74
- (void).cxx_destruct;	// IMP=0x000000010000c2dc
- (void)_setDownloadPropertiesForTrack:(id)arg1 usingLibraryItem:(id)arg2;	// IMP=0x000000010000c1a0
- (_Bool)_removeDownloadWithIdentifier:(long long)arg1 canceled:(_Bool)arg2 inLibrary:(id)arg3;	// IMP=0x000000010000bcc8
- (void)_dispatchAsync:(CDUnknownBlockType)arg1;	// IMP=0x000000010000bb98
- (void)_commitScheduledLibraryItems;	// IMP=0x000000010000ba50
- (_Bool)_addLibraryItems:(id)arg1 toMusicLibrary:(id)arg2 itemPids:(long long *)arg3 error:(id *)arg4;	// IMP=0x000000010000a9d8
- (void)setAppleIdentifier:(id)arg1 forAccountIdentifier:(unsigned long long)arg2;	// IMP=0x000000010000a8c8
- (void)scheduleLibraryItems:(id)arg1;	// IMP=0x000000010000a5a4
- (void)scheduleLibraryItem:(id)arg1;	// IMP=0x000000010000a524
- (void)removeDownloadWithIdentifier:(long long)arg1 canceled:(_Bool)arg2;	// IMP=0x000000010000a3fc
- (void)removeDownloadsWithIdentifiers:(id)arg1 canceled:(_Bool)arg2;	// IMP=0x000000010000a130
- (void)deleteAllOTATracks;	// IMP=0x0000000100009f18
- (void)commitScheduledLibraryItems;	// IMP=0x0000000100009eb0
- (_Bool)addLibraryItems:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100009e14
- (long long)addLibraryItem:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100009d14
- (void)dealloc;	// IMP=0x0000000100009c14
- (id)init;	// IMP=0x0000000100009b50

@end

