//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSArray, NSDictionary;

@interface ASCViewMetrics : NSObject <NSCopying, NSSecureCoding>
{
    NSArray *_instructions;	// 8 = 0x8
    NSDictionary *_pageFields;	// 16 = 0x10
}

+ (_Bool)supportsSecureCoding;	// IMP=0x000000010001860c
- (void).cxx_destruct;	// IMP=0x0000000100018d7c
@property(readonly, copy, nonatomic) NSDictionary *pageFields; // @synthesize pageFields=_pageFields;
@property(readonly, copy, nonatomic) NSArray *instructions; // @synthesize instructions=_instructions;
- (id)dataForInvocationPoint:(id)arg1;	// IMP=0x0000000100018b7c
- (id)description;	// IMP=0x0000000100018a90
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100018900
- (unsigned long long)hash;	// IMP=0x000000010001883c
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100018838
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100018780
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100018614
- (id)initWithInstructions:(id)arg1 pageFields:(id)arg2;	// IMP=0x000000010001854c

@end

