//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDS/IDSService.h>

@interface IDSService (MRAdditions)
+ (id)mediaRemoteServiceName;	// IMP=0x00000001000023d4
+ (id)sharedIDSService;	// IMP=0x00000001000022e0
+ (id)mediaRemoteServiceName;	// IMP=0x0000000100011618
+ (id)sharedIDSService;	// IMP=0x000000010001152c
+ (id)mediaRemoteServiceName;	// IMP=0x000000010003d3e4
+ (id)sharedIDSService;	// IMP=0x000000010003d2f8
@end

