//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MRDExternalDeviceHomeServerRecentlyPlayedEntry, MRDProximityController, NSMutableArray, NSString, NSUserDefaults;

@interface MRDExternalDeviceHomeServer : NSObject
{
    _Bool _sendingPlaybackStateToCompanion;	// 8 = 0x8
    MRDExternalDeviceHomeServerRecentlyPlayedEntry *_lastSentEntry;	// 16 = 0x10
    NSMutableArray *_entries;	// 24 = 0x18
    NSUserDefaults *_userDefaults;	// 32 = 0x20
    MRDProximityController *_proximityController;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0000000100036480
@property(retain, nonatomic) MRDProximityController *proximityController; // @synthesize proximityController=_proximityController;
@property(nonatomic) _Bool sendingPlaybackStateToCompanion; // @synthesize sendingPlaybackStateToCompanion=_sendingPlaybackStateToCompanion;
@property(retain, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
@property(retain, nonatomic) NSMutableArray *entries; // @synthesize entries=_entries;
@property(retain, nonatomic) MRDExternalDeviceHomeServerRecentlyPlayedEntry *lastSentEntry; // @synthesize lastSentEntry=_lastSentEntry;
- (id)decodeEntries;	// IMP=0x0000000100036188
- (id)encodeEntries;	// IMP=0x0000000100035fd4
- (void)_addEntry:(id)arg1;	// IMP=0x0000000100035c5c
- (_Bool)_shouldSendCompanionLinkMessage;	// IMP=0x0000000100035c38
- (void)_maybeSendPlaybackStateMessageToCompanion;	// IMP=0x0000000100035574
- (void)_handleDidSendSetQueueForHomeUserNotification:(id)arg1;	// IMP=0x0000000100035428
- (void)_handleDidAddPersonalDeviceNotification:(id)arg1;	// IMP=0x0000000100035380
- (void)_maybeMostRecentlyPlayedDeviceChanged:(id)arg1;	// IMP=0x00000001000351d8
- (void)_handleLocalPlaybackBeganNotification:(id)arg1;	// IMP=0x0000000100035034
- (void)_registerNotifications;	// IMP=0x0000000100034db0
- (void)_registerCompanionLinkHandlers;	// IMP=0x0000000100034568
@property(readonly, nonatomic) NSString *mostRecentDeviceUID;
- (id)initWithProximityController:(id)arg1;	// IMP=0x00000001000343c4

@end

