//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MRDAVRoutingDataSource.h"

@class MRDOutputDeviceRoutingDataSource;

@interface MRDMediaServerAVRoutingDataSource : MRDAVRoutingDataSource
{
    MRDOutputDeviceRoutingDataSource *_oddsShimDataSource;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010004d680
- (id)_oddsShimDataSource;	// IMP=0x000000010004d634
- (void)_notifyDelegateRoutesDidChange;	// IMP=0x000000010004d5d8
- (id)_descriptionForDiscoveryMode:(unsigned int)arg1;	// IMP=0x000000010004d5c0
- (void)_unregisterAVSystemControllerNotifications;	// IMP=0x000000010004d43c
- (void)_registerAVSystemControllerNotifications;	// IMP=0x000000010004d244
- (id)_mediaServerController;	// IMP=0x000000010004d220
- (void)_avSessionMediaServicesResetNotification:(id)arg1;	// IMP=0x000000010004d0f0
- (void)_portStatusDidChangeNotification:(id)arg1;	// IMP=0x000000010004ccd4
- (void)_externalScreenDidChangeNotification:(id)arg1;	// IMP=0x000000010004cc78
- (void)_postCurrentRouteHasVolumeControlDidChangeNotification:(_Bool)arg1;	// IMP=0x000000010004cb50
- (void)_currentRouteHasVolumeControlDidChangeNotification:(id)arg1;	// IMP=0x000000010004ca98
- (void)_pickableRoutesDidChangeNotification:(id)arg1;	// IMP=0x000000010004ca8c
- (_Bool)unpickAirPlayRoutes;	// IMP=0x000000010004c988
- (void)userCancelledPickingRoute:(id)arg1;	// IMP=0x000000010004c8e8
- (_Bool)resetPickedSystemRouteForSource:(unsigned int)arg1;	// IMP=0x000000010004c8dc
- (_Bool)resetPickedRouteForSource:(unsigned int)arg1;	// IMP=0x000000010004c6e8
- (_Bool)setPickedSystemRoute:(id)arg1 withPassword:(id)arg2 forSource:(unsigned int)arg3;	// IMP=0x000000010004c530
- (_Bool)setPickedRoute:(id)arg1 withPassword:(id)arg2 forSource:(unsigned int)arg3;	// IMP=0x000000010004c4cc
- (_Bool)setPickedRoute:(id)arg1 withPassword:(id)arg2;	// IMP=0x000000010004c46c
- (id)pickableRoutesForCategory:(id)arg1 source:(unsigned int)arg2;	// IMP=0x000000010004c114
- (id)pickableRoutesForCategory:(id)arg1;	// IMP=0x000000010004c104
- (id)pickedRoutesForCategory:(id)arg1 source:(unsigned int)arg2;	// IMP=0x000000010004bf80
- (id)pickedRouteForCategory:(id)arg1 source:(unsigned int)arg2;	// IMP=0x000000010004bf2c
- (id)pickedRouteForCategory:(id)arg1;	// IMP=0x000000010004bf1c
- (id)pickedRoutes;	// IMP=0x000000010004bf00
- (id)pickedRoute;	// IMP=0x000000010004beac
- (_Bool)currentRouteSupportsVolumeControl;	// IMP=0x000000010004be60
- (unsigned int)externalScreenType;	// IMP=0x000000010004bd38
- (void)setDiscoveryMode:(unsigned int)arg1;	// IMP=0x000000010004bc7c
- (void)dealloc;	// IMP=0x000000010004bbf8
- (id)init;	// IMP=0x000000010004bba0

@end

