//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "MRDAirPlayRemoteControlServiceDelegate-Protocol.h"
#import "MRDBonjourRemoteControlServiceDelegate-Protocol.h"
#import "MRDIDSRemoteControlServiceDelegate-Protocol.h"
#import "MRDRapportRemoteControlServiceDelegate-Protocol.h"

@class MRDAirPlayRemoteControlService, MRDBonjourRemoteControlService, MRDIDSRemoteControlService, MRDRapportRemoteControlService, NSString;
@protocol MRDRemoteControlServiceDelegate, OS_dispatch_queue;

@interface MRDRemoteControlService : NSObject <MRDAirPlayRemoteControlServiceDelegate, MRDBonjourRemoteControlServiceDelegate, MRDRapportRemoteControlServiceDelegate, MRDIDSRemoteControlServiceDelegate>
{
    id <MRDRemoteControlServiceDelegate> _delegate;	// 8 = 0x8
    MRDBonjourRemoteControlService *_genericNetworkService;	// 16 = 0x10
    MRDBonjourRemoteControlService *_televisionNetworkService;	// 24 = 0x18
    MRDAirPlayRemoteControlService *_airPlayService;	// 32 = 0x20
    MRDRapportRemoteControlService *_rapportService;	// 40 = 0x28
    MRDIDSRemoteControlService *_idsService;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_workerQueue;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0000000100095ccc
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workerQueue; // @synthesize workerQueue=_workerQueue;
@property(retain, nonatomic) MRDIDSRemoteControlService *idsService; // @synthesize idsService=_idsService;
@property(retain, nonatomic) MRDRapportRemoteControlService *rapportService; // @synthesize rapportService=_rapportService;
@property(retain, nonatomic) MRDAirPlayRemoteControlService *airPlayService; // @synthesize airPlayService=_airPlayService;
@property(retain, nonatomic) MRDBonjourRemoteControlService *televisionNetworkService; // @synthesize televisionNetworkService=_televisionNetworkService;
@property(retain, nonatomic) MRDBonjourRemoteControlService *genericNetworkService; // @synthesize genericNetworkService=_genericNetworkService;
@property(nonatomic) __weak id <MRDRemoteControlServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_notifyDelegateWithConnection:(id)arg1;	// IMP=0x0000000100095b6c
- (void)_notifyDelegateWithInputSteam:(id)arg1 outputStream:(id)arg2;	// IMP=0x0000000100095ad8
- (void)stop;	// IMP=0x0000000100095a7c
- (void)start;	// IMP=0x0000000100095a20
- (void)idsRemoteControlService:(id)arg1 didAcceptConnection:(id)arg2;	// IMP=0x0000000100095a10
- (void)rapportRemoteControlService:(id)arg1 didAcceptConnectionWithInputStream:(id)arg2 outputStream:(id)arg3;	// IMP=0x00000001000959c0
- (void)airPlayRemoteControlService:(id)arg1 didAcceptConnectionWithInputStream:(id)arg2 outputStream:(id)arg3;	// IMP=0x0000000100095970
- (void)bonjourRemoteControlService:(id)arg1 didAcceptConnectionWithInputStream:(id)arg2 outputStream:(id)arg3;	// IMP=0x0000000100095920
- (id)init;	// IMP=0x00000001000956d4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

