//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCATDriver.h"

@interface SCATManualDriver : SCATDriver
{
}

- (void)_idleTimerDidFire;	// IMP=0x00000001000059e0
- (_Bool)_handleStepPreviousAction;	// IMP=0x00000001000059bc
- (_Bool)_handleStepNextAction;	// IMP=0x000000010000597c
- (int)driverType;	// IMP=0x0000000100005974

@end

