//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCATElementManager.h"

@class AXElement, NSHashTable, NSValue, SCATAggregateElementProvider, SCATModernMenuViewController, SCATPointPicker;
@protocol SCATElement, SCATMenuDelegate;

@interface SCATMenu : SCATElementManager
{
    _Bool _shouldNotResetPointPickerRefinement;	// 8 = 0x8
    _Bool _wasPresentedWithTip;	// 9 = 0x9
    _Bool _transitioning;	// 10 = 0xa
    _Bool _isWaitingToBePresented;	// 11 = 0xb
    _Bool _didActivateElement;	// 12 = 0xc
    _Bool _willScanFirstElementAfterPresentation;	// 13 = 0xd
    SCATModernMenuViewController *_modernMenuViewController;	// 16 = 0x10
    id <SCATMenuDelegate> _delegate;	// 24 = 0x18
    NSHashTable *_menuObservers;	// 32 = 0x20
    AXElement *_textElement;	// 40 = 0x28
    long long _tipObject;	// 48 = 0x30
    NSValue *_screenPoint;	// 56 = 0x38
    SCATPointPicker *_pointPicker;	// 64 = 0x40
    long long _popoverPosition;	// 72 = 0x48
    long long _dockPosition;	// 80 = 0x50
    SCATAggregateElementProvider *_elementProvider;	// 88 = 0x58
    id <SCATElement> _element;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x00000001000776d8
@property(nonatomic) _Bool willScanFirstElementAfterPresentation; // @synthesize willScanFirstElementAfterPresentation=_willScanFirstElementAfterPresentation;
@property(nonatomic) _Bool didActivateElement; // @synthesize didActivateElement=_didActivateElement;
@property(nonatomic) _Bool isWaitingToBePresented; // @synthesize isWaitingToBePresented=_isWaitingToBePresented;
@property(retain, nonatomic) id <SCATElement> element; // @synthesize element=_element;
@property(nonatomic, getter=isTransitioning) _Bool transitioning; // @synthesize transitioning=_transitioning;
@property(retain, nonatomic) SCATAggregateElementProvider *elementProvider; // @synthesize elementProvider=_elementProvider;
@property(nonatomic) long long dockPosition; // @synthesize dockPosition=_dockPosition;
@property(nonatomic) long long popoverPosition; // @synthesize popoverPosition=_popoverPosition;
@property(nonatomic) _Bool wasPresentedWithTip; // @synthesize wasPresentedWithTip=_wasPresentedWithTip;
@property(nonatomic) _Bool shouldNotResetPointPickerRefinement; // @synthesize shouldNotResetPointPickerRefinement=_shouldNotResetPointPickerRefinement;
@property(retain, nonatomic) SCATPointPicker *pointPicker; // @synthesize pointPicker=_pointPicker;
@property(retain, nonatomic) NSValue *screenPoint; // @synthesize screenPoint=_screenPoint;
@property(retain, nonatomic) AXElement *textElement; // @synthesize textElement=_textElement;
@property(retain, nonatomic) NSHashTable *menuObservers; // @synthesize menuObservers=_menuObservers;
@property(nonatomic) __weak id <SCATMenuDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SCATModernMenuViewController *modernMenuViewController; // @synthesize modernMenuViewController=_modernMenuViewController;
- (void)didPressScreenChangingButton;	// IMP=0x0000000100077460
- (_Bool)_viewIsSuitableScannerElement:(id)arg1;	// IMP=0x00000001000773d8
- (void)_prepareMenuForScanning;	// IMP=0x000000010007715c
- (void)_prepareMenuForScanningIfNeeded;	// IMP=0x00000001000770cc
- (id)arrayByShiftingItemsInArray:(id)arg1 leftByNumberOfPositions:(unsigned long long)arg2;	// IMP=0x0000000100076f60
- (void)_flushScannableMenuElements;	// IMP=0x0000000100076f50
- (void)alertDidAppear:(id)arg1;	// IMP=0x0000000100076efc
- (void)appTransitionDidOccur:(id)arg1;	// IMP=0x0000000100076ea8
- (void)orientationDidChange:(id)arg1;	// IMP=0x0000000100076d50
- (void)driver:(id)arg1 willUnfocusFromContext:(id)arg2;	// IMP=0x0000000100076bb4
- (void)driver:(id)arg1 didFocusOnContext:(id)arg2 oldContext:(id)arg3;	// IMP=0x0000000100076820
- (void)driver:(id)arg1 willFocusOnContext:(id)arg2;	// IMP=0x0000000100076714
- (_Bool)allowsDwellScanningToAbortAfterTimeout;	// IMP=0x000000010007670c
- (_Bool)allowsDwellSelection;	// IMP=0x0000000100076698
- (_Bool)shouldKeepScannerAwake;	// IMP=0x0000000100076624
- (_Bool)canBeActiveElementManager;	// IMP=0x0000000100076578
- (id)identifier;	// IMP=0x0000000100076568
- (id)elementBefore:(id)arg1 didWrap:(_Bool *)arg2 options:(int *)arg3;	// IMP=0x0000000100076550
- (id)elementAfter:(id)arg1 didWrap:(_Bool *)arg2 options:(int *)arg3;	// IMP=0x0000000100076538
- (id)_siblingOfElement:(id)arg1 inDirection:(_Bool)arg2 didWrap:(_Bool *)arg3 options:(int *)arg4;	// IMP=0x000000010007625c
- (id)lastElementWithOptions:(int *)arg1;	// IMP=0x00000001000761cc
- (id)firstElementWithOptions:(int *)arg1;	// IMP=0x000000010007613c
- (void)_updateOptionsIfNeeded:(int *)arg1 withResultElement:(id)arg2;	// IMP=0x00000001000760a0
- (void)_notifyMenuObserversWithSelector:(SEL)arg1;	// IMP=0x0000000100075f58
- (void)unregisterAllMenuObservers;	// IMP=0x0000000100075f18
- (void)unregisterMenuObserver:(id)arg1;	// IMP=0x0000000100075eac
- (void)registerMenuObserver:(id)arg1;	// IMP=0x0000000100075e40
- (void)updateMenuVisualsForUpdatedElementVisuals;	// IMP=0x0000000100075df0
- (void)nativeFocusElementDidChange:(id)arg1;	// IMP=0x0000000100075de4
- (id)exitActionElement;	// IMP=0x0000000100075c68
- (void)handleMenuWasActivatedByScanner;	// IMP=0x0000000100075c58
- (void)closeCurrentScanningContext;	// IMP=0x0000000100075c48
- (void)slideDockToPosition:(long long)arg1;	// IMP=0x0000000100075c34
- (void)slidePopoverToPosition:(long long)arg1;	// IMP=0x0000000100075c20
- (void)_slideToPositionWithMode:(unsigned long long)arg1 positionIndex:(long long)arg2;	// IMP=0x0000000100075bd4
- (void)_updateForGeometryChange;	// IMP=0x0000000100075b54
- (void)reloadFromCurrentSheet;	// IMP=0x0000000100075b20
- (void)didTransitionToSheet:(id)arg1;	// IMP=0x0000000100075ae0
- (void)willTransitionToSheet:(id)arg1;	// IMP=0x0000000100075a90
- (void)menuTipObjectDidChange;	// IMP=0x0000000100075a7c
- (_Bool)containsGestureSheet;	// IMP=0x0000000100075a30
- (void)groupingEnabledDidChange;	// IMP=0x0000000100075a24
- (id)_elementWithRestorationInfo:(id)arg1 options:(int *)arg2;	// IMP=0x0000000100075538
- (id)_restorationInfoForElement:(id)arg1;	// IMP=0x0000000100075204
- (void)_updateWithElement:(id)arg1 forceUpdate:(_Bool)arg2;	// IMP=0x00000001000750f0
- (id)updateAfterFetchWithCurrentlyScannedElement:(id)arg1 options:(int *)arg2;	// IMP=0x0000000100074de4
- (_Bool)_isCurrentSheetValidForElement:(id)arg1;	// IMP=0x0000000100074d48
- (void)hideWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100074b78
- (void)_presentWithElement:(id)arg1 pointPicker:(id)arg2 useMenuTip:(_Bool)arg3 sheetToShow:(id)arg4;	// IMP=0x00000001000747d8
- (void)presentAutoscrollMenu;	// IMP=0x0000000100074780
- (void)presentSiriShortcutsMenu;	// IMP=0x000000010007477c
- (void)presentWithRootLevelSheet:(id)arg1 useCurrentElementAndPoint:(_Bool)arg2;	// IMP=0x00000001000746a4
- (void)presentWithPointPicker:(id)arg1;	// IMP=0x0000000100074550
- (void)presentWithElement:(id)arg1;	// IMP=0x0000000100074538
@property(readonly, nonatomic) _Bool shouldHideMenuCursor;
@property(readonly, nonatomic) long long tipObject; // @synthesize tipObject=_tipObject;
- (_Bool)isGroupingEnabled;	// IMP=0x00000001000743e4
@property(readonly, nonatomic) _Bool isVisible;
@property(readonly, nonatomic) AXElement *keyboardApplication;
- (id)initWithDelegate:(id)arg1;	// IMP=0x0000000100073f84

@end

