//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCATModernMenuGesturesSheetBase.h"

@protocol SCATMenuStopContinuousGestureItemViewDelegate;

@interface SCATModernMenuStopContinuousGestureSheet : SCATModernMenuGesturesSheetBase
{
    id <SCATMenuStopContinuousGestureItemViewDelegate> _delegate;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100089c4c
@property(nonatomic) __weak id <SCATMenuStopContinuousGestureItemViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)menuItemWasActivated:(id)arg1;	// IMP=0x0000000100089b48
- (_Bool)shouldAllowDwellSelection;	// IMP=0x0000000100089b40
- (_Bool)shouldKeepScannerAwake;	// IMP=0x0000000100089b38
- (struct CGRect)rectToClear;	// IMP=0x0000000100089abc
- (_Bool)allowsExitAction;	// IMP=0x0000000100089ab4
- (_Bool)allowsBackAction;	// IMP=0x0000000100089aac
- (id)makeMenuItemsIfNeeded;	// IMP=0x00000001000899ec

@end

