//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCATModernMenuItemGesturesFactory : NSObject
{
}

+ (id)_imageNameForNumberOfFingers:(unsigned long long)arg1;	// IMP=0x0000000100086be4
+ (id)_fingerItemStringForNumberOfFingers:(unsigned long long)arg1;	// IMP=0x0000000100086b4c
+ (CDUnknownBlockType)updateBlockForIdentifier:(id)arg1;	// IMP=0x00000001000869a0
+ (id)menuItemWithItemDictionary:(id)arg1 menu:(id)arg2 delegate:(id)arg3;	// IMP=0x0000000100086124
+ (id)itemDetailsForType:(id)arg1 menu:(id)arg2;	// IMP=0x00000001000856f8
+ (id)gestureMenuItemsForItemType:(id)arg1 menu:(id)arg2 delegate:(id)arg3;	// IMP=0x0000000100085538

@end

