//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "EscrowPasswordAuthenticatedRequest.h"

@class EscrowPrerecord;

@interface EscrowEnrollmentRequest : EscrowPasswordAuthenticatedRequest
{
    EscrowPrerecord *_prerecord;	// 216 = 0xd8
}

- (void).cxx_destruct;	// IMP=0x000000010001d118
@property(retain, nonatomic) EscrowPrerecord *prerecord; // @synthesize prerecord=_prerecord;
- (id)bodyDictionary;	// IMP=0x000000010001cc7c
- (id)validateInput;	// IMP=0x000000010001c974
- (id)command;	// IMP=0x000000010001c968
- (Class)responseClass;	// IMP=0x000000010001c95c
- (id)initWithRequest:(id)arg1;	// IMP=0x000000010001c8b8

@end

