//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCNewPayloadHandler.h"

@interface MCNewGlobalHTTPProxyPayloadHandler : MCNewPayloadHandler
{
}

- (_Bool)_sendSystemConfigurationProxyChangeNotification;	// IMP=0x00000001000738fc
- (void)remove;	// IMP=0x00000001000737b0
- (void)unsetAside;	// IMP=0x000000010007377c
- (void)setAside;	// IMP=0x0000000100073748
- (void)_recoverProxyCredential;	// IMP=0x0000000100073560
- (void)_removeProxyCredential;	// IMP=0x00000001000731b8
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x0000000100072e14
- (void)_applyProxyCredential:(id)arg1;	// IMP=0x0000000100072ba0
- (_Bool)_remove;	// IMP=0x0000000100072aec
- (_Bool)_install;	// IMP=0x00000001000724d8
- (_Bool)preflightUserInputResponses:(id)arg1 outError:(id *)arg2;	// IMP=0x0000000100072230
- (id)userInputFields;	// IMP=0x00000001000720a0

@end

