//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSData, PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxyDidReceiveData : PBCodable <NSCopying>
{
    NSData *_receivedData;	// 8 = 0x8
    PDURLSessionProxyTaskMessage *_task;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100030a94
@property(retain, nonatomic) NSData *receivedData; // @synthesize receivedData=_receivedData;
@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void)mergeFrom:(id)arg1;	// IMP=0x00000001000309c8
- (unsigned long long)hash;	// IMP=0x000000010003096c
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100030898
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000307e8
- (void)copyTo:(id)arg1;	// IMP=0x000000010003077c
- (void)writeTo:(id)arg1;	// IMP=0x0000000100030718
- (_Bool)readFrom:(id)arg1;	// IMP=0x0000000100030504
- (id)dictionaryRepresentation;	// IMP=0x000000010003044c
- (id)description;	// IMP=0x0000000100030398
@property(readonly, nonatomic) _Bool hasReceivedData;
@property(readonly, nonatomic) _Bool hasTask;

@end

