//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface AudioDeviceManager : NSObject
{
    struct _xpc_connection_s *_listener;	// 8 = 0x8
    struct dispatch_queue_s *_queue;	// 16 = 0x10
    struct vector<BT::XpcAudioPluginClient *, std::__1::allocator<BT::XpcAudioPluginClient *>> xpcClients;	// 24 = 0x18
    struct map<std::__1::basic_string<char>, BT::XpcAudioPluginDevice *, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, BT::XpcAudioPluginDevice *>>> audioDevices;	// 48 = 0x30
    struct Mutex {
        struct _opaque_pthread_mutex_t {
            long long __sig;
            unsigned char __opaque[56];
        } fMutex;
    } audioDeviceMapMutex;	// 72 = 0x48
    struct AudioSkywalkProvider *_audioSkywalkProvider;	// 136 = 0x88
}

+ (id)sharedManager;	// IMP=0x0000000100209d34
- (id).cxx_construct;	// IMP=0x000000010020ac70
- (void).cxx_destruct;	// IMP=0x000000010020ac28
- (struct dispatch_queue_s *)getXpcQueue;	// IMP=0x000000010020ac20
- (void)removeXpcClient:(struct XpcAudioPluginClient *)arg1;	// IMP=0x000000010020aaa0
- (struct AudioSkywalkProvider *)getAudioSkywalkProvider;	// IMP=0x000000010020a98c
- (struct XpcAudioPluginDevice *)getDeviceForUID:(basic_string_3f66b750)arg1;	// IMP=0x000000010020a87c
- (void)forwardEvent:(void *)arg1 forUid:(basic_string_3f66b750)arg2;	// IMP=0x000000010020a794
- (void)republishAllAudioDevices;	// IMP=0x000000010020a65c
- (void)sendMsg:(int)arg1 withArgs:(void *)arg2 uid:(basic_string_3f66b750)arg3;	// IMP=0x000000010020a34c
- (void)publishAndRegisterDevice:(int)arg1 withArgs:(void *)arg2 uid:(basic_string_3f66b750)arg3 device:(struct XpcAudioPluginDevice *)arg4;	// IMP=0x000000010020a164
- (void)handleListenerEvent:(void *)arg1;	// IMP=0x0000000100209f18
- (void)configureXPCListener;	// IMP=0x0000000100209e7c
- (void)dealloc;	// IMP=0x0000000100209e44
- (id)init;	// IMP=0x0000000100209da0

@end

