//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC8AppStore15ProgressBarView : UIView
{
    MISSING_TYPE *percentage;	// 8 = 0x8
    MISSING_TYPE *fillColor;	// 16 = 0x10
    MISSING_TYPE *trackColor;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0000000100011940
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100011978
@property(nonatomic, readonly) double accessibilityPercentage;
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000118b0
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x0000000100011764
@property(nonatomic) struct CGRect frame;
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000112b0
- (id)init;	// IMP=0x0000000100011290

@end

