//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC8AppStore29ScrollViewDelegateCoordinator : NSObject
{
    MISSING_TYPE *compoundScrollCoordinator;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010016046c
- (id)init;	// IMP=0x00000001001603a4
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(struct CGPoint *)arg3;	// IMP=0x000000010016032c
- (void)scrollViewWillBeginDragging:(id)arg1;	// IMP=0x00000001001601fc
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;	// IMP=0x00000001001600e0
- (void)scrollViewDidEndDecelerating:(id)arg1;	// IMP=0x000000010015ffc4
- (void)scrollViewWillBeginDecelerating:(id)arg1;	// IMP=0x000000010015ff78
- (void)scrollViewDidScroll:(id)arg1;	// IMP=0x000000010015ff2c

@end

