/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, April 14, 2021 at 2:31:48 PM Mountain Standard Time
                       * Operating System: Version 14.4 (Build 18K802)
                       * Image Source: /usr/lib/libacmobileshim.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libacmobileshim.dylib/ACMEUIController.h>

@interface ACMEUIController_Modern : ACMEUIController
-(Class)standardSignInClass;
-(Class)customSignInClass;
-(Class)iTunesSignInClass;
-(Class)signInWidgetClass;
@end

