//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableDictionary.h>

@interface NSMutableDictionary (MCUtilities)
- (void)MCFilterRestrictionPayloadKeys:(id)arg1;	// IMP=0x0000000100018b8c
- (void)MCSetUnionSetting:(id)arg1 values:(id)arg2;	// IMP=0x0000000100018888
- (void)MCSetIntersectionSetting:(id)arg1 values:(id)arg2;	// IMP=0x0000000100018584
- (void)MCSetUnionRestriction:(id)arg1 values:(id)arg2;	// IMP=0x0000000100018280
- (void)MCSetIntersectionRestriction:(id)arg1 values:(id)arg2;	// IMP=0x0000000100017f7c
- (void)MCSetValueRestriction:(id)arg1 value:(id)arg2;	// IMP=0x0000000100017c3c
- (void)MCDeleteBoolRestriction:(id)arg1;	// IMP=0x0000000100017b84
- (void)MCSetBoolRestriction:(id)arg1 value:(_Bool)arg2;	// IMP=0x00000001000178a8
- (void)MCSetObjectIfNotNil:(id)arg1 forKey:(id)arg2;	// IMP=0x0000000100017854
- (void)MCDeepCopyMissingEntriesFromDictionary:(id)arg1;	// IMP=0x0000000100017614
- (void)MCDeepCopyEntriesFromDictionary:(id)arg1;	// IMP=0x00000001000173d8
@end

