//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXPCListenerDelegate-Protocol.h"
#import "ReportingdSessionDelegate-Protocol.h"

@class NSDate, NSMutableArray, NSMutableDictionary, NSString, RTCActivityScheduler, RTCActivitySchedulerOptions, RTCSelfReporter;
@protocol OS_dispatch_queue, OS_os_transaction;

@interface ReportingdAgent : NSObject <NSXPCListenerDelegate, ReportingdSessionDelegate>
{
    NSMutableDictionary *_processActiveSessions;	// 8 = 0x8
    NSMutableArray *_sessionList;	// 16 = 0x10
    NSMutableDictionary *_cachedStorebags;	// 24 = 0x18
    NSMutableDictionary *_correlatedSessions;	// 32 = 0x20
    NSMutableArray *_emphemeralSessions;	// 40 = 0x28
    NSMutableDictionary *_sharedData;	// 48 = 0x30
    NSMutableDictionary *_sharedConnectivityHelpers;	// 56 = 0x38
    int _OSTransactionReferenceCounter;	// 64 = 0x40
    NSObject<OS_dispatch_queue> *_stateQueue;	// 72 = 0x48
    RTCActivitySchedulerOptions *_optionsForNormalScheduling;	// 80 = 0x50
    RTCActivitySchedulerOptions *_optionsForPeriodicRealtimeScheduling;	// 88 = 0x58
    RTCActivitySchedulerOptions *_optionsForAllRealtimeScheduling;	// 96 = 0x60
    RTCActivityScheduler *_normalActivityScheduler;	// 104 = 0x68
    RTCActivityScheduler *_periodicRealtimeActivityScheduler;	// 112 = 0x70
    RTCActivityScheduler *_allRealtimeActivityScheduler;	// 120 = 0x78
    RTCSelfReporter *_selfReporter;	// 128 = 0x80
    unsigned char _activeClients[37];	// 136 = 0x88
    NSObject<OS_os_transaction> *_OSTransaction;	// 176 = 0xb0
    NSDate *_nextAllowedStorebagNetworkFetchRequest;	// 184 = 0xb8
}

- (void)fetchAndCacheStorebag:(int)arg1 forBundleID:(id)arg2 andUserInfo:(id)arg3;	// IMP=0x0000000100022ad8
- (void)networkFetchDidFail;	// IMP=0x00000001000229dc
- (_Bool)canFetchNetworkStorebag;	// IMP=0x00000001000228c0
- (id)sharedActivitySchedulerForRealtimeBackend:(_Bool)arg1 isBatching:(_Bool)arg2;	// IMP=0x000000010002289c
- (id)sharedDataForSession:(id)arg1;	// IMP=0x0000000100022860
- (void)removeObjectFromSharedDataForSession:(id)arg1 key:(id)arg2;	// IMP=0x0000000100022800
- (void)updateSharedDataForSession:(id)arg1 sharedData:(id)arg2;	// IMP=0x0000000100022754
- (_Bool)isActiveClientLimitReachedForSession:(id)arg1 sessionInfo:(id)arg2;	// IMP=0x0000000100022454
- (void)copyReportingAgentState:(id *)arg1 cachedStorebags:(id *)arg2;	// IMP=0x0000000100022358
- (void)saveEphemeralSessions;	// IMP=0x000000010002234c
- (id)getEphemeralSessions;	// IMP=0x0000000100022344
- (id)getSelfReporter;	// IMP=0x000000010002233c
- (void)updateDownstreamSessions:(id)arg1;	// IMP=0x0000000100022078
- (id)getAncestorWithAggregatorForSession:(id)arg1;	// IMP=0x0000000100021fa4
- (id)parentSessionForChild:(id)arg1;	// IMP=0x0000000100021d68
- (void)updateCorrelatedSessions:(id)arg1;	// IMP=0x0000000100021a40
- (id)getFirstSessionWithHierarchy:(int)arg1 inSessionList:(id)arg2;	// IMP=0x000000010002191c
- (id)parentSessionIDStringForSession:(id)arg1;	// IMP=0x00000001000215ac
- (id)storebagVersionForSession:(id)arg1;	// IMP=0x00000001000214dc
- (id)storebagForSession:(id)arg1;	// IMP=0x0000000100020fc8
- (void)retainOSTransaction;	// IMP=0x0000000100020e9c
- (void)releaseOSTransactions:(unsigned int)arg1;	// IMP=0x0000000100020d50
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x0000000100020608
- (void)saveEphermalSessionsToDisk;	// IMP=0x0000000100020400
- (void)loadOrCreateEphemeralSessionsLookup;	// IMP=0x0000000100020164
- (void)perPIDInfo:(int)arg1;	// IMP=0x000000010001fef8
- (id)bundleIDforXPCConnection:(id)arg1 forProcessName:(id)arg2;	// IMP=0x000000010001fdcc
- (id)processNameForPID:(int)arg1;	// IMP=0x000000010001fcf8
- (void)invalidateSession:(id)arg1;	// IMP=0x000000010001fcec
- (id)createSession;	// IMP=0x000000010001fcd8
- (void)run;	// IMP=0x000000010001fc60
- (void)dealloc;	// IMP=0x000000010001fb7c
- (id)init;	// IMP=0x000000010001f910
- (void)invalidateReportingSession:(id)arg1;	// IMP=0x000000010001f5b0
- (id)createReportingSessionWithDelegate:(id)arg1 connection:(id)arg2;	// IMP=0x000000010001f414

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

