//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SSSQLiteDatabase;

@interface AccountCacheDBClient : NSObject
{
    SSSQLiteDatabase *_database;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100081db8
- (id)_databasePath;	// IMP=0x0000000100081ce4
- (id)DSIDForAppleID:(id)arg1;	// IMP=0x0000000100081b38
- (id)init;	// IMP=0x0000000100081a9c

@end

