//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface AppConduit : NSObject
{
}

+ (void)setUpdatesPendingForCompanionApps:(id)arg1;	// IMP=0x00000001002567c0
+ (void)setUpdatePendingForCompanionApp:(id)arg1;	// IMP=0x00000001002567bc
+ (void)cancelUpdatesPendingForCompanionApps:(id)arg1;	// IMP=0x00000001002567b8
+ (void)cancelUpdatePendingForCompanionApp:(id)arg1;	// IMP=0x00000001002567b4

@end

