//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AppInstallsDatabaseTransaction.h"

@class NSMutableArray;

@interface AppSchedulerDatabaseTransaction : AppInstallsDatabaseTransaction
{
    NSMutableArray *_jettisonCandidates;	// 8 = 0x8
}

+ (id)_queryJettisonCandidatesOnConnection:(id)arg1;	// IMP=0x00000001002bc710
+ (id)_queryActiveInstallationStatisticsOnConnection:(id)arg1;	// IMP=0x00000001002bc504
- (void).cxx_destruct;	// IMP=0x00000001002bcfa4
- (_Bool)_verifyBootstrapCompleteOrNotRequired:(id)arg1;	// IMP=0x00000001002bcde0
- (_Bool)_verifyActiveInstallation:(id)arg1;	// IMP=0x00000001002bcc78
- (id)_findJettisonCandidateForPriority:(long long)arg1;	// IMP=0x00000001002bcaec
- (id)scheduleMaximumActiveCount:(unsigned long long)arg1 evaluateUsingBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000001002bbb04
- (id)jettisonActiveInstallationsToReduceActiveCountTo:(unsigned long long)arg1 forReason:(long long)arg2;	// IMP=0x00000001002bb83c
- (void)bootstrapSourceType:(long long)arg1 enumerateUsingBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000001002bb3fc
- (void)bootstrapResetSourceType:(long long)arg1 withError:(id)arg2;	// IMP=0x00000001002bb068

@end

