//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSHashTable;

@interface PIDHashTable : NSObject
{
    NSHashTable *_hash;	// 8 = 0x8
}

+ (id)hashTable;	// IMP=0x000000010019f980
- (void).cxx_destruct;	// IMP=0x000000010019fbbc
- (id)_initWithHashTable:(id)arg1;	// IMP=0x000000010019fb44
- (id)description;	// IMP=0x000000010019fa90
- (void)removePID:(long long)arg1;	// IMP=0x000000010019fa68
- (_Bool)containsPID:(long long)arg1;	// IMP=0x000000010019fa38
- (void)addPID:(long long)arg1;	// IMP=0x000000010019fa10

@end

