//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface Storage : NSObject
{
}

+ (id)_whitelistForCachedDataPath;	// IMP=0x0000000100160db4
+ (id)_rootDownloadPath;	// IMP=0x0000000100160d08
+ (void)_enforceWhitelist:(id)arg1 forPath:(id)arg2;	// IMP=0x0000000100160854
+ (id)_containerURL;	// IMP=0x00000001001603a0
+ (id)_downloadPathForID:(id)arg1;	// IMP=0x0000000100160320
+ (id)_createDirectoryInSearchPath:(unsigned long long)arg1 domain:(unsigned long long)arg2 withPathComponent:(id)arg3;	// IMP=0x00000001001601dc
+ (id)_createDirectoryAtBaseURL:(id)arg1 withPathComponent:(id)arg2;	// IMP=0x00000001001600ac
+ (id)persistedDataPathForDomain:(id)arg1;	// IMP=0x0000000100160020
+ (void)enforceWhitelistForDomain:(id)arg1;	// IMP=0x000000010015ff84
+ (id)downloadPathForID:(id)arg1;	// IMP=0x000000010015fdc0
+ (void)cleanupDownloadPathsNotMatchingIDs:(id)arg1;	// IMP=0x000000010015fa48
+ (void)cleanupDownloadPathForID:(id)arg1;	// IMP=0x000000010015f8d4
+ (id)cachedDataPathForDomain:(id)arg1;	// IMP=0x000000010015f874
+ (id)odrScratchPath;	// IMP=0x000000010015f818
+ (id)scratchPath;	// IMP=0x000000010015f69c
+ (id)libraryPath;	// IMP=0x000000010015f548

@end

