//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WorkspaceTool : NSObject
{
}

+ (id)_placeholderScratch;	// IMP=0x00000001000812bc
+ (_Bool)_placeholderInstalledForBundleID:(id)arg1;	// IMP=0x00000001000811f8
+ (_Bool)uninstallPlaceholderForBundleID:(id)arg1;	// IMP=0x0000000100080f54
+ (id)iTunesMetadataPlistForProxy:(id)arg1;	// IMP=0x0000000100080e6c
+ (_Bool)isFactoryInstallAppProxy:(id)arg1;	// IMP=0x0000000100080d48
+ (_Bool)isCorruptedFactoryInstallAppProxy:(id)arg1;	// IMP=0x0000000100080674
+ (_Bool)cancelProgressForBundleID:(id)arg1;	// IMP=0x0000000100080474

@end

