//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "EscrowGenericRequest.h"

@class EscrowPrerecord;

@interface EscrowUpdateBlobRequest : EscrowGenericRequest
{
    EscrowPrerecord *_prerecord;	// 216 = 0xd8
}

- (void).cxx_destruct;	// IMP=0x000000010001dc84
@property(retain, nonatomic) EscrowPrerecord *prerecord; // @synthesize prerecord=_prerecord;
- (id)bodyDictionary;	// IMP=0x000000010001d9bc
- (id)command;	// IMP=0x000000010001d9b0
- (id)urlString;	// IMP=0x000000010001d954
- (Class)responseClass;	// IMP=0x000000010001d948
- (id)initWithRequest:(id)arg1;	// IMP=0x000000010001d8a4

@end

