//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDataDelegate-Protocol.h"
#import "SDAirDropFileZipperDelegate-Protocol.h"
#import "SDBonjourResolverDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSMutableData, NSMutableDictionary, NSMutableSet, NSNumber, NSProgress, NSString, NSURL, NSURLResponse, NSURLSession, NSURLSessionUploadTask, SDAirDropFileZipper, SDAirDropPeerMetric, SDBonjourResolver, SDStatusMonitor, SDXPCHelperConnection;
@protocol OS_dispatch_queue, OS_os_transaction, SDAirDropClientDelegate;

__attribute__((visibility("hidden")))
@interface SDAirDropClient : NSObject <SDAirDropFileZipperDelegate, SDBonjourResolverDelegate, NSURLSessionDataDelegate>
{
    NSURLResponse *_askResponse;	// 8 = 0x8
    NSURLSessionUploadTask *_askTask;	// 16 = 0x10
    _Bool _cancelled;	// 24 = 0x18
    NSString *_clientBundleID;	// 32 = 0x20
    NSString *_compressionType;	// 40 = 0x28
    NSString *_connectionKey;	// 48 = 0x30
    _Bool _conversionNotified;	// 56 = 0x38
    _Bool _conversionObserver;	// 57 = 0x39
    NSProgress *_conversionProgress;	// 64 = 0x40
    _Bool _discover;	// 72 = 0x48
    NSURLResponse *_discoverResponse;	// 80 = 0x50
    NSURLSessionUploadTask *_discoverTask;	// 88 = 0x58
    int _failCount;	// 96 = 0x60
    struct CGImage *_fileIcon;	// 104 = 0x68
    NSMutableArray *_fileURLs;	// 112 = 0x70
    NSMutableDictionary *_fileURLToConversionNeeded;	// 120 = 0x78
    NSMutableSet *_generatedFiles;	// 128 = 0x80
    struct __SecIdentity *_identity;	// 136 = 0x88
    NSArray *_items;	// 144 = 0x90
    long long _lastEvent;	// 152 = 0x98
    NSMutableArray *_mediaFormatConversionDestinations;	// 160 = 0xa0
    SDAirDropPeerMetric *_metric;	// 168 = 0xa8
    SDStatusMonitor *_monitor;	// 176 = 0xb0
    NSMutableArray *_otherStuff;	// 184 = 0xb8
    _Bool _p2pRetained;	// 192 = 0xc0
    struct __SFNode *_person;	// 200 = 0xc8
    _Bool _personAdded;	// 208 = 0xd0
    unsigned int _powerAssertionID;	// 212 = 0xd4
    NSProgress *_progress;	// 216 = 0xd8
    NSMutableDictionary *_properties;	// 224 = 0xe0
    _Bool _providedStream;	// 232 = 0xe8
    NSObject<OS_dispatch_queue> *_queue;	// 240 = 0xf0
    _Bool _queueSuspended;	// 248 = 0xf8
    NSMutableData *_receiverData;	// 256 = 0x100
    SDBonjourResolver *_resolver;	// 264 = 0x108
    NSNumber *_sendingLivePhotoJPEGs;	// 272 = 0x110
    struct __SecTrust *_serverTrust;	// 280 = 0x118
    NSURL *_serverURL;	// 288 = 0x120
    NSURLSession *_session;	// 296 = 0x128
    _Bool _shouldPublishProgress;	// 304 = 0x130
    struct CGImage *_smallFileIcon;	// 312 = 0x138
    double _startTime;	// 320 = 0x140
    NSURL *_tmpDirectoryToCleanUp;	// 328 = 0x148
    NSObject<OS_os_transaction> *_transaction;	// 336 = 0x150
    _Bool _transactionStarted;	// 344 = 0x158
    NSProgress *_transferProgress;	// 352 = 0x160
    _Bool _uploadFinished;	// 360 = 0x168
    NSURLResponse *_uploadResponse;	// 368 = 0x170
    NSURLSessionUploadTask *_uploadTask;	// 376 = 0x178
    NSMutableArray *_weblocURLs;	// 384 = 0x180
    SDXPCHelperConnection *_xpcHelperConnection;	// 392 = 0x188
    SDAirDropFileZipper *_zipper;	// 400 = 0x190
    _Bool _zipperFinished;	// 408 = 0x198
    int _clientPid;	// 412 = 0x19c
    id <SDAirDropClientDelegate> _delegate;	// 416 = 0x1a0
    CDStruct_4c969caf _auditToken;	// 424 = 0x1a8
}

- (void).cxx_destruct;	// IMP=0x000000010007c030
@property __weak id <SDAirDropClientDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool shouldPublishProgress; // @synthesize shouldPublishProgress=_shouldPublishProgress;
@property(copy) NSString *clientBundleID; // @synthesize clientBundleID=_clientBundleID;
@property int clientPid; // @synthesize clientPid=_clientPid;
@property CDStruct_4c969caf auditToken; // @synthesize auditToken=_auditToken;
- (void)donateTransferInteractionToDuet;	// IMP=0x000000010007bfa4
- (void)convertMediaItemsWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010007bf98
- (void)generatePreviewForFileURL:(id)arg1;	// IMP=0x000000010007bf94
- (void)invalidate;	// IMP=0x000000010007bb50
@property(readonly) NSString *personID;
- (_Bool)send;	// IMP=0x000000010007b950
- (void)resolve;	// IMP=0x000000010007b834
- (void)activate;	// IMP=0x000000010007b30c
- (void)startSending;	// IMP=0x000000010007ad90
- (id)tmpDirectory;	// IMP=0x000000010007abf8
- (void)cancelSendingClassroom;	// IMP=0x000000010007ab40
- (void)startSendingClassroom;	// IMP=0x000000010007a944
- (void)startPublishingProgress;	// IMP=0x000000010007a70c
- (void)removeFileIconsFromProperties;	// IMP=0x000000010007a638
- (void)appendFileURL:(id)arg1 withBase:(id)arg2 toItems:(id)arg3;	// IMP=0x000000010007a284
- (void)validateAirDropItemsWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100079cb0
- (_Bool)replaceFileURLsWithRealPaths;	// IMP=0x0000000100079b18
- (_Bool)splitOutFileURLs;	// IMP=0x000000010007976c
- (id)realPathURL:(struct __CFURL *)arg1;	// IMP=0x00000001000795c4
- (id)webURLFromInternetLocationFile:(id)arg1;	// IMP=0x00000001000794f8
- (id)internetLocationFile:(struct __CFURL *)arg1;	// IMP=0x000000010007937c
- (id)temporaryWeblocURL:(struct __CFURL *)arg1;	// IMP=0x0000000100079198
- (void)startZipping;	// IMP=0x00000001000790bc
- (void)sendRequest:(id)arg1;	// IMP=0x0000000100078a50
- (id)discoverBodyDataInFormat:(long long)arg1;	// IMP=0x00000001000789d4
- (id)askBodyDataInFormat:(long long)arg1;	// IMP=0x00000001000786f8
- (void)addHashesAndValidationRecordToRequest:(id)arg1;	// IMP=0x0000000100078638
- (void)bonjourResolverDidChange:(id)arg1;	// IMP=0x00000001000781f0
- (void)fileZipper:(id)arg1 event:(long long)arg2 withProperty:(void *)arg3;	// IMP=0x0000000100078060
- (void)URLSession:(id)arg1 task:(id)arg2 needNewBodyStream:(CDUnknownBlockType)arg3;	// IMP=0x0000000100077f2c
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100077a1c
- (void)URLSession:(id)arg1 task:(id)arg2 didFinishCollectingMetrics:(id)arg3;	// IMP=0x00000001000775cc
@property(readonly) struct __SecTrust *secTrustRef;
- (void)logInterfaceUsedForSending:(id)arg1;	// IMP=0x0000000100077568
- (void)releasePeerToPeerIfPossible:(id)arg1;	// IMP=0x00000001000774e8
- (_Bool)connectionOverP2P:(struct __CFData *)arg1;	// IMP=0x00000001000772b8
- (struct __SecKey *)copyReceiverPublicKey;	// IMP=0x00000001000771b8
- (void)evaluateReceiverTrust:(struct __SecTrust *)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100077020
- (void)didFail:(id)arg1;	// IMP=0x0000000100076d80
- (_Bool)shouldCancelTransferForError:(id)arg1;	// IMP=0x0000000100076c84
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;	// IMP=0x0000000100076bbc
- (void)URLSession:(id)arg1 task:(id)arg2 didSendBodyData:(long long)arg3 totalBytesSent:(long long)arg4 totalBytesExpectedToSend:(long long)arg5;	// IMP=0x0000000100076b3c
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;	// IMP=0x0000000100076a98
- (void)didFinishLoading;	// IMP=0x00000001000768d4
- (void)retryRequestForError:(id)arg1;	// IMP=0x00000001000766f4
- (void)finishOperation;	// IMP=0x0000000100076368
- (void)notifyClientOfBytesCopied:(id)arg1 timeRemaining:(id)arg2;	// IMP=0x000000010007620c
- (_Bool)parseDiscoverResponse:(struct __CFError **)arg1;	// IMP=0x0000000100076038
- (_Bool)parseAskResponse:(struct __CFError **)arg1;	// IMP=0x0000000100075eb8
- (void)storeStringValue:(struct __CFDictionary *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x0000000100075e0c
- (void)storeDataValue:(struct __CFDictionary *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x0000000100075d60
- (void)storePropertyValue:(void *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x0000000100075c48
- (void)setProperty:(id)arg1 forKey:(id)arg2;	// IMP=0x0000000100075bf8
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x0000000100075630
- (void)setSpotlightMetadata:(id)arg1;	// IMP=0x000000010007562c
- (id)whereFromInfo;	// IMP=0x0000000100075584
- (void)didFinishSendingAskBodyData;	// IMP=0x000000010007553c
- (void)didStartSendingAskBodyData;	// IMP=0x00000001000754a8
- (void)postNotificationForTransferStatus:(long long)arg1 progress:(double)arg2;	// IMP=0x00000001000754a4
- (void)notifyClientForEvent:(long long)arg1 withProperty:(void *)arg2;	// IMP=0x0000000100074d58
- (void)releaseIdleSleepAssertion;	// IMP=0x0000000100074c48
- (double)getTransferRate;	// IMP=0x0000000100074bc0
- (void)createSession;	// IMP=0x00000001000748d0
- (_Bool)requireAWDL;	// IMP=0x0000000100074884
- (void)removeObservers;	// IMP=0x0000000100074834
- (void)addObservers;	// IMP=0x0000000100074798
- (void)wirelessPowerChanged:(id)arg1;	// IMP=0x0000000100074728
- (void)systemWillSleep:(id)arg1;	// IMP=0x00000001000746d8
- (void)dealloc;	// IMP=0x00000001000745ec
- (id)initWithPerson:(struct __SFNode *)arg1 items:(id)arg2 forDiscovery:(_Bool)arg3;	// IMP=0x00000001000741f8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

