//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDAirDropHandler.h"

@class SFSharablePassword;

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerCredentialLinks : SDAirDropHandler
{
    SFSharablePassword *_credential;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000e38b0
- (void)updatePossibleActions;	// IMP=0x00000001000e3618
- (long long)transferTypes;	// IMP=0x00000001000e35e0
- (id)suitableContentsDescription;	// IMP=0x00000001000e3434
- (void)handleAction;	// IMP=0x00000001000e339c
- (_Bool)canHandleTransfer;	// IMP=0x00000001000e32ec

@end

