//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GeoServices/GEOServiceRequester.h>

@interface _GEOLocationShiftRequester : GEOServiceRequester
{
}

- (id)_validateResponse:(id)arg1;	// IMP=0x000000010001acb8
- (void)cancelRequest:(id)arg1;	// IMP=0x000000010001acac
- (void)startWithRequest:(id)arg1 traits:(id)arg2 auditToken:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010001ab18

@end

