//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSLock;

@interface GEOAnalyticsPipelineCountsAggregator : NSObject
{
    NSDate *_lastAggregation;	// 8 = 0x8
    double _aggregationInterval;	// 16 = 0x10
    NSLock *_runningLock;	// 24 = 0x18
}

+ (id)sharedAggregator;	// IMP=0x0000000100014e74
- (void).cxx_destruct;	// IMP=0x0000000100018b84
- (void)runEvalAggregation;	// IMP=0x0000000100018a18
- (id)apPersistence;	// IMP=0x0000000100018a04
- (id)daemonIdAdditions;	// IMP=0x00000001000189f4
- (id)now;	// IMP=0x00000001000189d8
- (double)retrieveAggregationInterval;	// IMP=0x00000001000189c8
- (id)retrieveLastAggregationTime;	// IMP=0x00000001000189b8
- (void)saveLastAggregationTime:(id)arg1;	// IMP=0x00000001000189a8
- (int)appTypeForApp:(id)arg1;	// IMP=0x00000001000187b4
- (id)daemonSet;	// IMP=0x0000000100018560
- (id)firstPartySet;	// IMP=0x00000001000184dc
- (void)aggregateCountsAndReportFrom:(id)arg1 until:(id)arg2;	// IMP=0x00000001000182ec
- (void)aggregateDailyUsageCountsAndReportFrom:(id)arg1 until:(id)arg2;	// IMP=0x00000001000172c8
- (void)reportDailySettingsFrom:(id)arg1 until:(id)arg2;	// IMP=0x0000000100016fc0
- (void)reportCuratedCollectionSavedListFrom:(id)arg1 until:(id)arg2;	// IMP=0x0000000100016c9c
- (void)aggregateCuratedCollectionViewCountsAndReportFrom:(id)arg1 until:(id)arg2;	// IMP=0x0000000100016010
- (void)aggregateMapKitCountsAndReportFrom:(id)arg1 until:(id)arg2;	// IMP=0x00000001000153d8
- (void)startAggregation;	// IMP=0x0000000100015134
@property(readonly, nonatomic) NSDate *nextAggregationTime;
@property(readonly, nonatomic) NSDate *lastAggregationTime;
- (void)setup;	// IMP=0x0000000100014f38
- (id)init;	// IMP=0x0000000100014ee0

@end

