//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GeoServices/GEOServer.h>

@class GEOLocationShifter;

@interface GEOLocationShiftServer : GEOServer
{
    GEOLocationShifter *_shifter;	// 16 = 0x10
}

+ (id)identifier;	// IMP=0x000000010001198c
- (void).cxx_destruct;	// IMP=0x0000000100019548
- (void)flushDiskCacheWithMessage:(id)arg1;	// IMP=0x0000000100019418
- (void)functionVersionWithMessage:(id)arg1;	// IMP=0x000000010001930c
- (void)isRequiredForCoordinateWithMessage:(id)arg1;	// IMP=0x000000010001911c
- (void)isEnabledWithMessage:(id)arg1;	// IMP=0x0000000100019010
- (void)shiftCoordinateWithMessage:(id)arg1;	// IMP=0x0000000100018c30
- (id)init;	// IMP=0x0000000100018bb4
- (_Bool)handleIncomingMessage:(id)arg1 withObject:(id)arg2 fromPeer:(id)arg3;	// IMP=0x0000000100011998

@end

