//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface RadioTS : NSObject
{
    int _sensorIndexTB0R;	// 8 = 0x8
    int _sensorIndexTB1R;	// 12 = 0xc
    _Bool _hasBaseBandTempSensors;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x000000010001a704
- (_Bool)hasBaseBandTempSensors;	// IMP=0x000000010001a7a4
- (void)registerForThermalReport;	// IMP=0x000000010001a7a0
- (void)queryThermalSensorInfo;	// IMP=0x000000010001a79c
- (id)init;	// IMP=0x000000010001a768

@end

