//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface AMSDTransactionStore : NSObject
{
}

+ (void)takeKeepAliveTransaction:(id)arg1 withQueue:(id)arg2 whilePerformingBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010002fe60
+ (void)takeKeepAliveTransaction:(id)arg1 whilePerformingBlock:(CDUnknownBlockType)arg2;	// IMP=0x000000010002fdd0
+ (void)takeKeepAliveTransaction:(id)arg1;	// IMP=0x000000010002faf8
+ (void)releaseKeepAliveTransaction:(id)arg1;	// IMP=0x000000010002f72c
+ (id)transactionsCount;	// IMP=0x000000010002f694
+ (id)transactionsAccessQueue;	// IMP=0x000000010002f5fc
+ (id)transactions;	// IMP=0x000000010002f564

@end

