//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RPCompanionLinkXPCServerInterface-Protocol.h"

@class CUBonjourDevice, NSMutableDictionary, NSMutableSet, NSString, NSXPCConnection, RPCompanionLinkClient, RPCompanionLinkDaemon, RPCompanionLinkDevice, RPConnection, RPDiscovery, RPServer, RPSession;
@protocol OS_dispatch_queue, OS_dispatch_source, OS_os_transaction;

@interface RPCompanionLinkXPCConnection : NSObject <RPCompanionLinkXPCServerInterface>
{
    CDStruct_20fd928a _metricsCtx;	// 8 = 0x8
    _Bool _entitled;	// 32 = 0x20
    _Bool _localDeviceUpdated;	// 33 = 0x21
    _Bool _needsCLink;	// 34 = 0x22
    unsigned int _xpcID;	// 36 = 0x24
    RPCompanionLinkClient *_client;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 48 = 0x30
    RPConnection *_netCnx;	// 56 = 0x38
    NSString *_appID;	// 64 = 0x40
    CUBonjourDevice *_bonjourDevice;	// 72 = 0x48
    RPCompanionLinkDaemon *_daemon;	// 80 = 0x50
    RPCompanionLinkDevice *_daemonDevice;	// 88 = 0x58
    NSMutableDictionary *_devices;	// 96 = 0x60
    RPDiscovery *_discoveryClient;	// 104 = 0x68
    NSObject<OS_dispatch_source> *_discoveryTimer;	// 112 = 0x70
    NSMutableDictionary *_registeredEvents;	// 120 = 0x78
    NSMutableSet *_registeredProfileIDs;	// 128 = 0x80
    NSMutableDictionary *_registeredRequests;	// 136 = 0x88
    NSObject<OS_os_transaction> *_osTransaction;	// 144 = 0x90
    RPServer *_server;	// 152 = 0x98
    RPSession *_session;	// 160 = 0xa0
    unsigned long long _startTicks;	// 168 = 0xa8
    NSXPCConnection *_xpcCnx;	// 176 = 0xb0
}

- (void).cxx_destruct;	// IMP=0x000000010002b574
@property(nonatomic) unsigned int xpcID; // @synthesize xpcID=_xpcID;
@property(readonly, nonatomic) NSXPCConnection *xpcCnx; // @synthesize xpcCnx=_xpcCnx;
@property(nonatomic) unsigned long long startTicks; // @synthesize startTicks=_startTicks;
@property(retain, nonatomic) RPSession *session; // @synthesize session=_session;
@property(retain, nonatomic) RPServer *server; // @synthesize server=_server;
@property(retain, nonatomic) NSObject<OS_os_transaction> *osTransaction; // @synthesize osTransaction=_osTransaction;
@property(readonly, nonatomic) NSMutableDictionary *registeredRequests; // @synthesize registeredRequests=_registeredRequests;
@property(readonly, nonatomic) NSMutableSet *registeredProfileIDs; // @synthesize registeredProfileIDs=_registeredProfileIDs;
@property(readonly, nonatomic) NSMutableDictionary *registeredEvents; // @synthesize registeredEvents=_registeredEvents;
@property(nonatomic) _Bool needsCLink; // @synthesize needsCLink=_needsCLink;
@property(nonatomic) _Bool localDeviceUpdated; // @synthesize localDeviceUpdated=_localDeviceUpdated;
@property(readonly, nonatomic) _Bool entitled; // @synthesize entitled=_entitled;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *discoveryTimer; // @synthesize discoveryTimer=_discoveryTimer;
@property(retain, nonatomic) RPDiscovery *discoveryClient; // @synthesize discoveryClient=_discoveryClient;
@property(readonly, nonatomic) NSMutableDictionary *devices; // @synthesize devices=_devices;
@property(readonly, nonatomic) RPCompanionLinkDevice *daemonDevice; // @synthesize daemonDevice=_daemonDevice;
@property(readonly, nonatomic) RPCompanionLinkDaemon *daemon; // @synthesize daemon=_daemon;
@property(retain, nonatomic) CUBonjourDevice *bonjourDevice; // @synthesize bonjourDevice=_bonjourDevice;
@property(retain, nonatomic) NSString *appID; // @synthesize appID=_appID;
@property(retain, nonatomic) RPConnection *netCnx; // @synthesize netCnx=_netCnx;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
@property(retain, nonatomic) RPCompanionLinkClient *client; // @synthesize client=_client;
- (void)xpcSessionActivate:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010002b2f4
- (void)xpcServerUpdate:(id)arg1;	// IMP=0x000000010002b004
- (void)xpcServerActivate:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010002a958
- (void)xpcDiscoveryUpdate:(id)arg1;	// IMP=0x000000010002a8a0
- (void)xpcDiscoveryActivate:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010002a764
- (void)companionLinkTryPassword:(id)arg1;	// IMP=0x000000010002a674
- (void)companionLinkSendRequestID:(id)arg1 request:(id)arg2 destinationID:(id)arg3 options:(id)arg4 responseHandler:(CDUnknownBlockType)arg5;	// IMP=0x000000010002a440
- (void)companionLinkDeregisterRequestID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010002a384
- (void)companionLinkRegisterRequestID:(id)arg1 options:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010002a278
- (void)companionLinkDeregisterProfileID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010002a124
- (void)companionLinkRegisterProfileID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100029eb0
- (void)companionLinkSendEventID:(id)arg1 event:(id)arg2 destinationID:(id)arg3 options:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x0000000100029c8c
- (void)companionLinkDeregisterEventID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100029b10
- (void)companionLinkRegisterEventID:(id)arg1 options:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100029894
- (void)companionLinkUpdateClient:(id)arg1;	// IMP=0x0000000100029534
- (void)companionLinkActivateClient:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100028690
- (void)companionLinkInvalidateAssertion:(id)arg1;	// IMP=0x000000010002868c
- (void)companionLinkActivateAssertion:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100028674
- (void)reportChangedDevice:(id)arg1 changes:(unsigned int)arg2;	// IMP=0x00000001000284a0
- (void)reportLostDevice:(id)arg1;	// IMP=0x000000010002834c
- (void)reportFoundDevice:(id)arg1;	// IMP=0x00000001000281f4
- (void)receivedRequestID:(id)arg1 request:(id)arg2 options:(id)arg3 responseHandler:(CDUnknownBlockType)arg4;	// IMP=0x00000001000280d8
- (void)receivedEventID:(id)arg1 event:(id)arg2 options:(id)arg3;	// IMP=0x0000000100027fe0
- (void)promptForPasswordType:(int)arg1 flags:(unsigned int)arg2 throttleSeconds:(int)arg3;	// IMP=0x0000000100027ef0
- (id)_devicesForClient:(id)arg1;	// IMP=0x0000000100027c18
- (void)handleDisconnect;	// IMP=0x0000000100027b80
- (void)authCompletion:(id)arg1;	// IMP=0x0000000100027ac4
- (_Bool)_entitledAndReturnError:(id *)arg1;	// IMP=0x0000000100027984
- (void)connectionInvalidatedCore;	// IMP=0x0000000100027208
- (void)connectionInvalidated;	// IMP=0x000000010002708c
- (id)initWithDaemon:(id)arg1 xpcCnx:(id)arg2;	// IMP=0x0000000100026fd0

@end

