//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC6Arcade31ArtworkDisplayingViewController : UIViewController
{
}

- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100066e48
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100066d80
- (void)loadView;	// IMP=0x0000000100066cb8

@end

