//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "MSDContentServerConnectionFreeSpaceDelegate-Protocol.h"

@class MSDContentServer, MSDSignedManifest, NSString;

@interface MSDAppUpdater : NSObject <MSDContentServerConnectionFreeSpaceDelegate>
{
    MSDSignedManifest *_manifest;	// 8 = 0x8
    MSDContentServer *_server;	// 16 = 0x10
    NSString *_currentApp;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x0000000100047bd8
- (void).cxx_destruct;	// IMP=0x000000010004b160
@property(retain, nonatomic) NSString *currentApp; // @synthesize currentApp=_currentApp;
@property(retain, nonatomic) MSDContentServer *server; // @synthesize server=_server;
@property(retain, nonatomic) MSDSignedManifest *manifest; // @synthesize manifest=_manifest;
- (long long)freeSpaceNeeded:(long long)arg1;	// IMP=0x000000010004afd8
- (long long)sizeToReserve;	// IMP=0x000000010004af28
- (_Bool)stopAllAppsExcept:(id)arg1;	// IMP=0x000000010004ac94
- (_Bool)installAndVerifyApp:(id)arg1 fullIPAHash:(id)arg2 UID:(id)arg3 currentUID:(id)arg4 fromServer:(id)arg5 error:(id *)arg6;	// IMP=0x000000010004a8b0
- (_Bool)verifyApp:(id)arg1 expectedUID:(id)arg2;	// IMP=0x000000010004a4c8
- (_Bool)installApp:(id)arg1 fullIPAHash:(id)arg2 UID:(id)arg3 currentUID:(id)arg4 fromServer:(id)arg5 error:(id *)arg6;	// IMP=0x000000010004a35c
- (_Bool)IXInstallApp:(id)arg1 fullIPAHash:(id)arg2 UID:(id)arg3 currentUID:(id)arg4 fromServer:(id)arg5 error:(id *)arg6;	// IMP=0x00000001000495bc
- (_Bool)IXMacInstallApp:(id)arg1 fullIPAHash:(id)arg2 UID:(id)arg3 currentUID:(id)arg4 fromServer:(id)arg5 error:(id *)arg6;	// IMP=0x00000001000495b4
- (_Bool)updateOrInstallAppAndData:(id)arg1 error:(id *)arg2 andAdditionalInfo:(id *)arg3;	// IMP=0x00000001000486c4
- (_Bool)removeAppUsingInstallCoordination:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100048390
- (_Bool)removeAppsNotInManifest:(id *)arg1;	// IMP=0x0000000100047e9c
- (id)installedApps;	// IMP=0x0000000100047c78
- (id)init;	// IMP=0x0000000100047c44

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

