//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/AceObject.h>

@interface AceObject (ADMediaRemote)
- (id)_ad_mediaRemoteOptions;	// IMP=0x000000010012f430
- (void)_ad_setPayloadOnRequestInfo:(id)arg1;	// IMP=0x00000001001b4c2c
- (void)adClientConnection_leaveRequestGroup;	// IMP=0x000000010026fd24
- (void)adClientConnection_enterRequestGroup:(id)arg1;	// IMP=0x000000010026fb74
- (_Bool)ad_transcriptionResultRequiresAddressBook;	// IMP=0x0000000100270178
- (id)ad_transcriptionResultWithAddressBookManager:(id)arg1;	// IMP=0x0000000100270170
- (_Bool)ad_shouldUseExtendedFlowTimeout;	// IMP=0x00000001002a0384
@end

