//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "AFDictionaryConvertible-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSString;

@interface ADAudioSessionCoordinationMessageKeepAudioSessionAliveRequest : NSObject <NSCopying, NSSecureCoding, AFDictionaryConvertible>
{
    double _expirationDuration;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x000000010018b168
+ (id)newWithBuilder:(CDUnknownBlockType)arg1;	// IMP=0x000000010018b55c
@property(readonly, nonatomic) double expirationDuration; // @synthesize expirationDuration=_expirationDuration;
- (id)buildDictionaryRepresentation;	// IMP=0x000000010018b380
- (id)initWithDictionaryRepresentation:(id)arg1;	// IMP=0x000000010018b2a0
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000010018b214
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010018b170
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010018b164
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010018b0d8
@property(readonly) unsigned long long hash;
- (id)_descriptionWithIndent:(unsigned long long)arg1;	// IMP=0x000000010018aef4
@property(readonly, copy) NSString *description;
- (id)initWithExpirationDuration:(double)arg1;	// IMP=0x000000010018ae9c
- (id)mutatedCopyWithMutator:(CDUnknownBlockType)arg1;	// IMP=0x000000010018b5dc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

