//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "ADBluetoothDevice-Protocol.h"
#import "AFInvalidating-Protocol.h"

@class ADMobileBluetoothDeviceDataSource, AFBluetoothDeviceInfo, AFBluetoothHeadphoneInEarDetectionState, NSHashTable, NSString, NSUUID;
@protocol OS_dispatch_queue;

@interface ADMobileBluetoothDeviceProxy : NSObject <ADBluetoothDevice, AFInvalidating>
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    ADMobileBluetoothDeviceDataSource *_dataSource;	// 16 = 0x10
    NSHashTable *_observers;	// 24 = 0x18
    AFBluetoothDeviceInfo *_deviceInfo;	// 32 = 0x20
    AFBluetoothHeadphoneInEarDetectionState *_headphoneInEarDetectionState;	// 40 = 0x28
    long long _headphoneListeningMode;	// 48 = 0x30
    NSString *_address;	// 56 = 0x38
    NSUUID *_deviceUID;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x00000001000bcb50
@property(readonly, copy, nonatomic) NSUUID *deviceUID; // @synthesize deviceUID=_deviceUID;
@property(readonly, copy, nonatomic) NSString *address; // @synthesize address=_address;
- (void)_enumerateObserversUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bca78
- (void)_invalidate;	// IMP=0x00000001000bc900
- (void)_accessBTDeviceAndAccessoryManagerUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bc438
- (void)_changeHeadphoneListeningMode:(long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000bc010
- (void)_fetchHeadphoneListeningModeWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bbdf8
- (void)_fetchHeadphoneInEarDetectionStateWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bbbd4
- (void)_fetchDeviceInfoWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bb604
- (void)_updateHeadphoneListeningMode:(long long)arg1;	// IMP=0x00000001000bb424
- (void)_updateHeadphoneInEarDetectionState:(id)arg1;	// IMP=0x00000001000bb1b0
- (void)_updateDeviceInfo:(id)arg1;	// IMP=0x00000001000baf3c
- (void)_setHeadphoneListeningMode:(long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000bac90
- (void)_getHeadphoneListeningMode:(CDUnknownBlockType)arg1;	// IMP=0x00000001000baa4c
- (void)_getHeadphoneInEarDetectionState:(CDUnknownBlockType)arg1;	// IMP=0x00000001000ba808
- (void)_getDeviceInfo:(CDUnknownBlockType)arg1;	// IMP=0x00000001000ba6fc
- (void)_reload:(_Bool)arg1;	// IMP=0x00000001000ba1c8
- (void)invalidate;	// IMP=0x00000001000ba160
- (void)removeObserver:(id)arg1;	// IMP=0x00000001000ba0b4
- (void)addObserver:(id)arg1;	// IMP=0x00000001000b9fb0
- (void)disconnect:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b9e64
- (void)connect:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b9cc8
- (void)setHeadphoneListeningMode:(long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000b9c1c
- (void)getHeadphoneListeningMode:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b9b70
- (void)getHeadphoneInEarDetectionState:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b9ac4
- (void)getDeviceInfo:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b9a18
- (id)deviceInfo;	// IMP=0x00000001000b9574
- (id)identifier;	// IMP=0x00000001000b9520
- (void)prewarm;	// IMP=0x00000001000b94b4
- (void)reload;	// IMP=0x00000001000b9448
- (void)updateHeadphoneListeningMode:(long long)arg1;	// IMP=0x00000001000b93dc
- (void)updateHeadphoneInEarDetectionState:(id)arg1;	// IMP=0x00000001000b9344
- (void)updateDeviceInfo:(id)arg1;	// IMP=0x00000001000b92ac
- (id)initWithDeviceUID:(id)arg1 dataSource:(id)arg2 queue:(id)arg3;	// IMP=0x00000001000b8efc
- (id)initWithAddress:(id)arg1 dataSource:(id)arg2 queue:(id)arg3;	// IMP=0x00000001000b8b4c
- (void)dealloc;	// IMP=0x00000001000b8a7c
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

