//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IDSServiceDelegate-Protocol.h"

@class IDSService, NSMutableDictionary, NSString;
@protocol ADPeerConnectionDelegate, OS_dispatch_queue;

@interface ADPeerConnection : NSObject <IDSServiceDelegate>
{
    NSString *_identifier;	// 8 = 0x8
    _Bool _requireConnectedPeer;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_queue;	// 24 = 0x18
    IDSService *_idsService;	// 32 = 0x20
    NSMutableDictionary *_completions;	// 40 = 0x28
    NSMutableDictionary *_responseClasses;	// 48 = 0x30
    id <ADPeerConnectionDelegate> _delegate;	// 56 = 0x38
    CDUnknownFunctionPointerType _requestMapFunc;	// 64 = 0x40
    CDUnknownFunctionPointerType _classMapFunc;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x000000010004ecbc
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(_Bool)arg4 error:(id)arg5;	// IMP=0x000000010004ebf0
- (void)service:(id)arg1 account:(id)arg2 incomingUnhandledProtobuf:(id)arg3 fromID:(id)arg4 context:(id)arg5;	// IMP=0x000000010004e624
- (id)_wrappedSendFailureError:(id)arg1;	// IMP=0x000000010004e514
- (void)_invokeCompletionForIdentifier:(id)arg1 response:(id)arg2 error:(id)arg3;	// IMP=0x000000010004e3ac
- (void)_sendResponse:(id)arg1 forRequestId:(id)arg2;	// IMP=0x000000010004e048
- (void)setDelegate:(id)arg1 forRequestTypes:(CDUnknownFunctionPointerType)arg2;	// IMP=0x000000010004df18
- (void)_sendRequest:(id)arg1 responseClass:(Class)arg2 fireAndForget:(_Bool)arg3 timeout:(double)arg4 overrideRequireConnectedPeer:(_Bool)arg5 to:(_Bool)arg6 allowCloud:(_Bool)arg7 completion:(CDUnknownBlockType)arg8;	// IMP=0x000000010004d894
- (void)sendRequest:(id)arg1 responseClass:(Class)arg2 overrideRequireConnectedPeer:(_Bool)arg3 allowCloud:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x000000010004d810
- (void)sendRequest:(id)arg1 responseClass:(Class)arg2 timeout:(double)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010004d790
- (void)sendRequest:(id)arg1 responseClass:(Class)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010004d71c
- (void)sendRequest:(id)arg1 fireAndForget:(_Bool)arg2;	// IMP=0x000000010004d6dc
- (void)sendRequest:(id)arg1;	// IMP=0x000000010004d69c
- (id)_destination;	// IMP=0x000000010004d63c
- (id)_account;	// IMP=0x000000010004d5e4
- (id)_service;	// IMP=0x000000010004d57c
- (id)serviceIdentifier;	// IMP=0x000000010004d574
- (_Bool)_hasConnectedPeer;	// IMP=0x000000010004d528
- (id)_pairedDevice;	// IMP=0x000000010004d3c0
- (_Bool)deviceIsNearby:(id *)arg1;	// IMP=0x000000010004d348
- (id)peerBuildVersion;	// IMP=0x000000010004d2f4
- (id)peerVersion;	// IMP=0x000000010004d2a0
- (id)peerName;	// IMP=0x000000010004d24c
- (id)peerType;	// IMP=0x000000010004d1f8
- (_Bool)hasPeer;	// IMP=0x000000010004d1bc
- (id)initWithServiceIdentifier:(id)arg1 forRequests:(CDUnknownFunctionPointerType)arg2;	// IMP=0x000000010004d1ac
- (id)initWithServiceIdentifier:(id)arg1 forRequests:(CDUnknownFunctionPointerType)arg2 requireConnectedPeer:(_Bool)arg3;	// IMP=0x000000010004cffc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

