//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface ADPreferences : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    _Bool _needToPostLanguageNotification;	// 16 = 0x10
    _Bool _needToPostOutputLanguageNotification;	// 17 = 0x11
    NSMutableDictionary *_redirects;	// 24 = 0x18
    NSMutableDictionary *_keychainCache;	// 32 = 0x20
}

+ (id)sharedPreferences;	// IMP=0x00000001001dd2c8
- (void).cxx_destruct;	// IMP=0x00000001001e0314
- (id)useDeviceAuthenticationVersion;	// IMP=0x00000001001e0308
- (double)myriadDeviceVTEndTimeDistanceThreshold;	// IMP=0x00000001001e0304
- (void)setMyriadDeviceVTEndTimeDistanceThreshold:(double)arg1;	// IMP=0x00000001001e0300
- (void)setMultiUserSetUpCompleteTimes:(id)arg1;	// IMP=0x00000001001e02f0
- (id)multiUserSetupCompleteTimes;	// IMP=0x00000001001e02e4
- (void)setMultiUserSetUpStartTimes:(id)arg1;	// IMP=0x00000001001e02d4
- (id)multiUserSetupStartTimes;	// IMP=0x00000001001e02c8
- (id)singleUserCompanionACEHost;	// IMP=0x00000001001e02bc
- (void)setSingleUserCompanionACEHost:(id)arg1;	// IMP=0x00000001001e02a4
- (id)singleUserMeCard;	// IMP=0x00000001001e0298
- (void)setSingleUserMeCard:(id)arg1;	// IMP=0x00000001001e0280
- (id)_keychainCache;	// IMP=0x00000001001e0234
- (void)_setKeychainValue:(id)arg1 forKey:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001001e00f4
- (id)_keychainStringForKey:(id)arg1;	// IMP=0x00000001001e005c
- (id)_cachedKeychainStringForKey:(id)arg1;	// IMP=0x00000001001dfee8
- (_Bool)dictationLanguageDetectorEnabled;	// IMP=0x00000001001dfee4
- (void)setServerAudioSessionActivationDelayAboveMediaPlaybackVolumeThreshold:(id)arg1;	// IMP=0x00000001001dfed4
- (id)serverAudioSessionActivationDelayAboveMediaPlaybackVolumeThreshold;	// IMP=0x00000001001dfe70
- (void)setServerMediaPlaybackVolumeThresholdForAudioSessionActivationDelay:(id)arg1;	// IMP=0x00000001001dfe60
- (id)serverMediaPlaybackVolumeThresholdForAudioSessionActivationDelay;	// IMP=0x00000001001dfdfc
- (void)setServerAudioSessionActivationDelay:(id)arg1;	// IMP=0x00000001001dfdec
- (id)serverAudioSessionActivationDelay;	// IMP=0x00000001001dfd88
- (id)overrideAudioSessionActiveDelay;	// IMP=0x00000001001dfd24
- (_Bool)getMinimumOutputVolume:(float *)arg1;	// IMP=0x00000001001dfc94
- (_Bool)getMaximumOutputVolume:(float *)arg1;	// IMP=0x00000001001dfc04
- (void)setLastKnownAnalyticsStoreState:(unsigned long long)arg1;	// IMP=0x00000001001dfbbc
- (unsigned long long)lastKnownAnalyticsStoreState;	// IMP=0x00000001001dfb48
- (_Bool)proxyConnectionDisabled;	// IMP=0x00000001001dfafc
- (_Bool)metricsSenderDisabled;	// IMP=0x00000001001dfaa0
- (void)setExperimentIdentifier:(id)arg1;	// IMP=0x00000001001dfa90
- (id)experimentIdentifier;	// IMP=0x00000001001dfa84
- (void)setSiriDataSharingOptInStatus:(long long)arg1;	// IMP=0x00000001001df9fc
- (long long)siriDataSharingOptInStatus;	// IMP=0x00000001001df9f8
- (void)setLastCompanionRemoteDataFetchDate:(id)arg1;	// IMP=0x00000001001df9e8
- (id)lastCompanionRemoteDataFetchDate;	// IMP=0x00000001001df984
- (void)setCompanionIdentifier:(id)arg1;	// IMP=0x00000001001df710
- (id)companionIdentifier;	// IMP=0x00000001001df60c
- (void)setSharedUserIdentifier:(id)arg1 loggingSharedUserIdentifier:(id)arg2;	// IMP=0x00000001001df2a4
- (id)loggingSharedUserIdentifier;	// IMP=0x00000001001df1a0
- (id)sharedUserIdentifier;	// IMP=0x00000001001df084
- (id)multiUserHomeUUIDsForDeletion;	// IMP=0x00000001001df020
- (void)removeMultiUserHomeUUID:(id)arg1;	// IMP=0x00000001001def48
- (void)setMultiUserHomeUUIDsForDeletion:(id)arg1;	// IMP=0x00000001001dee0c
- (void)setIsMultiUserSyncerMeDevice:(_Bool)arg1;	// IMP=0x00000001001dedc4
- (_Bool)isMultiUserSyncerMeDevice;	// IMP=0x00000001001ded78
- (void)setMultiUserSyncerBackupIdentifiersAnchor:(id)arg1;	// IMP=0x00000001001ded68
- (id)multiUserSyncerBackupIdentifiersAnchor;	// IMP=0x00000001001ded5c
- (void)setMultiUserSyncerIdentifiersAnchor:(id)arg1;	// IMP=0x00000001001ded4c
- (id)multiUserSyncerIdentifiersAnchor;	// IMP=0x00000001001ded40
- (void)setMultiUserSyncerSADAnchor:(id)arg1;	// IMP=0x00000001001ded30
- (id)multiUserSyncerSADAnchor;	// IMP=0x00000001001ded24
- (void)setMultiUserIsOnboardingDevice:(_Bool)arg1;	// IMP=0x00000001001dec38
- (_Bool)multiUserIsOnboardingDevice;	// IMP=0x00000001001debec
- (void)setMultiUserSharedUsers:(id)arg1;	// IMP=0x00000001001debdc
- (id)multiUserSharedUsers;	// IMP=0x00000001001deb78
- (void)setMultiUserPrimaryUser:(id)arg1;	// IMP=0x00000001001deb68
- (id)multiUserPrimaryUser;	// IMP=0x00000001001deb04
- (void)setHasSetupMultiUserSharedRecordZoneSubscription:(_Bool)arg1;	// IMP=0x00000001001deabc
- (_Bool)hasSetUpMultiUserSharedRecordZoneSubscription;	// IMP=0x00000001001dea70
- (void)setMultiUserSharedDataServerChangeToken:(id)arg1;	// IMP=0x00000001001dea60
- (id)multiUserSharedDataServerChangeToken;	// IMP=0x00000001001de9fc
- (void)setDeviceWasRedirectedToProduction:(_Bool)arg1;	// IMP=0x00000001001de954
- (_Bool)deviceWasRedirectedToProduction;	// IMP=0x00000001001de908
- (void)setMultiUserVoiceIdentification:(_Bool)arg1;	// IMP=0x00000001001de78c
- (_Bool)multiUserVoiceIdentification;	// IMP=0x00000001001de730
- (void)setMultiUserSharedDataServerChangeToken:(id)arg1 forOwnerName:(id)arg2;	// IMP=0x00000001001de650
- (id)multiUserSharedDataServerChangeTokenForOwner:(id)arg1;	// IMP=0x00000001001de5d0
- (void)setMirroredMultiUserSharedDataNeedsSync:(_Bool)arg1;	// IMP=0x00000001001de588
- (_Bool)mirroredMultiUserSharedDataNeedsSync;	// IMP=0x00000001001de52c
- (void)setMultiUserSharedDataNeedsSync:(_Bool)arg1;	// IMP=0x00000001001de4e4
- (_Bool)multiUserSharedDataNeedsSync;	// IMP=0x00000001001de488
- (void)setHasSetUpVoiceTriggerRecordZoneSubscription:(_Bool)arg1;	// IMP=0x00000001001de440
- (_Bool)hasSetUpVoiceTriggerRecordZoneSubscription;	// IMP=0x00000001001de3f4
- (void)setVoiceTriggerServerChangeToken:(id)arg1;	// IMP=0x00000001001de3e4
- (id)voiceTriggerServerChangeToken;	// IMP=0x00000001001de380
- (void)setVoiceTriggerNeedsDataSync:(_Bool)arg1;	// IMP=0x00000001001de338
- (_Bool)voiceTriggerNeedsDataSync;	// IMP=0x00000001001de2dc
- (_Bool)_validatePhsManifestData:(id)arg1;	// IMP=0x00000001001de054
- (void)setPhsAssetManifest:(id)arg1 onSharedZone:(_Bool)arg2;	// IMP=0x00000001001de030
- (id)phsAssetManifest:(_Bool)arg1;	// IMP=0x00000001001ddf6c
- (void)setCloudKitSharedDatabaseChangeToken:(id)arg1;	// IMP=0x00000001001ddf5c
- (id)cloudKitSharedDatabaseChangeToken;	// IMP=0x00000001001ddef8
- (void)setHasSetUpAccountStatusRecordZoneSubscription:(_Bool)arg1;	// IMP=0x00000001001ddeb0
- (_Bool)hasSetUpAccountStatusRecordZoneSubscription;	// IMP=0x00000001001dde64
- (void)setHasSetUpKeyValueRecordZoneSubscription:(_Bool)arg1;	// IMP=0x00000001001dde1c
- (_Bool)hasSetUpKeyValueRecordZoneSubscription;	// IMP=0x00000001001dddd0
- (void)setAccountStatusServerChangeToken:(id)arg1;	// IMP=0x00000001001dddc0
- (id)accountStatusServerChangeToken;	// IMP=0x00000001001ddd5c
- (void)clearLegacyKeyValueServerChangeTokens;	// IMP=0x00000001001ddd4c
- (void)setKeyValueServerChangeToken:(id)arg1;	// IMP=0x00000001001ddd3c
- (id)keyValueServerChangeToken;	// IMP=0x00000001001ddcd8
- (void)setLastMetricsUploadFailureReportedOnDate:(id)arg1;	// IMP=0x00000001001ddcc8
- (id)lastMetricsUploadFailureReportedOnDate;	// IMP=0x00000001001ddcbc
- (void)setLastMetricsUploadDate:(id)arg1;	// IMP=0x00000001001ddcac
- (id)lastMetricsUploadDate;	// IMP=0x00000001001ddca0
- (void)setLastSyncVerificationDate:(id)arg1;	// IMP=0x00000001001ddc90
- (id)lastSyncVerificationDate;	// IMP=0x00000001001ddc84
- (void)setLastKnownProxyStreamId:(id)arg1;	// IMP=0x00000001001ddc74
- (id)lastKnownProxyStreamId;	// IMP=0x00000001001ddc10
- (void)setRedirect:(id)arg1 forServerURLString:(id)arg2;	// IMP=0x00000001001ddb10
- (id)redirectForServerURLString:(id)arg1;	// IMP=0x00000001001dda2c
- (id)productTypePrefix;	// IMP=0x00000001001dd9c8
- (id)serverOverride;	// IMP=0x00000001001dd964
- (_Bool)ignoreLocationWiFiStatus;	// IMP=0x00000001001dd908
- (void)setCountryCode:(id)arg1;	// IMP=0x00000001001dd900
- (id)countryCode;	// IMP=0x00000001001dd8fc
- (void)setOutputVoice:(id)arg1;	// IMP=0x00000001001dd824
- (id)outputVoice;	// IMP=0x00000001001dd820
- (void)setLanguageCode:(id)arg1;	// IMP=0x00000001001dd748
- (id)languageCode;	// IMP=0x00000001001dd744
- (double)serverTimeoutInterval;	// IMP=0x00000001001dd6e0
- (_Bool)statisticsRecordingEnabled;	// IMP=0x00000001001dd694
- (void)setActiveAccountIdentifier:(id)arg1;	// IMP=0x00000001001dd684
- (id)accountIdentifiers;	// IMP=0x00000001001dd630
- (id)activeAccountIdentifier;	// IMP=0x00000001001dd624
- (void)setAccountInfo:(id)arg1 forIdentifier:(id)arg2;	// IMP=0x00000001001dd52c
- (id)accountInfoForIdentifier:(id)arg1;	// IMP=0x00000001001dd4b8
- (void)synchronize;	// IMP=0x00000001001dd398
- (id)init;	// IMP=0x00000001001dd334

@end

