//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "ADCompanionServiceMessageHandler-Protocol.h"

@class NSHashTable, NSString;
@protocol OS_dispatch_queue;

@interface ADRequestLifecycleObserver : NSObject <ADCompanionServiceMessageHandler>
{
    struct os_unfair_lock_s _listenersLock;	// 8 = 0x8
    NSHashTable *_listeners;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_queue;	// 24 = 0x18
}

+ (id)sharedObserver;	// IMP=0x0000000100188100
- (void).cxx_destruct;	// IMP=0x0000000100188f64
- (void)_enumerateListenersUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100188e8c
- (void)_removeListener:(id)arg1;	// IMP=0x0000000100188e28
- (void)_addListener:(id)arg1;	// IMP=0x0000000100188dcc
- (void)_handleMessage:(id)arg1 messageType:(id)arg2 fromDeviceWithIdentifier:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100188b54
- (void)handleMessage:(id)arg1 messageType:(id)arg2 fromDeviceWithIdentifier:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100188a0c
- (void)requestDidEndWithInfo:(id)arg1 fromOrigin:(long long)arg2 client:(id)arg3;	// IMP=0x000000010018878c
- (void)requestWasCancelledWithInfo:(id)arg1 origin:(long long)arg2 client:(id)arg3;	// IMP=0x000000010018850c
- (void)requestWillBeginWithInfo:(id)arg1 fromOrigin:(long long)arg2 client:(id)arg3;	// IMP=0x000000010018828c
- (void)removeListener:(id)arg1;	// IMP=0x0000000100188280
- (void)addListener:(id)arg1;	// IMP=0x0000000100188274
- (id)init;	// IMP=0x000000010018816c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

