//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface ADSyncSnapshot : NSObject
{
    NSMutableDictionary *_pluginCache;	// 8 = 0x8
    NSMutableDictionary *_appsCache;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_queue;	// 24 = 0x18
    NSObject<OS_dispatch_source> *_saveTimer;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x0000000100094ca4
- (void).cxx_destruct;	// IMP=0x0000000100096f68
- (void)_save;	// IMP=0x0000000100096958
- (void)pruneCacheWithCurrentSynapseInfo:(id)arg1;	// IMP=0x0000000100096888
- (_Bool)_pruneAppsCacheWithTruth:(id)arg1;	// IMP=0x0000000100096448
- (void)_readFromDisk;	// IMP=0x0000000100095c00
- (_Bool)shouldIgnoreSyncKey:(id)arg1;	// IMP=0x0000000100095b8c
- (void)deleteSavedSnapshots;	// IMP=0x0000000100095ab8
- (void)noteSendingChunk:(id)arg1;	// IMP=0x0000000100095828
- (void)_noteSendingPostGen:(id)arg1 validity:(id)arg2 key:(id)arg3 appMetaData:(id)arg4;	// IMP=0x000000010009550c
- (void)_scheduleSave;	// IMP=0x00000001000953a4
- (void)_cancelSaveTimer;	// IMP=0x0000000100095368
- (void)fetchSentAnchorsOnQueue:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010009523c
- (void)_fetchSentAnchorsOnQueue:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100094ee8
- (id)_storePath;	// IMP=0x0000000100094e94
- (id)init;	// IMP=0x0000000100094d40

@end

