//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/SASStartSpeech.h>

@interface SASStartSpeech (AFAdditions)
- (void)af_logDiagnostics;	// IMP=0x00000001001a7fe4
- (id)ad_deferredMetricsContext;	// IMP=0x000000010029e55c
- (void)ad_setADRecordingInfo:(id)arg1;	// IMP=0x000000010029e270
- (void)ad_setAFSpeechRequestOptions:(id)arg1;	// IMP=0x000000010029e138
- (void)ad_setAFSpeechEvent:(long long)arg1;	// IMP=0x000000010029e0f0
- (id)ad_languageModel;	// IMP=0x000000010029e0e8
@end

