//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/SASSpeechRecognized.h>

@interface SASSpeechRecognized (Analytics)
- (id)ad_endTime;	// IMP=0x0000000100186ad8
- (id)ad_trailingSilence;	// IMP=0x0000000100186a20
- (id)ad_speechEndTime;	// IMP=0x00000001001868f4
- (id)ad_leadingSilence;	// IMP=0x00000001001867cc
- (id)description;	// IMP=0x000000010029d5e8
@end

