//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/SASStartSpeechDictation.h>

@interface SASStartSpeechDictation (ADSAExtensions)
+ (id)ad_startSpeechDictationWithAFDictationOptions:(id)arg1;	// IMP=0x000000010029d920
- (id)ad_deferredMetricsContext;	// IMP=0x000000010029dd74
- (id)ad_languageModel;	// IMP=0x000000010029d8a0
@end

