//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIApplication.h>

#import "UIApplicationDelegate-Protocol.h"

@class NSString, UIWindow;

@interface Application : UIApplication <UIApplicationDelegate>
{
}

- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;	// IMP=0x000000010000cd6c
- (void)applicationDidEnterBackground:(id)arg1;	// IMP=0x000000010000cd24
- (void)applicationDidBecomeActive:(id)arg1;	// IMP=0x000000010000ccdc
- (void)applicationWillResignActive:(id)arg1;	// IMP=0x000000010000cc94
- (void)applicationDidFinishLaunching:(id)arg1;	// IMP=0x000000010000cc10
- (void)applicationWillTerminate:(id)arg1;	// IMP=0x000000010000cc0c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

