//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SATVLegalPresentationWarrantyDelegate;

@interface SATVLegalPresentation : NSObject
{
    id <SATVLegalPresentationWarrantyDelegate> _warrantyDelegate;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x000000010000cdcc
- (void).cxx_destruct;	// IMP=0x000000010000d568
@property(nonatomic) __weak id <SATVLegalPresentationWarrantyDelegate> warrantyDelegate; // @synthesize warrantyDelegate=_warrantyDelegate;
- (void)_warrantyAccepted;	// IMP=0x000000010000d4f0
- (void)displayWarrantyChallengeWithTerms:(id)arg1 navigationController:(id)arg2;	// IMP=0x000000010000d044
- (_Bool)needsWarrantyChallenge;	// IMP=0x000000010000cfe8
- (void)displayLegalNoticeWithTitle:(id)arg1 terms:(id)arg2 navigationController:(id)arg3;	// IMP=0x000000010000ce38

@end

