//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSetupKit/TVSKViewController.h>

#import "SATVConsentViewControllerDataSource-Protocol.h"
#import "SATVConsentViewControllerDelegate-Protocol.h"

@class NSString, OBPrivacyLinkController;

@interface SATVLocationServicesViewController : TVSKViewController <SATVConsentViewControllerDelegate, SATVConsentViewControllerDataSource>
{
    CDUnknownBlockType _completionHandler;	// 8 = 0x8
    OBPrivacyLinkController *_privacyLink;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010004fe10
@property(retain, nonatomic) OBPrivacyLinkController *privacyLink; // @synthesize privacyLink=_privacyLink;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (void)_enableLocationServices:(_Bool)arg1;	// IMP=0x000000010004fd4c
- (void)consentViewControllerDidSelectDissent:(id)arg1;	// IMP=0x000000010004fcc8
- (void)consentViewControllerDidSelectConsent:(id)arg1;	// IMP=0x000000010004fc44
- (id)footerButtonViewForConsentViewController:(id)arg1;	// IMP=0x000000010004fc2c
- (id)dissentButtonTextForConsentViewController:(id)arg1;	// IMP=0x000000010004fbac
- (id)consentButtonTextForConsentViewController:(id)arg1;	// IMP=0x000000010004fb2c
- (id)subtitleTextForConsentViewController:(id)arg1;	// IMP=0x000000010004faac
- (id)titleTextForConsentViewController:(id)arg1;	// IMP=0x000000010004fa2c
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x000000010004f9c0
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010004f968
- (void)viewDidLoad;	// IMP=0x000000010004f860
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010004f7ac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

