//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, TVCSTapToSetupDeviceInfo;

@interface SATVExpressTapToSetupDataSource : NSObject
{
    NSString *_deviceClass;	// 8 = 0x8
    NSArray *_items;	// 16 = 0x10
    TVCSTapToSetupDeviceInfo *_tapToSetupDeviceInfo;	// 24 = 0x18
}

+ (id)new;	// IMP=0x00000001000310f8
- (void).cxx_destruct;	// IMP=0x0000000100031928
@property(readonly, nonatomic) TVCSTapToSetupDeviceInfo *tapToSetupDeviceInfo; // @synthesize tapToSetupDeviceInfo=_tapToSetupDeviceInfo;
@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
- (void)_updateItemsWithTapToSetupDeviceInfo:(id)arg1;	// IMP=0x00000001000315a4
@property(readonly, nonatomic) unsigned long long itemTypes;
- (id)itemAtIndex:(unsigned long long)arg1;	// IMP=0x00000001000313f0
@property(readonly, copy, nonatomic) NSString *deviceClass; // @synthesize deviceClass=_deviceClass;
@property(readonly, copy, nonatomic) NSString *deviceName;
- (id)initWithTapToSetupDeviceInfo:(id)arg1;	// IMP=0x0000000100031154
- (id)init;	// IMP=0x000000010003111c

@end

