//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "AMSDeviceLanguageContract-Protocol.h"
#import "BatterySaverWatcherDelegate-Protocol.h"

@class AMSBagValue, BatterySaverWatcher, NSCountedSet, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString;
@protocol AMSMescalBagContract, AMSMetricsBagContract, OS_dispatch_queue, OS_dispatch_source, OS_xpc_object;

@interface Daemon : NSObject <AMSDeviceLanguageContract, BatterySaverWatcherDelegate>
{
    _Bool _aliveForOperationQueues;	// 8 = 0x8
    NSMutableDictionary *_backgroundTaskObservers;	// 16 = 0x10
    NSMutableArray *_bagTimers;	// 24 = 0x18
    BatterySaverWatcher *_batterySaverWatcher;	// 32 = 0x20
    NSMutableDictionary *_cachedObjects;	// 40 = 0x28
    long long _dialogCount;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 56 = 0x38
    NSObject<OS_dispatch_source> *_jetsamSource;	// 64 = 0x40
    NSCountedSet *_keepAliveTransactions;	// 72 = 0x48
    NSMutableDictionary *_keepAliveTransactionStore;	// 80 = 0x50
    NSMutableSet *_keepAliveOperationQueues;	// 88 = 0x58
    NSObject<OS_dispatch_queue> *_notifyQueue;	// 96 = 0x60
    int _notifyToken;	// 104 = 0x68
    NSObject<OS_xpc_object> *_satisfiedWakeRequests;	// 112 = 0x70
}

+ (id)daemon;	// IMP=0x000000010016e4d0
- (void)_warmUpSharedURLCache;	// IMP=0x0000000100172bb8
- (void)_setGlobalState;	// IMP=0x0000000100172a8c
- (void)_reloadWiFiManager;	// IMP=0x0000000100172a28
- (void)_reloadOperationKeepAliveTransaction;	// IMP=0x00000001001728c8
- (void)_observeNotifications;	// IMP=0x00000001001712ac
- (void)_initBackgroundTaskAgent;	// IMP=0x0000000100170f10
- (void)_handleWakeWithName:(const char *)arg1 job:(id)arg2;	// IMP=0x0000000100170ae8
- (void)_expireCachedObjectForKey:(id)arg1;	// IMP=0x0000000100170a88
- (void)_operationCountChanged:(id)arg1;	// IMP=0x0000000100170a20
- (void)_networkUsageStateChangeNotification:(id)arg1;	// IMP=0x000000010017095c
- (void)_getShowingDialogWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00000001001708ac
- (void)batterySaverWatcherDidChangeState:(id)arg1;	// IMP=0x0000000100170628
@property(readonly, nonatomic) AMSBagValue *trustedDomains;
@property(readonly, nonatomic) AMSBagValue *changeLanguageURL;
- (void)start;	// IMP=0x000000010016f838
- (void)removeKeepAliveOperationQueue:(id)arg1;	// IMP=0x000000010016f774
- (void)removeCachedObjectForKey:(id)arg1;	// IMP=0x000000010016f704
- (void)removeBackgroundTaskObserver:(id)arg1;	// IMP=0x000000010016f574
- (void)releaseKeepAliveAssertion:(id)arg1;	// IMP=0x000000010016f494
- (void)takeKeepAliveAssertion:(id)arg1;	// IMP=0x000000010016f3b0
- (void)keepAliveWithAssertion:(id)arg1 block:(CDUnknownBlockType)arg2;	// IMP=0x000000010016f2b0
- (void)endShowingDialog;	// IMP=0x000000010016f21c
- (void)cancelBackgroundTaskWithIdentifier:(id)arg1;	// IMP=0x000000010016f074
- (void)cacheObject:(id)arg1 withKey:(id)arg2 expirationInterval:(double)arg3;	// IMP=0x000000010016ee3c
- (id)cachedObjectForKey:(id)arg1;	// IMP=0x000000010016ed08
- (void)beginShowingDialog;	// IMP=0x000000010016ec78
- (id)addObserverForBackgroundTaskWithIdentifierPrefix:(id)arg1 withBlock:(CDUnknownBlockType)arg2;	// IMP=0x000000010016e950
- (void)addKeepAliveOperationQueue:(id)arg1;	// IMP=0x000000010016e860
- (void)addBackgroundTaskWithRequest:(id)arg1;	// IMP=0x000000010016e568
- (void)dealloc;	// IMP=0x000000010016e3b0
- (id)init;	// IMP=0x000000010016e208

// Remaining properties
@property(readonly, nonatomic) AMSBagValue *TFOSamplingPercentage;
@property(readonly, nonatomic) AMSBagValue *TFOSamplingSessionDuration;
@property(readonly, nonatomic) AMSBagValue *TLSSamplingPercentage;
@property(readonly, nonatomic) AMSBagValue *TLSSamplingSessionDuration;
@property(readonly, nonatomic) AMSBagValue *apsAllowedProductTypes;
@property(readonly, nonatomic) AMSBagValue *apsEnabledPatterns;
@property(readonly, nonatomic) AMSBagValue *apsSamplingPercent;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) AMSBagValue *guidRegexes;
@property(readonly, nonatomic) AMSBagValue *guidSchemes;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) id <AMSMescalBagContract> mescalContract;
@property(readonly, nonatomic) id <AMSMetricsBagContract> metricsContract;
@property(readonly, nonatomic) AMSBagValue *metricsURL;
@property(readonly, nonatomic) AMSBagValue *storefrontSuffix;
@property(readonly) Class superclass;

@end

