//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <iTunesStore/ISOperation.h>

@class MicroPaymentQueueResponse, NSArray, NSDate, StoreKitClientIdentity;

@interface LoadMicroPaymentQueuesOperation : ISOperation
{
    StoreKitClientIdentity *_clientIdentity;	// 96 = 0x60
    NSDate *_lastQueueCheckDate;	// 104 = 0x68
    long long _reason;	// 112 = 0x70
    MicroPaymentQueueResponse *_paymentsResponse;	// 120 = 0x78
    NSArray *_userDSIDs;	// 128 = 0x80
}

- (void).cxx_destruct;	// IMP=0x000000010008b510
@property(copy) NSArray *userDSIDs; // @synthesize userDSIDs=_userDSIDs;
@property long long reason; // @synthesize reason=_reason;
@property(retain) MicroPaymentQueueResponse *paymentsResponse; // @synthesize paymentsResponse=_paymentsResponse;
- (id)_URLBagContext;	// IMP=0x000000010008b450
- (_Bool)_shouldCheckAutoRenewQueue;	// IMP=0x000000010008b35c
- (_Bool)_appendToResponse:(id)arg1 usingOperation:(id)arg2 error:(id *)arg3;	// IMP=0x000000010008af0c
- (_Bool)_appendNormalQueueToResponse:(id)arg1 error:(id *)arg2;	// IMP=0x000000010008ad88
- (_Bool)_appendAutoRenewQueueToResponse:(id)arg1 error:(id *)arg2;	// IMP=0x000000010008ac04
- (void)run;	// IMP=0x000000010008a490
@property(copy) NSDate *lastQueueCheckDate;
@property(copy) StoreKitClientIdentity *clientIdentity;

@end

