//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NESMSession.h"

@class NSMutableArray, NWInterface;

@interface NESMIKEv2VPNFallbackSession : NESMSession
{
    _Bool _fallbackIsActive;	// 8 = 0x8
    int _sleepAckCount;	// 12 = 0xc
    NSMutableArray *_childSessions;	// 16 = 0x10
    unsigned long long _predicatedInterfaceIndex;	// 24 = 0x18
    unsigned long long _advisoryInterfaceIndex;	// 32 = 0x20
    NWInterface *_primaryCellularInterface;	// 40 = 0x28
    unsigned long long _cellularIfFlags;	// 48 = 0x30
    long long _installState;	// 56 = 0x38
    NSMutableArray *_configurationOperationArray;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x0000000100087cc8
@property(retain) NSMutableArray *configurationOperationArray; // @synthesize configurationOperationArray=_configurationOperationArray;
@property _Bool fallbackIsActive; // @synthesize fallbackIsActive=_fallbackIsActive;
@property int sleepAckCount; // @synthesize sleepAckCount=_sleepAckCount;
@property long long installState; // @synthesize installState=_installState;
@property unsigned long long cellularIfFlags; // @synthesize cellularIfFlags=_cellularIfFlags;
@property(retain) NWInterface *primaryCellularInterface; // @synthesize primaryCellularInterface=_primaryCellularInterface;
@property unsigned long long advisoryInterfaceIndex; // @synthesize advisoryInterfaceIndex=_advisoryInterfaceIndex;
@property unsigned long long predicatedInterfaceIndex; // @synthesize predicatedInterfaceIndex=_predicatedInterfaceIndex;
@property(retain) NSMutableArray *childSessions; // @synthesize childSessions=_childSessions;
- (void)startFallbackSession;	// IMP=0x0000000100087690
- (void)resetFallbackInterfaceOnServer;	// IMP=0x0000000100087028
- (void)handleClearConfigurationResult:(id)arg1;	// IMP=0x0000000100086d58
- (void)handleSetConfigurationResult:(id)arg1 tunnelInterfaceName:(id)arg2;	// IMP=0x0000000100086af4
- (_Bool)shouldDisableInitialContactForSession:(id)arg1;	// IMP=0x00000001000868a8
- (void)handleNetworkConfigurationChange:(long long)arg1;	// IMP=0x00000001000865b0
- (void)uninstall;	// IMP=0x0000000100086124
- (void)requestUninstall:(id)arg1;	// IMP=0x0000000100085e10
- (void)requestUninstall;	// IMP=0x00000001000857e4
- (void)installPended;	// IMP=0x0000000100085368
- (void)install;	// IMP=0x0000000100084c14
- (void)registerSession:(id)arg1 fromClient:(id)arg2 fromSession:(id)arg3;	// IMP=0x00000001000846ac
- (void)requestInstallForSession:(id)arg1 exclusive:(_Bool)arg2;	// IMP=0x000000010008437c
- (void)requestInstall;	// IMP=0x0000000100083c54
- (void)setLastDisconnectErrorFromSession:(id)arg1 lastDisconnectError:(id)arg2;	// IMP=0x0000000100083a40
- (void)setLastStopReasonFromSession:(id)arg1 lastStopReason:(int)arg2;	// IMP=0x0000000100083854
- (void)setStatusFromSession:(id)arg1 andStatus:(int)arg2;	// IMP=0x0000000100083440
- (void)setStatus:(int)arg1;	// IMP=0x00000001000831d8
- (int)parentStatus:(int)arg1 secondStatus:(int)arg2;	// IMP=0x0000000100082fcc
- (void)prepareNetwork:(id)arg1;	// IMP=0x0000000100082a24
- (void)handleNetworkDetectionNotification:(int)arg1;	// IMP=0x0000000100082728
- (void)handleChangeEventForInterface:(id)arg1 newFlags:(unsigned long long)arg2 previousFlags:(unsigned long long)arg3;	// IMP=0x000000010008251c
- (id)copyExtendedStatus;	// IMP=0x0000000100081e38
- (id)copyStatistics;	// IMP=0x00000001000817e4
- (void)handleGetInfoMessage:(id)arg1 withType:(int)arg2;	// IMP=0x0000000100081714
- (_Bool)handleUpdateConfiguration:(id)arg1;	// IMP=0x0000000100080cc8
- (void)ackSleep:(id)arg1;	// IMP=0x0000000100080bb0
- (void)handleUserSwitch;	// IMP=0x00000001000808d8
- (void)handleUserLogout;	// IMP=0x0000000100080600
- (void)handleSleepTime:(double)arg1;	// IMP=0x000000010008030c
- (_Bool)handleSleep;	// IMP=0x000000010007ffe8
- (void)handleWakeup;	// IMP=0x000000010007fd10
- (void)handleStopMessageWithReason:(int)arg1;	// IMP=0x000000010007f9f4
- (void)handleStartMessage:(id)arg1;	// IMP=0x000000010007f7ac
- (void)handleInitializeState;	// IMP=0x000000010007f4b4
- (id)tunnelInstallState2String:(long long)arg1;	// IMP=0x000000010007f454
- (id)tunnelSessionType2String:(id)arg1;	// IMP=0x000000010007f314
- (int)type;	// IMP=0x000000010007f30c
- (void)dealloc;	// IMP=0x000000010007f294
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010007eb14
- (_Bool)startMonitoringPrimaryCellularInterface;	// IMP=0x000000010007e958
- (void)handleChangeEventForFallback:(_Bool)arg1;	// IMP=0x000000010007e790
- (id)initWithConfiguration:(id)arg1 andServer:(id)arg2 andProtocol:(id)arg3 andSessionType:(int)arg4;	// IMP=0x000000010007e348

@end

