//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface GKAcceptedInviteManager : NSObject
{
    NSMutableArray *_acceptedMultiplayerInvites;	// 8 = 0x8
    NSMutableArray *_acceptedTurnBased;	// 16 = 0x10
    NSMutableArray *_acceptedTournamentInvites;	// 24 = 0x18
}

+ (id)syncQueue;	// IMP=0x00000001000c6a00
@property(retain) NSMutableArray *acceptedTournamentInvites; // @synthesize acceptedTournamentInvites=_acceptedTournamentInvites;
@property(retain) NSMutableArray *acceptedTurnBased; // @synthesize acceptedTurnBased=_acceptedTurnBased;
@property(retain) NSMutableArray *acceptedMultiplayerInvites; // @synthesize acceptedMultiplayerInvites=_acceptedMultiplayerInvites;
- (id)description;	// IMP=0x00000001000c8478
- (id)tournamentInviteForGame:(id)arg1;	// IMP=0x00000001000c82b8
- (id)turnBasedInviteForGameDescriptor:(id)arg1;	// IMP=0x00000001000c8118
- (id)turnBasedInviteForGame:(id)arg1;	// IMP=0x00000001000c7fa4
- (id)multiplayerInviteForGameDescriptor:(id)arg1;	// IMP=0x00000001000c7d18
- (id)multiplayerInviteForGame:(id)arg1;	// IMP=0x00000001000c7ba4
- (id)removeAndReturnTurnBasedInviteWithMatchID:(id)arg1;	// IMP=0x00000001000c79e0
- (id)removeAndReturnInviteWithSessionToken:(id)arg1;	// IMP=0x00000001000c781c
- (void)addTournamentInvite:(id)arg1;	// IMP=0x00000001000c76c4
- (void)addTurnBasedEvent:(id)arg1;	// IMP=0x00000001000c756c
- (void)addMultiplayerInvite:(id)arg1;	// IMP=0x00000001000c7414
- (id)_fetchAndRemoveBulletinFromArray:(id)arg1 passingTest:(CDUnknownBlockType)arg2;	// IMP=0x00000001000c7118
- (void)_insertBulletin:(id)arg1 atFrontOfArray:(id)arg2;	// IMP=0x00000001000c6f78
- (void)_addBulletin:(id)arg1 toArray:(id)arg2;	// IMP=0x00000001000c6ddc
- (void)performSync:(CDUnknownBlockType)arg1;	// IMP=0x00000001000c6b88
- (void)dealloc;	// IMP=0x00000001000c69a8
- (id)init;	// IMP=0x00000001000c6938

@end

