//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface GKBadgeController : NSObject
{
    NSMutableDictionary *_badgeDictionaries[4];	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_syncQueue;	// 40 = 0x28
    _Bool _dirty;	// 48 = 0x30
}

+ (id)sharedController;	// IMP=0x0000000100106bd4
- (void)registerBadgePermissionForBundleID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100108a64
- (void)unbadgeAllApplications;	// IMP=0x000000010010880c
- (void)badgeAllApplications;	// IMP=0x000000010010857c
- (void)setBadgeCount:(unsigned long long)arg1 forBundleID:(id)arg2 badgeType:(unsigned long long)arg3;	// IMP=0x0000000100108138
- (unsigned long long)_totalBadgeCountForBundleID:(id)arg1;	// IMP=0x0000000100107fc4
- (unsigned long long)badgeCountForBundleID:(id)arg1 badgeType:(unsigned long long)arg2;	// IMP=0x0000000100107dd4
- (unsigned long long)_badgeCountForBundleID:(id)arg1 badgeType:(unsigned long long)arg2;	// IMP=0x0000000100107c70
- (id)_dictionaryForBadgeType:(unsigned long long)arg1;	// IMP=0x0000000100107b3c
- (void)badgeBundleID:(id)arg1 badgeCount:(unsigned long long)arg2;	// IMP=0x0000000100107828
- (void)badgeApplicationWithBundleID:(id)arg1 badgeCount:(unsigned long long)arg2;	// IMP=0x0000000100107398
- (_Bool)isBadgingEnabledForBundleID:(id)arg1;	// IMP=0x000000010010732c
- (void)synchronize;	// IMP=0x0000000100106d8c
- (id)_plistKeyForBadgeType:(unsigned long long)arg1;	// IMP=0x0000000100106d54
- (void)dealloc;	// IMP=0x0000000100106cf8
- (id)init;	// IMP=0x0000000100106c8c
- (id)_badgeCountURL;	// IMP=0x0000000100106c38

@end

