//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "GKClientProtocol-Protocol.h"
#import "_GKStateMachineDelegate-Protocol.h"

@class GKDatabaseConnection, GKEntitlements, GKEventTuple, GKGameInternal, GKInviteSession, GKMatchResponse, GKResourceManager, GKThreadsafeDictionary, NSDate, NSDictionary, NSLocale, NSMapTable, NSMutableDictionary, NSMutableSet, NSNumber, NSString, NSXPCConnection, _GKStateMachine;
@protocol GKUIViewService, OS_dispatch_queue;

@interface GKClientProxy : NSObject <GKClientProtocol, _GKStateMachineDelegate>
{
    _Bool _deniedProductionEnvironment;	// 8 = 0x8
    _Bool _productionSigned;	// 9 = 0x9
    _Bool _installed;	// 10 = 0xa
    _Bool _supportsMultipleActivePlayers;	// 11 = 0xb
    _Bool _isOcelot;	// 12 = 0xc
    unsigned char _achievementsRateLimitedCurrentState;	// 13 = 0xd
    unsigned char _scoresRateLimitedCurrentState;	// 14 = 0xe
    _Bool _initialized;	// 15 = 0xf
    int _pid;	// 16 = 0x10
    unsigned int _applicationState;	// 20 = 0x14
    unsigned int _previousApplicationState;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_replyQueue;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_authQueue;	// 40 = 0x28
    NSXPCConnection *_connection;	// 48 = 0x30
    GKEntitlements *_entitlements;	// 56 = 0x38
    NSNumber *_adamID;	// 64 = 0x40
    NSNumber *_sandboxExtensionToken;	// 72 = 0x48
    NSNumber *_externalVersion;	// 80 = 0x50
    NSString *_bundleIdentifier;	// 88 = 0x58
    NSString *_bundleVersion;	// 96 = 0x60
    NSString *_bundleShortVersion;	// 104 = 0x68
    long long _environment;	// 112 = 0x70
    NSDate *_achievementsRateLimitingStartDate;	// 120 = 0x78
    long long _achievementsRateLimitingCurrentNumberOfRequests;	// 128 = 0x80
    NSDate *_scoresRateLimitingStartDate;	// 136 = 0x88
    long long _scoresRateLimitingCurrentNumberOfRequests;	// 144 = 0x90
    NSMutableDictionary *_alreadyCoalescingNetworkRequests;	// 152 = 0x98
    NSString *_language;	// 160 = 0xa0
    GKClientProxy<GKUIViewService> *_viewService;	// 168 = 0xa8
    GKGameInternal *_currentGame;	// 176 = 0xb0
    GKEventTuple *_launchEvent;	// 184 = 0xb8
    GKInviteSession *_inviteSession;	// 192 = 0xc0
    GKMatchResponse *_currentMatchResponse;	// 200 = 0xc8
    _GKStateMachine *_appInitStateMachine;	// 208 = 0xd0
    GKThreadsafeDictionary *_appSessions;	// 216 = 0xd8
    NSObject<OS_dispatch_queue> *_delayedRequestsQueue;	// 224 = 0xe0
    GKDatabaseConnection *_delayedRequestsDBConnection;	// 232 = 0xe8
    NSObject<OS_dispatch_queue> *_cacheQueue;	// 240 = 0xf0
    GKResourceManager *_resourceManager;	// 248 = 0xf8
    NSMutableSet *_pendingDataTypesForRefresh;	// 256 = 0x100
    NSMapTable *_extensionProxies;	// 264 = 0x108
    NSDictionary *_preferencesFromBag;	// 272 = 0x110
}

+ (id)syncQueue;	// IMP=0x00000001001473e0
+ (void)closeDatabaseFromManagedObjectContextForMOC:(id)arg1;	// IMP=0x000000010007dd14
+ (void)closeDatabaseFromManagedObjectContextForPlayer:(id)arg1;	// IMP=0x000000010007dcdc
+ (id)newManagedObjectContextForClient:(id)arg1 player:(id)arg2;	// IMP=0x000000010007dbac
+ (id)_newManagedObjectContextForPlayer:(id)arg1;	// IMP=0x000000010007d128
+ (id)cacheFileQueue;	// IMP=0x000000010007d0c0
+ (id)managedObjectModel;	// IMP=0x000000010007ce38
+ (void)removeAllCaches;	// IMP=0x000000010007c96c
+ (void)removeCacheForPlayer:(id)arg1;	// IMP=0x000000010007c378
+ (id)cacheFileURLForClient:(id)arg1 player:(id)arg2;	// IMP=0x000000010007c348
+ (id)cacheDirectoryURLForClient:(id)arg1 player:(id)arg2;	// IMP=0x000000010007bf6c
+ (id)cacheDirectoryForBundleID:(id)arg1 environment:(long long)arg2;	// IMP=0x000000010007befc
+ (id)_existingManagedObjectContextForPlayer:(id)arg1;	// IMP=0x000000010007bcb4
+ (id)contextKeyForPlayer:(id)arg1;	// IMP=0x000000010007bc84
+ (void)removeClient:(id)arg1;	// IMP=0x000000010014ae1c
+ (void)enumerateClientsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010014ad50
+ (id)clientsToBeEnumerated;	// IMP=0x000000010014ab2c
+ (id)clientForMatchmakingRID:(id)arg1;	// IMP=0x000000010014a964
+ (id)clientForInviteSessionToken:(id)arg1;	// IMP=0x000000010014a484
+ (id)foregroundClient;	// IMP=0x000000010014a320
+ (id)clientForBundleID:(id)arg1 pid:(int)arg2 createIfNecessary:(_Bool)arg3;	// IMP=0x000000010014a308
+ (id)clientForBundleID:(id)arg1 bundle:(id)arg2 pid:(int)arg3 createIfNecessary:(_Bool)arg4;	// IMP=0x00000001001496f0
+ (_Bool)isExtensionBundleID:(id)arg1;	// IMP=0x0000000100149564
+ (id)clientForProcessIdentifier:(int)arg1;	// IMP=0x00000001001494c4
+ (id)clientForBundleID:(id)arg1;	// IMP=0x00000001001494ac
+ (id)gameCenterClient;	// IMP=0x0000000100149488
+ (id)_clientLookup;	// IMP=0x000000010014940c
+ (id)factoryQueue;	// IMP=0x000000010014939c
+ (void)saveAppInitState:(id)arg1 forBundleID:(id)arg2 pid:(int)arg3;	// IMP=0x000000010014f334
+ (id)lastKnownAppInitStateForClientWithBundleID:(id)arg1 pid:(int)arg2;	// IMP=0x000000010014ee74
+ (void)authenticationDidChange;	// IMP=0x000000010014e898
+ (void)performDelayedRequestsForEnvironment:(long long)arg1;	// IMP=0x0000000100158394
+ (id)storeAndForwardDirectoryPathForEnvironment:(long long)arg1;	// IMP=0x0000000100156d68
- (void).cxx_destruct;	// IMP=0x0000000100149244
@property(copy, nonatomic) NSDictionary *preferencesFromBag; // @synthesize preferencesFromBag=_preferencesFromBag;
@property(retain, nonatomic) NSMapTable *extensionProxies; // @synthesize extensionProxies=_extensionProxies;
@property(retain, nonatomic) NSMutableSet *pendingDataTypesForRefresh; // @synthesize pendingDataTypesForRefresh=_pendingDataTypesForRefresh;
@property(retain, nonatomic) GKResourceManager *resourceManager; // @synthesize resourceManager=_resourceManager;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *cacheQueue; // @synthesize cacheQueue=_cacheQueue;
@property(retain, nonatomic) GKDatabaseConnection *delayedRequestsDBConnection; // @synthesize delayedRequestsDBConnection=_delayedRequestsDBConnection;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *delayedRequestsQueue; // @synthesize delayedRequestsQueue=_delayedRequestsQueue;
@property(retain, nonatomic) GKThreadsafeDictionary *appSessions; // @synthesize appSessions=_appSessions;
@property(retain) _GKStateMachine *appInitStateMachine; // @synthesize appInitStateMachine=_appInitStateMachine;
@property _Bool initialized; // @synthesize initialized=_initialized;
@property(retain) GKMatchResponse *currentMatchResponse; // @synthesize currentMatchResponse=_currentMatchResponse;
@property(retain) GKInviteSession *inviteSession; // @synthesize inviteSession=_inviteSession;
@property(retain, nonatomic) GKEventTuple *launchEvent; // @synthesize launchEvent=_launchEvent;
@property unsigned int previousApplicationState; // @synthesize previousApplicationState=_previousApplicationState;
@property unsigned int applicationState; // @synthesize applicationState=_applicationState;
@property(retain, nonatomic) GKGameInternal *currentGame; // @synthesize currentGame=_currentGame;
@property(nonatomic) __weak GKClientProxy<GKUIViewService> *viewService; // @synthesize viewService=_viewService;
@property(retain, nonatomic) NSString *language; // @synthesize language=_language;
@property(retain, nonatomic) NSMutableDictionary *alreadyCoalescingNetworkRequests; // @synthesize alreadyCoalescingNetworkRequests=_alreadyCoalescingNetworkRequests;
@property(nonatomic) unsigned char scoresRateLimitedCurrentState; // @synthesize scoresRateLimitedCurrentState=_scoresRateLimitedCurrentState;
@property(nonatomic) long long scoresRateLimitingCurrentNumberOfRequests; // @synthesize scoresRateLimitingCurrentNumberOfRequests=_scoresRateLimitingCurrentNumberOfRequests;
@property(retain, nonatomic) NSDate *scoresRateLimitingStartDate; // @synthesize scoresRateLimitingStartDate=_scoresRateLimitingStartDate;
@property(nonatomic) unsigned char achievementsRateLimitedCurrentState; // @synthesize achievementsRateLimitedCurrentState=_achievementsRateLimitedCurrentState;
@property(nonatomic) long long achievementsRateLimitingCurrentNumberOfRequests; // @synthesize achievementsRateLimitingCurrentNumberOfRequests=_achievementsRateLimitingCurrentNumberOfRequests;
@property(retain, nonatomic) NSDate *achievementsRateLimitingStartDate; // @synthesize achievementsRateLimitingStartDate=_achievementsRateLimitingStartDate;
@property _Bool isOcelot; // @synthesize isOcelot=_isOcelot;
@property(nonatomic) _Bool supportsMultipleActivePlayers; // @synthesize supportsMultipleActivePlayers=_supportsMultipleActivePlayers;
@property(nonatomic) _Bool installed; // @synthesize installed=_installed;
@property(nonatomic) _Bool productionSigned; // @synthesize productionSigned=_productionSigned;
@property(nonatomic) _Bool deniedProductionEnvironment; // @synthesize deniedProductionEnvironment=_deniedProductionEnvironment;
@property(nonatomic) long long environment; // @synthesize environment=_environment;
@property(retain, nonatomic) NSString *bundleShortVersion; // @synthesize bundleShortVersion=_bundleShortVersion;
@property(retain, nonatomic) NSString *bundleVersion; // @synthesize bundleVersion=_bundleVersion;
@property(retain, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(retain, nonatomic) NSNumber *externalVersion; // @synthesize externalVersion=_externalVersion;
@property(retain, nonatomic) NSNumber *sandboxExtensionToken; // @synthesize sandboxExtensionToken=_sandboxExtensionToken;
@property(retain, nonatomic) NSNumber *adamID; // @synthesize adamID=_adamID;
@property(retain) GKEntitlements *entitlements; // @synthesize entitlements=_entitlements;
@property(nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(nonatomic) int pid; // @synthesize pid=_pid;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *authQueue; // @synthesize authQueue=_authQueue;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *replyQueue; // @synthesize replyQueue=_replyQueue;
- (void)deleteInviteSession;	// IMP=0x0000000100148cd4
- (void)cancelInvitationForSession:(id)arg1 playerID:(id)arg2 pushTokens:(id)arg3 handler:(CDUnknownBlockType)arg4;	// IMP=0x0000000100148728
- (_Bool)processMatchResponse:(id)arg1;	// IMP=0x0000000100147c3c
- (void)checkMatchStatus;	// IMP=0x0000000100147684
- (void)performAsync:(CDUnknownBlockType)arg1;	// IMP=0x0000000100147628
- (void)performSync:(CDUnknownBlockType)arg1;	// IMP=0x0000000100147450
- (void)setLaunchEvent:(unsigned long long)arg1 withContext:(id)arg2;	// IMP=0x0000000100147154
- (void)updatePreferencesFromBag:(id)arg1;	// IMP=0x00000001001470f4
- (void)setExtensionProxy:(id)arg1 forBundleID:(id)arg2;	// IMP=0x0000000100146fd4
- (_Bool)isExtension;	// IMP=0x0000000100146fcc
- (_Bool)isUIService;	// IMP=0x0000000100146fc4
- (_Bool)isGameCenter;	// IMP=0x0000000100146f6c
@property(readonly, nonatomic) NSLocale *locale; // @dynamic locale;
@property(readonly, nonatomic) NSDictionary *gameDescriptor;
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100146ab8
@property(readonly) unsigned long long hash;
@property(readonly, copy) NSString *description;
- (void)resetCache:(id)arg1;	// IMP=0x0000000100146958
- (void)_setupCache;	// IMP=0x0000000100146954
- (id)credentialForPlayer:(id)arg1;	// IMP=0x00000001001467e0
- (id)transportWithCredential:(id)arg1;	// IMP=0x000000010014671c
- (void)dealloc;	// IMP=0x0000000100146628
- (void)updateIfRecentlyInstalled;	// IMP=0x0000000100146238
- (id)initWithBundleIdentifier:(id)arg1 bundleOrNil:(id)arg2 pid:(int)arg3;	// IMP=0x0000000100145be4
- (void)initializeInitializationStateMachine;	// IMP=0x0000000100145a78
- (void)invalidateStoreFrontDependentObjects;	// IMP=0x000000010007ced8
- (id)transactionGroupIfCacheExistsForPlayer:(id)arg1;	// IMP=0x000000010007be78
- (id)transactionGroupForPlayer:(id)arg1;	// IMP=0x000000010007be14
- (id)_managedObjectContextForPlayer:(id)arg1;	// IMP=0x000000010007bcf8
- (void)handleCloudKitShareMetadata:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010014e584
- (oneway void)resetLoginCancelCount;	// IMP=0x000000010014e2e0
- (oneway void)loadRemoteImageDataForURL:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010014e240
- (oneway void)localizedMessageFromDictionary:(id)arg1 forBundleID:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x000000010014e100
- (oneway void)getAuthenticatedPlayerIDWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010014dfc4
- (oneway void)getAccountNameWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010014dd44
- (oneway void)getAuthenticatedLocalPlayersWithStatus:(unsigned long long)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x000000010014cfb0
- (oneway void)getGamedFiredUpWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010014cd60
- (oneway void)getAuthenticatedPlayerInfo:(CDUnknownBlockType)arg1;	// IMP=0x000000010014ca1c
- (oneway void)getPrivateServicesForPID:(int)arg1 localPlayer:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010014c54c
- (oneway void)getServicesForPID:(int)arg1 localPlayer:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010014bf74
- (oneway void)getPrivateServicesWithTransport:(id)arg1 forClient:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010014b99c
- (oneway void)getServicesWithTransport:(id)arg1 forClient:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010014b2ac
- (oneway void)setTestGame:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010014b298
- (oneway void)setHostPID:(int)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010014b284
- (id)serviceForClass:(Class)arg1 transport:(id)arg2 client:(id)arg3 credential:(id)arg4;	// IMP=0x000000010014afd8
- (void)didEnterForeground;	// IMP=0x000000010014f9c0
- (void)updateAppInitState;	// IMP=0x000000010014f8e0
- (id)verifyAuthorized;	// IMP=0x000000010014ed40
- (id)appInitState;	// IMP=0x000000010014ed30
- (_Bool)setAppInitState:(id)arg1;	// IMP=0x000000010014ed20
- (void)stateDidChange;	// IMP=0x000000010014ec94
- (id)missingTransitionFromState:(id)arg1 toState:(id)arg2;	// IMP=0x000000010014eb50
- (void)sendAuthenticationDidChangeNotificationWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010014e8c8
- (void)bgInitializeWithCredential:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001001568d0
- (void)initializeWithCredential:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100156324
- (void)removeAppSessionForPlayer:(id)arg1;	// IMP=0x0000000100156314
- (id)appSessionForPlayer:(id)arg1;	// IMP=0x000000010015628c
- (void)addAppSession:(id)arg1 forCredential:(id)arg2;	// IMP=0x0000000100156160
- (void)backgroundWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001001559cc
- (void)terminateWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100155238
- (oneway void)setLogBits:(int)arg1;	// IMP=0x0000000100154fbc
- (oneway void)authenticatedPlayersDidChange:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00000001001548bc
- (oneway void)completedOptimisticAuthenticationWithResponse:(id)arg1 error:(id)arg2;	// IMP=0x0000000100154810
- (oneway void)setCurrentGame:(id)arg1 serverEnvironment:(long long)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010015438c
- (oneway void)getPreferenceForKey:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00000001001542ec
- (oneway void)setPreferencesValues:(id)arg1;	// IMP=0x0000000100154180
- (oneway void)refreshPendingDataTypes;	// IMP=0x000000010015404c
- (oneway void)refreshContentsForDataType:(unsigned int)arg1 userInfo:(id)arg2;	// IMP=0x0000000100153a7c
- (oneway void)setBadgeCount:(unsigned long long)arg1 forType:(unsigned long long)arg2;	// IMP=0x00000001001538c0
- (oneway void)session:(id)arg1 didReceiveMessage:(id)arg2 withData:(id)arg3 fromPlayer:(id)arg4;	// IMP=0x0000000100153694
- (oneway void)session:(id)arg1 didReceiveData:(id)arg2 fromPlayer:(id)arg3;	// IMP=0x0000000100153484
- (oneway void)session:(id)arg1 player:(id)arg2 didSaveData:(id)arg3;	// IMP=0x0000000100153274
- (oneway void)session:(id)arg1 player:(id)arg2 didChangeConnectionState:(long long)arg3;	// IMP=0x0000000100153078
- (oneway void)session:(id)arg1 removedPlayer:(id)arg2;	// IMP=0x0000000100152e8c
- (oneway void)session:(id)arg1 addedPlayer:(id)arg2;	// IMP=0x0000000100152ca0
- (oneway void)localPlayerAcceptedCustomTournamentInvite;	// IMP=0x0000000100152a7c
- (oneway void)didReceiveData:(id)arg1 reliably:(_Bool)arg2 forRecipients:(id)arg3 fromSender:(id)arg4;	// IMP=0x0000000100152864
- (oneway void)didDisconnectFromParticipantWithID:(id)arg1;	// IMP=0x0000000100152694
- (oneway void)didConnectToParticipantWithID:(id)arg1;	// IMP=0x00000001001524c4
- (oneway void)relayPushNotification:(id)arg1;	// IMP=0x0000000100152218
- (oneway void)cancelGameInvite:(id)arg1;	// IMP=0x0000000100151f6c
- (oneway void)declineInviteWithNotification:(id)arg1;	// IMP=0x0000000100151cc0
- (oneway void)acceptInviteWithNotification:(id)arg1;	// IMP=0x0000000100151a14
- (oneway void)acceptMultiplayerGameInvite;	// IMP=0x00000001001517ec
- (oneway void)fetchTurnBasedData;	// IMP=0x0000000100151624
- (oneway void)achievementSelected:(id)arg1;	// IMP=0x0000000100151454
- (oneway void)scoreSelected:(id)arg1;	// IMP=0x0000000100151284
- (oneway void)challengeCompleted:(id)arg1;	// IMP=0x0000000100151048
- (oneway void)challengeReceived:(id)arg1;	// IMP=0x0000000100150e78
- (oneway void)completedChallengeSelected:(id)arg1;	// IMP=0x0000000100150ca8
- (oneway void)receivedChallengeSelected:(id)arg1;	// IMP=0x0000000100150ad8
- (oneway void)friendRequestSelected:(id)arg1;	// IMP=0x00000001001508c8
- (oneway void)respondedToNearbyInvite:(id)arg1;	// IMP=0x00000001001506f8
- (oneway void)resetNetworkActivity;	// IMP=0x0000000100150554
- (oneway void)endNetworkActivity;	// IMP=0x00000001001503b0
- (oneway void)beginNetworkActivity;	// IMP=0x000000010015020c
- (oneway void)requestSandboxExtension:(CDUnknownBlockType)arg1;	// IMP=0x000000010014ffe0
- (void)performDelayedRequestsForCredential:(id)arg1;	// IMP=0x00000001001599a8
- (void)performDelayedRequestsForEnvironment:(long long)arg1;	// IMP=0x00000001001598d8
- (void)performPassThroughScoreRequestsForEnvironment:(long long)arg1;	// IMP=0x00000001001590c4
- (void)performPassThroughAchievementRequestsForEnvironment:(long long)arg1;	// IMP=0x00000001001588b0
- (id)removeFriendWriterWithCredential:(id)arg1;	// IMP=0x00000001001582f0
- (id)removeGameWriterWithCredential:(id)arg1;	// IMP=0x000000010015824c
- (id)deletePlayerPhotoWriterWithCredential:(id)arg1;	// IMP=0x00000001001581a8
- (id)setPlayerPhotoWriterWithCredential:(id)arg1;	// IMP=0x0000000100158104
- (id)setPlayerStatusWriterWithCredential:(id)arg1;	// IMP=0x0000000100158060
- (id)abortChallengesWriterWithCredential:(id)arg1;	// IMP=0x0000000100157fbc
- (id)issueChallengesWriterWithCredential:(id)arg1;	// IMP=0x0000000100157f18
- (id)submitAchievementsWriterWithCredential:(id)arg1;	// IMP=0x0000000100157e60
- (id)submitRatingsWriterWithCredential:(id)arg1;	// IMP=0x0000000100157dbc
- (id)submitScoresWriterWithCredential:(id)arg1;	// IMP=0x0000000100157d18
- (id)_delayedRequestWriterWithCacheWriterClass:(Class)arg1 cacheReaderClass:(Class)arg2 networkWriterClass:(Class)arg3 bagKey:(id)arg4 batchSubmissionInterval:(long long)arg5 credential:(id)arg6;	// IMP=0x00000001001579a0
- (void)_removeDelayedRequestStore;	// IMP=0x000000010015736c
- (void)_setupDelayedRequestsWriters;	// IMP=0x0000000100157144
- (id)requestsCacheForEnvironment:(long long)arg1;	// IMP=0x0000000100156ef8
- (id)storeAndForwardDirectoryPathForEnvironment:(long long)arg1;	// IMP=0x0000000100156e90

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

