//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "ImageConversionService-Protocol.h"
#import "MediaConversionQueueDelegate-Protocol.h"
#import "NSXPCListenerDelegate-Protocol.h"

@class MediaConversionQueue, NSString, NSXPCListener;

__attribute__((visibility("hidden")))
@interface ImageConversionService : NSObject <MediaConversionQueueDelegate, ImageConversionService, NSXPCListenerDelegate>
{
    long long _pendingRequestCount;	// 8 = 0x8
    NSXPCListener *_listener;	// 16 = 0x10
    MediaConversionQueue *_requestQueue;	// 24 = 0x18
}

+ (void)run;	// IMP=0x0000000100016310
- (void).cxx_destruct;	// IMP=0x000000010001620c
@property(retain) MediaConversionQueue *requestQueue; // @synthesize requestQueue=_requestQueue;
@property(retain) NSXPCListener *listener; // @synthesize listener=_listener;
@property long long pendingRequestCount; // @synthesize pendingRequestCount=_pendingRequestCount;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x0000000100015eec
- (void)conversionQueueDidFinishProcessingEntry:(id)arg1;	// IMP=0x0000000100015d6c
- (void)conversionQueue:(id)arg1 processNextEntry:(id)arg2;	// IMP=0x0000000100015860
- (id)urlCollectionForBookmarkDictionaryKey:(id)arg1 inOptions:(id)arg2 removeExistingEmptyFiles:(_Bool)arg3 error:(id *)arg4;	// IMP=0x000000010001554c
- (_Bool)convertImageWithOptions:(id)arg1 sourceURLCollection:(id)arg2 outputURLCollection:(id)arg3 outputData:(id *)arg4 outputFileType:(id *)arg5 outputImageInfo:(id *)arg6 error:(id *)arg7;	// IMP=0x00000001000145f0
- (void)enumerateEnvironmentVariablePairsInRequestOptions:(id)arg1 block:(CDUnknownBlockType)arg2;	// IMP=0x000000010001429c
- (void)performEndRequestActionsForUnitTestSupportOptions:(id)arg1;	// IMP=0x00000001000141f0
- (void)performBeginRequestActionsForUnitTestSupportOptions:(id)arg1;	// IMP=0x00000001000140d0
- (void)decrementPendingRequestCountWithRequestIdentifier:(id)arg1;	// IMP=0x0000000100013fe0
- (void)replyToCompletionHandler:(CDUnknownBlockType)arg1 requestIdentifier:(id)arg2 resultData:(id)arg3 resultImageInformation:(id)arg4 error:(id)arg5;	// IMP=0x0000000100013f2c
- (long long)incrementPendingRequestCountWithRequestIdentifier:(id)arg1;	// IMP=0x0000000100013e4c
- (_Bool)validateRequestOptions:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100013af0
- (_Bool)setupSourceAndDestinationForRequestTracker:(id)arg1 imageConversionOptions:(id)arg2 error:(id *)arg3;	// IMP=0x00000001000138e0
- (void)convertImageWithOptions:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100013284
- (void)run;	// IMP=0x00000001000131c8
- (id)init;	// IMP=0x0000000100013154

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

