//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_DASActivityPolicy-Protocol.h"

@class NSArray, NSString;

@interface _DASPhotosPolicy : NSObject <_DASActivityPolicy>
{
    _Bool _photosIsForeground;	// 8 = 0x8
    NSString *_policyName;	// 16 = 0x10
    NSArray *_triggers;	// 24 = 0x18
}

+ (_Bool)isActivity:(id)arg1 consideredNonDiscretionary:(id)arg2;	// IMP=0x00000001000296fc
+ (_Bool)isPhotosMessagesAppForegroundWithContext:(id)arg1;	// IMP=0x00000001000296a4
+ (_Bool)isPhotosForegroundWithContext:(id)arg1;	// IMP=0x00000001000295f8
+ (_Bool)isCMMActivity:(id)arg1;	// IMP=0x00000001000292a4
+ (_Bool)isiCPLActivity:(id)arg1;	// IMP=0x0000000100029128
+ (id)keyPathForBlockedStartDate;	// IMP=0x000000010002911c
+ (id)keyPathForPhotosIsBlocked;	// IMP=0x0000000100029110
+ (id)keyPathForPhotosBudgetOverride;	// IMP=0x0000000100029104
+ (id)keyPathForSignificantWorkRemaining;	// IMP=0x00000001000290f8
+ (id)policyInstance;	// IMP=0x0000000100029058
+ (void)initialize;	// IMP=0x0000000100028cb4
+ (id)photosFocalAppStateChangedPredicate;	// IMP=0x0000000100028c40
- (void).cxx_destruct;	// IMP=0x0000000100029c00
@property(nonatomic) _Bool photosIsForeground; // @synthesize photosIsForeground=_photosIsForeground;
@property(retain, nonatomic) NSArray *triggers; // @synthesize triggers=_triggers;
@property(retain, nonatomic) NSString *policyName; // @synthesize policyName=_policyName;
- (id)responseForActivity:(id)arg1 withState:(id)arg2;	// IMP=0x00000001000297cc
- (_Bool)isEnergyBudgetAvailableForPhotos:(id)arg1;	// IMP=0x00000001000297c4
- (_Bool)isDataBudgetAvailableForPhotos:(id)arg1;	// IMP=0x00000001000297bc
- (double)weightForActivity:(id)arg1;	// IMP=0x00000001000295f0
- (_Bool)appliesToActivity:(id)arg1;	// IMP=0x000000010002957c
- (_Bool)shouldIgnoreTrigger:(id)arg1 withState:(id)arg2;	// IMP=0x0000000100029498
- (_Bool)shouldOverrideSignificantWork:(id)arg1;	// IMP=0x00000001000293f4
- (_Bool)shouldOverrideBudgets:(id)arg1;	// IMP=0x000000010002939c
- (_Bool)haveSignificantWorkRemaining:(id)arg1;	// IMP=0x0000000100029344
- (id)init;	// IMP=0x0000000100028fd4
- (id)initializeTriggers;	// IMP=0x0000000100028d94

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

