//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_DASDataStore-Protocol.h"

@class NSString, _DASCoreDataStorage;

@interface _DASCoreDataStore : NSObject <_DASDataStore>
{
    _DASCoreDataStorage *_database;	// 8 = 0x8
}

+ (id)storageWithDirectory:(id)arg1 readOnly:(_Bool)arg2;	// IMP=0x0000000100014074
- (void).cxx_destruct;	// IMP=0x0000000100017074
@property(retain, nonatomic) _DASCoreDataStorage *database; // @synthesize database=_database;
- (void)deleteActivitiesIfRequired;	// IMP=0x0000000100016ed4
- (void)deleteOldActivities;	// IMP=0x0000000100016d48
- (void)deleteActivity:(id)arg1;	// IMP=0x0000000100016b90
- (_Bool)deleteStorageWithObliterationOption:(_Bool)arg1;	// IMP=0x0000000100016b20
- (void)updateActivityCanceled:(id)arg1;	// IMP=0x00000001000169b4
- (void)updateActivityCompleted:(id)arg1;	// IMP=0x0000000100016848
- (void)updateActivityStarted:(id)arg1;	// IMP=0x00000001000166dc
- (void)loadAllGroups:(id)arg1;	// IMP=0x000000010001643c
- (void)loadStartedTasks:(id)arg1;	// IMP=0x0000000100016158
- (void)loadPendingLaunchTasks:(id)arg1;	// IMP=0x0000000100015d78
- (void)saveActivity:(id)arg1 group:(id)arg2 triggers:(id)arg3 hasStarted:(_Bool)arg4;	// IMP=0x0000000100015b18
- (void)loadAllTasks:(id)arg1 startedTasks:(id)arg2;	// IMP=0x0000000100015810
- (void)saveGroups:(id)arg1 activitiesArray:(id)arg2;	// IMP=0x00000001000155d8
- (void)saveGroup:(id)arg1 activity:(id)arg2;	// IMP=0x00000001000153cc
- (void)saveGroup:(id)arg1;	// IMP=0x000000010001526c
- (void)createMOInMOC:(id)arg1 group:(id)arg2 activities:(id)arg3;	// IMP=0x0000000100015048
- (void)saveActivities:(id)arg1 groups:(id)arg2 triggersArray:(id)arg3;	// IMP=0x0000000100014bf4
- (void)saveActivity:(id)arg1 triggers:(id)arg2;	// IMP=0x00000001000149fc
- (void)saveActivities:(id)arg1;	// IMP=0x00000001000147a0
- (void)saveActivity:(id)arg1;	// IMP=0x0000000100014640
- (void)createMOInMOC:(id)arg1 activity:(id)arg2 group:(id)arg3 triggers:(id)arg4;	// IMP=0x00000001000143f0
- (void)mocSaveAndReset:(id)arg1;	// IMP=0x0000000100014294
- (id)initWithDirectory:(id)arg1 readOnly:(_Bool)arg2;	// IMP=0x00000001000140ec
- (id)init;	// IMP=0x00000001000140d4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

