//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WLKConnectionServerProtocol-Protocol.h"

@class NSString, NSXPCConnection;
@protocol WLDClientConnectionDelegate, WLKConnectionClientProtocol;

__attribute__((visibility("hidden")))
@interface WLDClientConnection : NSObject <WLKConnectionServerProtocol>
{
    id <WLKConnectionClientProtocol> _remoteObjectProxy;	// 8 = 0x8
    NSXPCConnection *_connection;	// 16 = 0x10
    NSString *_clientIdentifier;	// 24 = 0x18
    id <WLDClientConnectionDelegate> _delegate;	// 32 = 0x20
}

+ (id)_sanitizeError:(id)arg1;	// IMP=0x00000001000084bc
+ (id)_sanitizeDictionary:(id)arg1;	// IMP=0x0000000100008220
- (void).cxx_destruct;	// IMP=0x0000000100008678
@property(nonatomic) __weak id <WLDClientConnectionDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy, nonatomic) NSString *clientIdentifier; // @synthesize clientIdentifier=_clientIdentifier;
@property(readonly, nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
- (void)_didInvalidate;	// IMP=0x0000000100008168
- (void)refreshSubscriptionData:(_Bool)arg1;	// IMP=0x0000000100008034
- (void)fetchSubscriptionData:(_Bool)arg1 callerProcessID:(int)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100007d34
- (void)clearOffers:(CDUnknownBlockType)arg1;	// IMP=0x0000000100007bc0
- (void)fetchOffers:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100007a1c
- (void)saveOffer:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010000788c
- (void)prewarm;	// IMP=0x0000000100007804
- (void)fetchLocationAuthorizationStatus:(CDUnknownBlockType)arg1;	// IMP=0x0000000100007690
- (void)fetchSettings:(CDUnknownBlockType)arg1;	// IMP=0x00000001000074c4
- (void)postSettings:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100007270
- (void)writeSettingsStore:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000070e0
- (void)readSettingsStore:(CDUnknownBlockType)arg1;	// IMP=0x0000000100006f6c
- (void)fetchApplications:(CDUnknownBlockType)arg1;	// IMP=0x0000000100006df8
- (void)ping;	// IMP=0x0000000100006ddc
- (void)requestConsentForBundleID:(id)arg1 forceAuth:(_Bool)arg2 replyHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100006c2c
- (void)checkPendingPlaybackReports;	// IMP=0x0000000100006be4
- (void)endPlaybackSession:(id)arg1;	// IMP=0x0000000100006b74
- (void)reportPlayback:(id)arg1 sessionID:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000069b4
- (void)reportPlayback:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100006960
- (void)requestDecoratedNowPlayingSummaries:(CDUnknownBlockType)arg1;	// IMP=0x00000001000067ec
- (void)requestNowPlayingSummaries:(CDUnknownBlockType)arg1;	// IMP=0x0000000100006610
- (void)deletePlaybackActivityWithIdentifier:(id)arg1 bundleID:(id)arg2;	// IMP=0x000000010000644c
- (id)initWithConnection:(id)arg1 clientIdentifier:(id)arg2;	// IMP=0x00000001000061d0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

