//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class EAOverHID, FudIpcDispatch, FudStorage, NSMutableArray, UARPManagerAUD;
@protocol OS_dispatch_queue, OS_dispatch_queue_attr, OS_dispatch_source, OS_xpc_object;

__attribute__((visibility("hidden")))
@interface FudController : NSObject
{
    NSObject<OS_xpc_object> *_listener;	// 8 = 0x8
    long long _idleExitTimeoutSec;	// 16 = 0x10
    _Bool _isRunningTimer;	// 24 = 0x18
    _Bool _isIdleExiting;	// 25 = 0x19
    _Bool _isWatchingGroup;	// 26 = 0x1a
    _Bool _isInstallerUpdate;	// 27 = 0x1b
    _Bool _isDeviceIdleLaunch;	// 28 = 0x1c
    _Bool _isMayRebootLaunch;	// 29 = 0x1d
    _Bool _isSimulatedDeviceIdleLaunch;	// 30 = 0x1e
    _Bool _simulateIdleUseFilepath;	// 31 = 0x1f
    NSObject<OS_dispatch_source> *_idleTimer;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_timeoutQueue;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_processingQueue;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_eaOverHIDQueue;	// 56 = 0x38
    EAOverHID *_eaOverHID;	// 64 = 0x40
    NSObject<OS_dispatch_queue_attr> *_attr;	// 72 = 0x48
    FudIpcDispatch *_fudIpcDispatch;	// 80 = 0x50
    unsigned long long _numProcessedConnection;	// 88 = 0x58
    FudStorage *_fudStorage;	// 96 = 0x60
    NSMutableArray *_defaultClients;	// 104 = 0x68
    NSObject<OS_dispatch_queue> *_uarpQueue;	// 112 = 0x70
    UARPManagerAUD *_uarpManager;	// 120 = 0x78
    NSObject<OS_dispatch_source> *_usr1SignalSource;	// 128 = 0x80
}

- (void)doPeriodicCheck;	// IMP=0x000000010000f2d4
- (void)doInstallerCheck;	// IMP=0x000000010000ee7c
- (void)doDeviceIdleCheck;	// IMP=0x000000010000ea34
- (void)doSimulateIdleCheck;	// IMP=0x000000010000e954
- (void)doMayRebootCheck;	// IMP=0x000000010000e514
- (void)setActivityForPeriodicLaunch:(_Bool)arg1;	// IMP=0x000000010000e1a4
- (void)setActivityForDeviceIdleLaunch:(_Bool)arg1;	// IMP=0x000000010000debc
- (void)setActivityForMayRebootLaunch:(_Bool)arg1;	// IMP=0x000000010000dbe0
- (_Bool)initializeFud;	// IMP=0x000000010000d748
- (void)notifyClientsOfInstallerUpdate:(_Bool)arg1;	// IMP=0x000000010000d594
- (_Bool)startDefaultClients;	// IMP=0x000000010000d4d8
- (_Bool)setupXPCStreamsWithPolicies:(id)arg1 shouldRegister:(_Bool)arg2;	// IMP=0x000000010000d0cc
- (void)registerForNotifydNotification:(id)arg1 filterName:(id)arg2;	// IMP=0x000000010000cf98
- (id)loadPolicyForAllPlugins;	// IMP=0x000000010000cd38
- (id)loadPolicyForAllServices;	// IMP=0x000000010000ca84
- (void)handleXPCAPIEvent:(id)arg1;	// IMP=0x000000010000c77c
- (_Bool)clientHasEntitlements:(id)arg1;	// IMP=0x000000010000c740
- (void)processAPIDict:(id)arg1;	// IMP=0x000000010000c40c
- (void)handleInternalAPIEvent:(id)arg1;	// IMP=0x000000010000c2d0
- (void)handleXPCStreamEvent:(id)arg1;	// IMP=0x000000010000bd00
- (void)handleEAOverHIDXPCStreamEvent:(id)arg1 forFilterName:(id)arg2;	// IMP=0x000000010000bb40
- (void)handleBrokenConnection:(id)arg1;	// IMP=0x000000010000ba64
- (_Bool)processEvent:(id)arg1;	// IMP=0x000000010000b9ac
- (void)watchSharedGroup;	// IMP=0x000000010000b830
- (void)initIdleTimer;	// IMP=0x000000010000b728
- (void)cancelIdleTimer;	// IMP=0x000000010000b670
- (void)beginIdleTimer;	// IMP=0x000000010000b520
- (void)handleIdleTimeout;	// IMP=0x000000010000b460
- (_Bool)isWorkPending;	// IMP=0x000000010000b3fc
- (void)idleExit;	// IMP=0x000000010000b2e8
- (void)handleInternalClientMessage:(id)arg1;	// IMP=0x000000010000b1b8
- (void)setActivityForUARPPeriodicLaunch:(_Bool)arg1;	// IMP=0x000000010000aed8
- (void)initSignals;	// IMP=0x000000010000ae2c
- (void)initUARP:(_Bool)arg1;	// IMP=0x000000010000ad98
- (id)initWithIdleTimeout:(long long)arg1;	// IMP=0x000000010000ab74

@end

