/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, April 14, 2021 at 2:38:58 PM Mountain Standard Time
                       * Operating System: Version 14.4 (Build 18K802)
                       * Image Source: /usr/lib/libpartition2_dynamic.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <MSUDataAccessor/LPMedia.h>

@interface LPPartitionMedia : LPMedia
+(id)primaryMedia;
+(id)contentTypesForPartitionMedia;
+(id)supportedContentTypes;
-(id)children;
-(BOOL)isPrimaryMedia;
@end

