//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSUserDefaults;

@interface ACCAccessoryAuthorizationStore : NSObject
{
    NSUserDefaults *_userDefaults;	// 8 = 0x8
}

+ (id)authorizationEntryForCertSerial:(id)arg1 withAccessoryDict:(id)arg2;	// IMP=0x00000001000eaa5c
+ (id)authorizationEntryForCertSerial:(id)arg1;	// IMP=0x00000001000ea93c
+ (_Bool)removeAccessory:(id)arg1;	// IMP=0x00000001000ea724
+ (_Bool)storeAccessory:(id)arg1;	// IMP=0x00000001000ea3c4
+ (id)storedCertSerialStrings;	// IMP=0x00000001000ea1ac
+ (id)storedAccessories;	// IMP=0x00000001000e9ed8
+ (id)sharedStore;	// IMP=0x00000001000e9e3c
- (void).cxx_destruct;	// IMP=0x00000001000eaba8
@property(retain, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
- (void)knownAccessoriesDidChange:(id)arg1;	// IMP=0x00000001000e9e38
- (void)dealloc;	// IMP=0x00000001000e9dc0
- (id)init;	// IMP=0x00000001000e9c70

@end

