//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IMSystemMonitorListener-Protocol.h"

@class IMTimer, NSMutableDictionary;

@interface IDSDeviceHeartbeatCenter : NSObject <IMSystemMonitorListener>
{
    IMTimer *_getDependentHeartbeatTimer;	// 8 = 0x8
    NSMutableDictionary *_usersToHeartbeatDatesMap;	// 16 = 0x10
    _Bool _isSetup;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x000000010000c22c
- (void).cxx_destruct;	// IMP=0x000000010000ef94
- (void)systemDidWake;	// IMP=0x000000010000ef60
- (void)_cleanupKeychain;	// IMP=0x000000010000edfc
- (_Bool)_fetchExpiryDatesIfNecessary;	// IMP=0x000000010000e82c
- (void)accountsChanged;	// IMP=0x000000010000e11c
- (void)_updateExpiry:(double)arg1 forUser:(id)arg2;	// IMP=0x000000010000db34
- (void)resetExpiryForUser:(id)arg1;	// IMP=0x000000010000d9f0
- (void)_updateDependentRegistrations;	// IMP=0x000000010000d7c0
- (void)_scheduleRescueHeartBeat;	// IMP=0x000000010000d5e0
- (_Bool)_scheduleDependentRegistrations;	// IMP=0x000000010000d2b8
- (void)invalidateTimer;	// IMP=0x000000010000d26c
- (void)printInfo;	// IMP=0x000000010000cd38
- (void)dealloc;	// IMP=0x000000010000cc90
- (id)_getNextExpirationDate;	// IMP=0x000000010000c6e0
- (void)_heartBeat;	// IMP=0x000000010000c598
- (void)setup;	// IMP=0x000000010000c504
- (id)init;	// IMP=0x000000010000c3d8

@end

