//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IDSUser-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSString;

@interface IDSPhoneUser : NSObject <NSCopying, IDSUser>
{
    _Bool _isDefaultUser;	// 8 = 0x8
    NSString *_phoneNumber;	// 16 = 0x10
    NSString *_phoneBookNumber;	// 24 = 0x18
    NSString *_labelID;	// 32 = 0x20
    NSString *_countryCode;	// 40 = 0x28
    NSString *_networkCode;	// 48 = 0x30
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100244b0c
- (void).cxx_destruct;	// IMP=0x00000001002453f4
@property(retain, nonatomic) NSString *networkCode; // @synthesize networkCode=_networkCode;
@property(retain, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(nonatomic) _Bool isDefaultUser; // @synthesize isDefaultUser=_isDefaultUser;
@property(readonly, nonatomic) NSString *labelID; // @synthesize labelID=_labelID;
@property(retain, nonatomic) NSString *phoneBookNumber; // @synthesize phoneBookNumber=_phoneBookNumber;
@property(retain, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(readonly, copy) NSString *description;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100244fe8
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100244ec4
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100244b2c
- (_Bool)differsFromPhoneNumber:(id)arg1;	// IMP=0x000000010024481c
- (_Bool)isIdenticalToUser:(id)arg1;	// IMP=0x000000010024457c
- (_Bool)isEqualToUser:(id)arg1;	// IMP=0x0000000100244504
- (_Bool)isEqualToPhoneUser:(id)arg1;	// IMP=0x00000001002440d0
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100244014
@property(readonly) unsigned long long hash;
- (_Bool)shouldReplace:(id)arg1;	// IMP=0x0000000100243e38
- (id)storageIdentifier;	// IMP=0x0000000100243e04
- (id)unprefixedIdentifier;	// IMP=0x0000000100243d48
- (id)realmPrefixedIdentifier;	// IMP=0x0000000100243bb8
- (long long)realm;	// IMP=0x0000000100243b9c
- (id)uniqueIdentifier;	// IMP=0x0000000100243b68
- (id)phoneUserWithUpdatedDefaultUser:(_Bool)arg1 countryCode:(id)arg2 networkCode:(id)arg3;	// IMP=0x0000000100243a44
- (id)phoneUserWithUpdatedPhoneNumber:(id)arg1;	// IMP=0x000000010024398c
- (id)phoneUserWithUpdatedPhoneNumber:(id)arg1 phoneBookNumber:(id)arg2;	// IMP=0x0000000100243890
- (id)initWithLabelID:(id)arg1 phoneBookNumber:(id)arg2 isDefaultUser:(_Bool)arg3 countryCode:(id)arg4 networkCode:(id)arg5;	// IMP=0x00000001002436ec
- (id)initWithLabelID:(id)arg1 phoneBookNumber:(id)arg2;	// IMP=0x00000001002435d0
- (id)initWithLabelID:(id)arg1;	// IMP=0x00000001002434e8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

