//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMapTable, NSString;

@interface IDSUTunPeerServiceMap : NSObject
{
    NSString *_name;	// 8 = 0x8
    struct os_unfair_lock_s _lock;	// 16 = 0x10
    unsigned char _remoteInstanceID[16];	// 20 = 0x14
    NSMapTable *_serviceNameToStreamIDMap;	// 40 = 0x28
    NSMapTable *_streamIDToServiceNameMap;	// 48 = 0x30
    unsigned short _nextStreamID;	// 56 = 0x38
    unsigned char _previousRemoteInstanceIDs[8][16];	// 58 = 0x3a
    int _nextRemoteInstanceIDIndex;	// 188 = 0xbc
}

- (void).cxx_destruct;	// IMP=0x000000010001d794
- (void)_simulateCrashWithErrorString:(id)arg1;	// IMP=0x000000010001d688
- (void)dumpServiceMap;	// IMP=0x000000010001d5a4
- (void)_dumpServiceMap;	// IMP=0x000000010001d1d0
@property(readonly) unsigned long long count;
- (_Bool)translateServiceName:(id)arg1 toStreamID:(unsigned short *)arg2 createIfNotFound:(_Bool)arg3 mappingCreated:(_Bool *)arg4 remoteInstanceID:(unsigned char (*)[16])arg5 remoteInstanceIDChanged:(_Bool *)arg6;	// IMP=0x000000010001c858
- (_Bool)translateStreamID:(unsigned short)arg1 toServiceName:(id *)arg2 remoteInstanceID:(unsigned char (*)[16])arg3 remoteInstanceIDChanged:(_Bool *)arg4;	// IMP=0x000000010001c418
- (_Bool)associateServiceName:(id)arg1 withStreamID:(unsigned short)arg2 remoteInstanceID:(unsigned char (*)[16])arg3 remoteInstanceIDChanged:(_Bool *)arg4;	// IMP=0x000000010001b94c
- (_Bool)setRemoteInstanceID:(unsigned char (*)[16])arg1;	// IMP=0x000000010001b1ec
- (id)description;	// IMP=0x000000010001b104
- (id)initWithName:(id)arg1;	// IMP=0x000000010001aefc

@end

