//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MCMUserIdentityCache;

@interface MCMContainerMigrator : NSObject
{
    MCMUserIdentityCache *_userIdentityCache;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x000000010003b480
- (void).cxx_destruct;	// IMP=0x000000010003a3d8
@property(retain, nonatomic) MCMUserIdentityCache *userIdentityCache; // @synthesize userIdentityCache=_userIdentityCache;
- (int)_intendedDataProtectionClassBasedOnEntitlementsForIdentifier:(id)arg1;	// IMP=0x000000010003a330
- (_Bool)performPerUserDataMigrationForClientConnection:(id)arg1 withError:(id *)arg2;	// IMP=0x0000000100039914
- (void)_setDataProtectionIfNecessaryOnContainer:(id)arg1;	// IMP=0x0000000100039400
- (id)_bundleContainerForDataContainer:(id)arg1 withError:(id *)arg2;	// IMP=0x0000000100038ff4
- (_Bool)performDataMigratorMigrationForClientConnection:(id)arg1 withError:(id *)arg2;	// IMP=0x0000000100038a88
- (_Bool)performSynchronousBuildUpgradeMigration:(id)arg1 withError:(id *)arg2;	// IMP=0x0000000100037e90
- (_Bool)_migrateBundleContainersWithError:(id *)arg1;	// IMP=0x0000000100037ad0
- (_Bool)_performInternalACLMigrationWithError:(id *)arg1;	// IMP=0x000000010003756c
- (void)_checkIfDeviceMayNeedSystemContainerACLMigration:(id)arg1;	// IMP=0x0000000100037214
- (_Bool)_performWhitelistMigrationWithError:(id *)arg1;	// IMP=0x0000000100036210
- (_Bool)_performBundleContainerOwnershipMigrationWithError:(id *)arg1;	// IMP=0x0000000100035e10
- (id)initWithUserIdentityCache:(id)arg1;	// IMP=0x0000000100035d98

@end

