//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreServices/LSApplicationWorkspaceObserver.h>

@class NSObject;
@protocol LSApplicationWorkspaceObserverProtocol;

@interface WorkspaceDownloadObserver : LSApplicationWorkspaceObserver
{
    NSObject<LSApplicationWorkspaceObserverProtocol> *_delegate;	// 8 = 0x8
}

- (void)applicationInstallsDidPrioritize:(id)arg1;	// IMP=0x00000001001e69b8
- (void)applicationInstallsDidCancel:(id)arg1;	// IMP=0x00000001001e69a0
- (void)applicationInstallsDidResume:(id)arg1;	// IMP=0x00000001001e6988
- (void)applicationInstallsDidPause:(id)arg1;	// IMP=0x00000001001e6970
- (void)applicationInstallsArePrioritized:(id)arg1 arePaused:(id)arg2;	// IMP=0x00000001001e6958
- (void)applicationsDidUninstall:(id)arg1;	// IMP=0x00000001001e6940
- (void)applicationsDidInstall:(id)arg1;	// IMP=0x00000001001e6928
- (void)applicationInstallsDidChange:(id)arg1;	// IMP=0x00000001001e6910
- (void)applicationInstallsDidStart:(id)arg1;	// IMP=0x00000001001e68f8
@property(nonatomic) NSObject<LSApplicationWorkspaceObserverProtocol> *delegate;
- (void)stopObserving;	// IMP=0x00000001001e689c
- (void)startObserving;	// IMP=0x00000001001e6860

@end

